### ISSUE TITLE
Smoke tests and Characterisation tests with small data sets

### ISSUE THREAD

**Issue by gillesdegottex** [CSTR-Edinburgh/merlin#1]
Hi,

First, thanks a lot for sharing this on Github, I'm sure this will help to easily manage contributions.

I think it would be good to add some scripts for testing purpose.
The main motivation is because research tools like Merlin are very likely to be modified (they are not supposed to converge to something specific and stable) and, thus, it is necessary that previous behaviors are still reproducible with newer versions.

Two things to realize this:
- Smoke tests: a script that runs the pipeline with many different configurations using very small train/valid/test sets, in order to check that the previous features are still runnable (basically no crash).
- Characterisation tests: Using bigger train/valid/test sets, the pipeline can be run on standard configuration (e.g. one DNN and one LSTM). Then, the objectives measures can be used to verify that the results do not change for these configurations.

What do you think ?
Cheers,

**Comment by ronanki** [comment]
Hi,

First of all, thank you for your suggestions. I am also thinking on the same lines. 

I will be preparing some short and full data - one speaker from Arctic (16 khz sampling frequency) and one other speaker (with 48khz sampling frequency). 

The data will be uploaded somewhere in our servers and is publicly accessible. 

We are also looking to support phoneme alignments (rather than forcing everyone to use state labels). Once this is done, I will be uploading the data -- you can help me writing the test scripts, if you have time. 

Cheers
Srikanth

**Comment by gillesdegottex** [comment]
Great. I can start writting a script to automatically test the pipeline on DNN and LSTM using the data in dnn_baseline_practice that Zhizheng gave us. We can still change the data later on anyway.

Using phoneme alignement, how will the states be aligned on the data ? just uniformly ? there is no expected loss in doing so ?

**Comment by ronanki** [comment]
That would be great.

There won't be any states.  3 numerical features for coarse-coded position of the current frame in the current phoneme and 1 numerical feature for duration of the current segment are used -- as suggested in the paper by Heiga zen. (http://static.googleusercontent.com/media/research.google.com/en//pubs/archive/40837.pdf)

**Comment by ronanki** [comment]
Hi,

I revamped the Merlin scripts -- added example demo directory in egs. Also, created some scripts to automatically setup the workspace, create config files and run the models. 

Can you please check with the latest setup, if possible? Also, can you please update me on the progress with your scripts to automatically test the pipeline? 

Cheers
Srikanth

**Comment by gillesdegottex** [comment]
Well, it seems I can refactor what I did :P

Could you drop a subset of slt voice somwhere ? (like 50 sentences only)

**Comment by ronanki** [comment]
At the moment, the scripts in egs/slt_arctic does the same -- the demo runs only on 60 files. But, the setup.sh downloads all the files -- so that we can do Smoke tests with file_id_list_demo.scp and later Characterisation tests with file_id_list.scp 

Does that make any sense?

**Comment by gillesdegottex** [comment]
Fully sense! You actually did what I thought to do :D
For the charac. test. I'll make a script that compare the obj. meas. with saved ones.

**Comment by gillesdegottex** [comment]
Done in #4

**Comment by gillesdegottex** [comment]
BTW, I really like the way you reorganized the files, much cleaner!

For the generation of the config files, there might be a simpler solution though:
We could put templates config files in misc/recipes/general_config/
and modify them in setup.sh (using sed) under the "### default settings ###" section

In doing so, you get rid of both prepare_config_files.sh script, which is a bit heavy, and global_settings.cfg, which repeats the content of the conf files.

what do you think ?

**Comment by ronanki** [comment]
Thank you.

The current scripts are written without much thought -- just aiming for automatic end-to-end system building without configuring anything. 

We need global settings file -- for those who want to tweak or set only few important parameters. Going forward, we might end up with too many configurable variables in conf files and hence global conf file is required for demo purpose.

However, the creation of config files can be changed. But, at the moment, I am concentrating more on restructuring the source code for training DNN.

**Comment by gillesdegottex** [comment]
Ok, I understand.
So I would just suggest to copy the conf files from misc/recipes/ and modify them according to global_settings.cfg. I'm happy to do it if you want.

**Comment by dreamk73** [comment]
I just wanted to comment on this. Thanks for writing the demo scripts. I had to set up a new machine today for our DL research. I was running this code on my Msi gaming laptop with a GTX860 processor on Ubuntu. And now I am running it on a desktop with the new GTX1080 processor. The speed-up is significant. 

To run the full script the train_DNN step for the duration model took 4.52m on the laptop and it takes 2.21m on the server. But more impressively, the train_DNN step for the acoustic model took 39.39m on my laptop and only 6.05m on the server.

**Comment by gillesdegottex** [comment]
Could you give us your numpy and theano version ?
This should be printed in your log at the beginning.

I ask you this because I experienced huge differences of running time between numpy/theano versions.

**Comment by dreamk73** [comment]
I didn't know that. My laptop has newer versions at the moment. Theano is 0.9.0dev1.dev and numpy is 1.11.1. The new machine was initially configured by someone else so it has theano 0.8.2 and numpy 1.7.1.

I am planning to upgrade numpy to 1.11.1 as I currently get a message when I load it in python:
/usr/lib64/python2.7/site-packages/numpy/lib/utils.py:254: FutureWarning: Numpy has detected that you (may be) writing to an array returned
by numpy.diagonal or by selecting multiple fields in a record
array. This code will likely break in the next numpy release --
see numpy.diagonal or arrays.indexing reference docs for details.
The quick fix is to make an explicit copy (e.g., do
arr.diagonal().copy() or arr[['f0','f1']].copy()).
  ai = a.__array_interface__

**Comment by sushantakpani** [comment]
Hi,
First of all thanks for merlin.
I have trained slt_arctic_full_data whose output is awesome, now  I want to know how can we test new unseen sentences in merlin. In the case of Festival uss voice we use(SayText "promt" ) command. Is there any provision for testing unseen data?  along with that I want to know  what are the steps/modification  required to train different languages apart from english.

**Comment by gillesdegottex** [comment]
Hi @dreamk73 and @sushantakpani ,

This thread mentions many different issues that are not related to the initial subject. May I ask you to open new issues dedicated to your problems?

@sushantakpani there is currently no easy-going command to synthesis an arbitrary text, because this would need to call a phonetizer. You can provide a list of separate test sentences though (look at test_id_scp).

Thanks
