### ISSUE TITLE
Too slower performance

### ISSUE THREAD

**Issue by Ali20177** [CSTR-Edinburgh/merlin#106]
Hi all,

I am trying to run full_voice using TANH_TANH_TANH_TANH_TANH_LSTM under CPU, but the process is too slow and I didn't get any epoch ran. I was waiting around 8 hours and nothing happened, just waiting ...

I don't have a GPU. But when I using TANH_TANH_TANH_TANH_TANH_TANH, it works with less hours and 25 epochs. My problem is when I using LSTM.

Thanks in advance

**Comment by ronanki** [comment]
Did you set sequential_training to True? See how much time it takes for demo voice before proceeding to full voice. Also, use SLSTM -- which is simplified version of LSTM and is quite faster compared to LSTM with similar performance.

**Comment by Ali20177** [comment]
Thank you very much for quick reply. I'll do that now using SLSTM and let you know the progress.

By the way, which is the best for training using TANH_TANH_TANH_TANH_TANH_SLSTM OR 
SLSTM_SLSTM_SLSTM_SLSTM_SLSTM_SLSTM?

Best regards,

**Comment by ronanki** [comment]
Go with TANH_TANH_TANH_TANH_TANH_SLSTM or TANH_TANH_TANH_TANH_SLSTM_SLSTM -- the more you replace, it becomes further slow.

**Comment by Ali20177** [comment]
It works with TANH_TANH_TANH_TANH_SLSTM.

Thanks ...
