### ISSUE TITLE
WORLD vocoder

### ISSUE THREAD

**Issue by Ali20177** [CSTR-Edinburgh/merlin#108]
Hi all,

How can I use WORLD vocoder alone without using any DNN training and without parameters generation?
I mean just analysis and synthesis under Merlin toolkit.

Thanks in advance ....

**Comment by RasmusD** [comment]
Two options:

1. For the original world - simply download it here and run it on your
wavs: http://ml.cs.yamanashi.ac.jp/world/english/

2. For the version packed with Merlin - simply run the acoustic feature
extraction step on the wavs, then run the synthesis step on those extracted
features.

The difference is that the original world does not natively create the kind
of MGC, BAP and LF0 features extracted for Merlin DNN modelling - this is a
modification performed to allow for easier modelling - so the results will
be a little bit different depending on the method.

- Rasmus

2017-03-07 11:04 GMT+00:00 Ali20177 <notifications@github.com>:

**Comment by ronanki** [comment]
You can use below scripts to do analysis-synthesis:
https://github.com/CSTR-Edinburgh/merlin/tree/master/misc/scripts/vocoder/world

**Comment by Ali20177** [comment]
Thank you very much for both of you .... It works for me.
