### ISSUE TITLE
Alignment file for input sentence

### ISSUE THREAD

**Issue by dhm42** [CSTR-Edinburgh/merlin#109]
Hi, I want to test Merlin with my own sentences. So, I used the slt_arctic_demo and I added the sentence
( arctic_as "The fourth most popular country in the worl." ) to the  "cmuarctic.data" file  and changed the "test_id_list.scp" to contain only "arctic_as".
Now I run the ./run_demo.sh with only the 1,4 and 5 steps and the script prompts that the alignmnent file :
.../test_synthesis/prompt-lab/arctic_as.lab  can't be found.
Why does Merlin need an alignment file for an input text sentence? A TTS system should only have a text as input. Did I miss something ?
Thanks in advance for your help.

**Comment by simonkingedinburgh** [comment]
Yes, you missed something. You need to put the text through a text processor (often called a "front end") to extract linguistic features from the text. Merlin deliberately does not include a front end, because that component is language-specific and hard to build. For English, you can use Festival.

**Comment by dhm42** [comment]
Thank you for your answer. The linguistic features extracted by Festival include only the phoneme decomposition or do Festival give other important features to Merlin ? For instance the alignment file contains the duration of each phoneme and this information should be computed bu the duration model of Merlin.

**Comment by ronanki** [comment]
use [merlin_synthesis.sh](https://github.com/CSTR-Edinburgh/merlin/blob/master/egs/slt_arctic/s1/merlin_synthesis.sh) for synthesizing new test sentences -- if you have festival installed in tools.

**Comment by dhm42** [comment]
Thanks ronanki, I know that the script prepare_labels_from_txt.sh is used to create the labels file from text. The labels are saved in prompt-lab directory. Those labels files already contains alignment:
**0 50000** x^x-sil+sil=ao@x_x/A:0_0_0/B:x-x-x@x-x&x-x#x-x$x-x!x-x;x-...
**50000 100000** x^x-sil+sil=ao@x_x/A:0_0_0/B:x-x-x@x-x&x-x#x-x$x-x!x-x;x-...
**100000 150000** x^x-sil+sil=ao@x_x/A:0_0_0/B:x-x-x@x-x&x-x#x-x$x-x!x-x;x-...
**150000 1700000** x^x-sil+sil=ao@x_x/A:0_0_0/B:x-x-x@x-x&x-x#x-x$x-x!x-x;x-...

My question is, why does this labels **input** files for Merlin already contains duration information? It's Merlin duration model who should compute the durations.
THanks again for your help.

**Comment by m-toman** [comment]
Hi, 

AFAIK the duration model takes the labels from prompt-lab, replaces the durations and places the results in gen-lab.

**Comment by ronanki** [comment]
As said above, those durations will be replaced with predictions from duration model. The labels from Festival contain durations generated by some default voice -- Merlin doesn't use them at all but the code expects the labels to be in the same format as training label files. You can even test it by replacing all those values with some junk numbers or with a constant.

**Comment by dhm42** [comment]
M-toman & ronanki, it's clearer now, thank you for your explanation.

**Comment by Bladechou** [comment]
Hi, I  have installed festival by the command "sudo apt-get install festival festvox-kallpc16k", then I run the " ./run_demo.sh " step and step, but the script prompts that the alignmnent file :
IOError: [Errno 2] No such file or directory: '.../merlin/egs/slt_arctic/s1/experiments/slt_arctic_demo/test_synthesis/prompt-lab/arctic_as.lab'
I don't konw how to solve this prolem. Could give me some advice?
Thanks in advance for your help.

**Comment by Jackiexiao** [comment]
@Bladechou 
You can follow my instruction to install festival correctly and create your own label [Create your own label Using Festival](https://shimo.im/doc/2oZBCNoeFLMzFbg8/)

**Comment by Bladechou** [comment]
@Jackiexiao 
      Happy to receive your answer.  I read your scripy " Create your own label Using Festival ", and I complete the first three steps, but I don't know how to set path in step 4 ?

**Comment by Jackiexiao** [comment]
Linux shell terminal
``` 
bash ~$ export FESTVOXDIR=/home/awb/projects/festvox/
```

**Comment by Bladechou** [comment]
@Jackiexiao 
       I read the "Please read the README.md " in  "5.Using Merlin to generate label ", and  how to do that Step 2: Please configure paths to all tools in config.cfg

**Comment by Jackiexiao** [comment]
By default, paths is merlin/tools , so you don't need to configure paths to all tools in config.cfg
