### ISSUE TITLE
Synthesis from hts 'gen' labels

### ISSUE THREAD

**Issue by oytunturk** [CSTR-Edinburgh/merlin#111]
After training an acoustic and duration model with my own data, I noticed start and end times are required in test label files in order for synthesis to work. Is there a way to use hts 'gen' style labels, i.e. full-context labels without any timing information as it would be the case for 'real' test data for which no recordings/alignments exist?

Thanks!

Oytun

**Comment by ronanki** [comment]
One function similar to [load_labels_with_phone_alignment](https://github.com/CSTR-Edinburgh/merlin/blob/master/src/frontend/label_normalisation.py#L313-L403) has to be written for such format. And another one similar to [modifying](https://github.com/CSTR-Edinburgh/merlin/blob/master/src/frontend/label_modifier.py#L116-L161) labels with predicted durations. 

Hoping to write those functions some time soon.

**Comment by oytunturk** [comment]
Thanks! I was wondering if synthesis used the durations I provided (from original alignments) which would make it sound presumably better than predicted ones. I will try as you suggested.
