### ISSUE TITLE
Include duration training in acoustic_model?

### ISSUE THREAD

**Issue by dreamk73** [CSTR-Edinburgh/merlin#116]
Why is it necessary to train the duration model separately from the acoustic model? When you train the acoustic model you are already training lf0, bap, mgc parameters, why couldn't you add the duration there as well?

**Comment by simonkingedinburgh** [comment]
How would the acoustic model know how many frames to generate?

-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by dreamk73** [comment]
Ah yes, that is a crucial part that I overlooked ;).
