### ISSUE TITLE
Vocoder must be WORLD?

### ISSUE THREAD

**Issue by shuipi100** [CSTR-Edinburgh/merlin#118]
tools don't contain the straight, If I need to copy straightV40 to here?

**Comment by ronanki** [comment]
STRAIGHT is licensed and we can't provide or distribute along with merlin. If you have license to STRAIGHT, please copy the C executables in "tools/bin/straight"

**Comment by shuipi100** [comment]
Thank you！



shenquanbo100@163.com
 
From: Srikanth Ronanki
Date: 2017-03-17 15:58
To: CSTR-Edinburgh/merlin
CC: shuipi100; Author
Subject: Re: [CSTR-Edinburgh/merlin] Vocoder must be WORLD? (#118)
STRAIGHT is licensed and we can't provide or distribute along with merlin. If you have license to STRAIGHT, please copy the C executables in "tools/bin/straight"
