### ISSUE TITLE
wave files

### ISSUE THREAD

**Issue by Ali20177** [CSTR-Edinburgh/merlin#119]
Dear all,

If I need to change the wave sounds to different ones, is it enough to replace the existing wav folder in "egs\slt_arctic\s1\slt_arctic_full_data\wav" to different style of speakers (eg. from female to male or child)?

Hope you understand my question.
Appreciated you help in advance.

**Comment by RasmusD** [comment]
No. You should also create updated lab files with an alignment which is
suitable for the new wav files you have copied in.

You will probably also want to play around with various parameters such as
those for f0 extraction considering that you might want to do childs speech
the standard aprameters are not suitable.

- Rasmus

2017-03-18 12:46 GMT+00:00 Ali20177 <notifications@github.com>:

**Comment by Ali20177** [comment]
Thanks for your reply. Can I ask you that how can I create updated lab files based Merlin_NN?

Regards,

**Comment by RasmusD** [comment]
If you look in the egs/build_your_own_voice folder and read the README.md
and 01-04 scripts there are pointers to how to create labs using festival
and producing either state-level or phone-level alignments.

- Rasmus

2017-03-18 13:51 GMT+00:00 Ali20177 <notifications@github.com>:

**Comment by Ali20177** [comment]
Thanks again for your reply. 

One more question please, if male and female said the same sentence (for example: "Nice to meet you") does the state_align or phon_align should be the same for both male and female?
In other words, can I use the phon or state alignment for female to a male if they said the same sentence?

Thanks and best regards,

**Comment by RasmusD** [comment]
No, you have to redo the alignment as it is specific to each wav file.

2017-03-18 21:49 GMT+00:00 Ali20177 <notifications@github.com>:

**Comment by Ali20177** [comment]
Thanks a lot ....
