### ISSUE TITLE
Running Merlin on a cluster of GPUs

### ISSUE THREAD

**Issue by pglushkov** [CSTR-Edinburgh/merlin#122]
Hello all!

I've been trying to figure out if training a model in Merlin can be speed-up using several GPUs. As far as I can see:
1) Running Merlin on a GPU cluster == running Theano on a GPU cluster
2) To run Theano on a GPU cluster one must not only modify flags/configs, but also to explicitly write the code, so that it would use several gpu devices ( see http://deeplearning.net/software/theano/tutorial/using_multi_gpu.html )
3) I could not find in Merlin sources anything reminiscent of the code given by the link above

From this I conclude that Merlin (and Theano) in it's current state is unable to 'easily' run DNN training on a GPU without extensive code modification. Am I correct?

**Comment by ronanki** [comment]
As of now, the current code in Merlin is capable of training only on one GPU. However, we are planning to release an extension to Merlin to train the model using Keras (which supports theano and tensorflow as backend) -- which allows to speed-up using cluster of GPUs when used with tensorflow.

**Comment by pglushkov** [comment]
Thank you for the reply! Issue is closed.
