### ISSUE TITLE
Question: duration model vs acoustic model

### ISSUE THREAD

**Issue by dreamk73** [CSTR-Edinburgh/merlin#13]
When running the current run_full_voice demo script, when you create a duration model and an acoustic model, does it use label files generated by the duration model to generate the wave files with the acoustic model? If not, how can we make that happen?

**Comment by ronanki** [comment]
Good question. The scripts for the same are under development and will be ready in a day or two. However, you could still do it with the current setup (but to be configured manually).

1. copy the generated "*.lab" files from duration_model/gen/*/ into acoustic_model/data/label_state_align/ (caution: this will replace original files) 
2. run acoustic model setup again, with only NORMLAB, DNNGEN, GENWAV in the conf file set to True.

Optional: Additionally, you can avoid running on validation set, by using a variable GenTestList under the Main processes section set to True -- by setting this, Merlin reads files from data/test_id_list.scp only.

**Comment by dreamk73** [comment]
Great thanks! 

I will test it with solution #1 for now and will be looking forward to seeing the implementation.

**Comment by ronanki** [comment]
It's fixed now! Please check latest commit!

**Comment by dreamk73** [comment]
Thanks! Pulled latest code.
