### ISSUE TITLE
Free voices

### ISSUE THREAD

**Issue by dhm42** [CSTR-Edinburgh/merlin#130]
Where can I find free voices with their labels files in any given language (english in preference) ?  I just want to try Merlin with different data than the one given in  slt_arctic demo.
Thank you !

**Comment by dreamk73** [comment]
I just posted in #124 about training a merlin voice using the Arctic AWB data which is fairly straightforward and you can perform the same process for all Arctic voices. You can download them from: http://www.festvox.org/cmu_arctic/

But they are all the same size, so you have about 1000 sentences for training.

**Comment by dhm42** [comment]
@dreamk73 thanks a lot for your very helpful answer.
 Can you please share your generated labels or part of them (for any database, on DropBox, google drive...) so that I can test Merlin quickly and have a reference labels to compare when I install Festival and use it for this purpose ?
Thanks in advance.

**Comment by dreamk73** [comment]
I have uploaded my awb.zip to dropbox (link available for a short time: https://www.dropbox.com/s/zvut8pieg4rbg35/awb.zip?dl=0). Note that you need to put it in your merlin/egs directory and then unzip it. I have only done the acoustic_model part with state_align setting. It assumes you have the question file mentioned in conf/acoustic_awb.conf, which I think is the standard one that came with merlin. After unpacking run in merlin/egs/awb:

./scripts/submit.sh <merlindir>/src/run_merlin.sh conf/acoustic_awb.conf

**Comment by dhm42** [comment]
@dreamk73  Thanks a lot. I downloaded the data. 
Yes it is the same default questions file. Thanks again !

**Comment by dreamk73** [comment]
Great, I hope this works for you.

**Comment by dhm42** [comment]
Yes it is working and the result is clear :)

**Comment by dreamk73** [comment]
That is good to hear! I hope this helps you figure out what goes wrong with your French voice.
