### ISSUE TITLE
Question about world vocoder processing?

### ISSUE THREAD

**Issue by sotelo** [CSTR-Edinburgh/merlin#134]
Hey guys,

First of all, thanks for putting all the effort to build Merlin. It's a GREAT resource. I have a question about the WORLD processing and I hope you could help me sort it out.

Can someone explain to me why do you do this in the WORLD processing?
`$sptk/sopr -R -m 32768.0`
As far as I understand, this is taking the root of the spectrum and then multiplying by 32768. However, I have no idea why you do that.

The file is here:
https://github.com/CSTR-Edinburgh/merlin/blob/master/misc/scripts/vocoder/world/extract_features_for_merlin.sh#L65

Thanks a lot!
Jose

**Comment by bajibabu** [comment]
I don't know the exact answer, but I think the computation of mel-cepstral coefficients (MCEPs) involves iteration based optimization. Thus to take care of numerical stability issues they multiplied the spectrum with some large number i.e. 32768(2^15)

**Comment by wuaalb** [comment]
WORLD's harmonic spectral envelope output is squared magnitude. In the script you linked SPTK's `mcep` is invoked with option `-q 3` which is linear magnitude input format, hence the square root.

I'm guessing the multiplication factor is there for historical reasons similar to those bajibabu mentions, although the script uses `-j 0` which disabled Newton-Raphson optimization. The scaling also affects the epsilon added to the periodogram prior to taking its log, but the used value of 1e-8 is probably already low enough to yield similar results with or without scaling.

**Comment by sotelo** [comment]
Hey @wuaalb !

I saw your singing synthesis paper! It's SUPER nice :)
Actually, I'm kind of trying to replicate your setup for the WORLD vocoder. Although, I'm interesting in using it for speech synthesis from non-professional recordings. I'm using pysptk and the wrapper by Jeremy. I'm guessing (because of your contribution to the repos) you used those both, no?

It seems to me that the quality of the generated audio (in terms of noise and deformations) in your paper results is MUCH better than any configuration that I used previously. Do you have some advice on how to get there? Is it mostly because of quality of the original recordings? Is it because you kind of have manual f0?

Alsom thanks @bajibabu for your answer.

Cheers!
Jose

**Comment by ljuvela** [comment]
It probably has something to do with conversions between signed int and float. The value range in 16bit wav/raw files is -32,768 to 32,767, but often you'd expect audio to be float scaled between -1 and 1.

The comments in WORLD's wavread function state that it's "roughly implemented", so there might be some scaling operation missing in the source code (and later compensated in the data extraction script).

https://github.com/CSTR-Edinburgh/merlin/blob/master/tools/WORLD_v2/test/audioio.cpp
