### ISSUE TITLE
Wolrd vocoder frame rate

### ISSUE THREAD

**Issue by theabc123** [CSTR-Edinburgh/merlin#139]
Where can I change the World vocoder rate to go from 200 frames per second  (5msec frame intervals) to 250 frames per second (4msec frame intervals) ? 
Thanks.

**Comment by theabc123** [comment]
@r9y9  Thank you for your answer!  I just updated my issue please see it.

**Comment by r9y9** [comment]
I think there are a few places that need to be changed, e.g. https://github.com/CSTR-Edinburgh/merlin/blob/b74abe4b54a1c34f6c8cdf4464b159b867affa50/tools/WORLD/test/synth.cpp#L293. I haven't looked into config files yet, though.

**Comment by theabc123** [comment]
I changed the framerate in the two files analysis.cpp et synth.cpp and recompiled. After that I used the copy_synthesis.sh to generate acoustic features and regenerate my wav files successfully (the number of generated frames is good also).
I think the problem is not the vocoder, but a parameter given to the models. I am trying to look at src/configuration/configuration.py line 363 
I changed frameshift parameter in my acoustic config file with no success.

**Comment by ronanki** [comment]
If you change the frameshift for acoustic features, you need to change the same for linguistic features as well. check [label normalisation](https://github.com/CSTR-Edinburgh/merlin/blob/master/src/frontend/label_normalisation.py) script.

**Comment by theabc123** [comment]
Hi ronanki, I changed the frame rate in:
- label_normalisation (line: 209, 217, 351, 474, 510, 996 and 1000)
- parameter_generation (188 and 189)
- silence_remover (182 and 187)
Also configuration/configuration.py line 363. The result is better now but still fast and some phonemes are not pronounced. 
I am using phone align, but is there a relation between the number of states and the 5msec framerate?
Can you please tell me if the 0.5 factor in frontend/feature_normalisation_base.py line 163 has any relation with the 5msec framerate.
Should I change other parameters ?
Thanks
