### ISSUE TITLE
How to change spectrum extracted from World into mgc?

### ISSUE THREAD

**Issue by handsomedylan1988** [CSTR-Edinburgh/merlin#14]
Dear all,
I have tried the following steps:
1.    ./analysis arctic_a0001.wav 1.f0 1.sp 1.ap
2. x2x +df 1.sp | sopr -R -m 32768.0 | mgcep -a 0.58 -m 59 -l 1024 -e 1.0E-8 -f 0.0 -q 3 >tmp.mgc

however, the final tmp.mgc is quite different from arctic_a0001.mgc which is provided in data/
So how can I extract the correct mgc from sp based on WORLD?

Many thanks

**Comment by dreamk73** [comment]
Have you tried with mgcep -a 0.42? It looks like the arctic_a0001.wav is 16000Hz so then you would use 0.42 instead of 0.58.

**Comment by ronanki** [comment]
The scripts for extracting parameters are here:

https://github.com/CSTR-Edinburgh/merlin/tree/master/misc/scripts/vocoder/world

**Comment by handsomedylan1988** [comment]
Thank ronanki,  I have found the problems by compare my script with
 https://github.com/CSTR-Edinburgh/merlin/tree/master/misc/scripts/vocoder/world
1. There are two "analysis" , one is located in /WORLD/ and the other is located in /WORLD/build, you should use /WORLD/build/analysis , It seems the results are quite different from each other.
2. you should use mcep instead of mgcep.
Here is the fixed version:
1. cd tools/WORLD
2./build/analysis arctic_a0001.wav 1.f0 1.sp 1.ap
2. x2x +df a.sp | sopr -R -m 32768.0 | mcep -a 0.58 -m 59 -l 1024 -e 1.0E-8 -j 0 -f 0.0 -q 3 >tmp.mgc
