### ISSUE TITLE
How to create plot of (train/dev) training convergence?

### ISSUE THREAD

**Issue by bimahasto** [CSTR-Edinburgh/merlin#152]
in function from "/src/run_merlin.py"
I tried to change:

**def train_DNN**(...
                        plot=True
                       ...)

But it doesn't work

**Comment by ronanki** [comment]
Set variable [plot](https://github.com/CSTR-Edinburgh/merlin/blob/master/src/configuration/configuration.py#L163) to True. 

Before running the code, create a directory named "plot" besides data directory.
