### ISSUE TITLE
Normalize_lab_for_merlin.py and Merlin label files

### ISSUE THREAD

**Issue by DavidTofu** [CSTR-Edinburgh/merlin#156]
Hi, 

What exactly is normalize_lab_for_merlin.py doing, especially in the case of phone_align?

**Comment by ronanki** [comment]
It is a multi-purpose code:
1. Normalize duration to nearest divisible number by 5. Say 1.413 -> 1.415 
2. Merge consecutive silence phones or pause phones to one. 
3. Get rid of timestamps if required -- input format for HTK alignment

**Comment by DavidTofu** [comment]
Thanks @ronanki . Running the script on some label files generated by the Makefile in data/ of an HTS voice results in about half of the files still retaining "pau". I see the conditionals in the script that prevent the "pau"s from being replaced, but I don't know exactly what their purpose is. After doing the 3 steps above, why not do a simple substitution for all instances of pau into sil?

**Comment by ronanki** [comment]
No, it doesn't replace 'pau' with 'sil' -- both phones are used. Sometimes, the alignment may yield consecutive pauses or consecutive sil phones in the beginning -- in which case, the consecutive 'pau' phones are replaced with single 'pau' and consecutive 'sil' phones are replaced with one 'sil' phone, merging the duration.
