### ISSUE TITLE
run keras_merlin_io.py has different input and output features for all test files

### ISSUE THREAD

**Issue by satyam1729** [CSTR-Edinburgh/merlin#158]
On running keras_merlin_io.py, The training is performed okay but as soon as it starts testing it shows
The number of frames in input and output features are different: 563 vs 514 (arctic_a0056).
I don't understand why they are different? 
The line abs(inp_frame_number-out_frame_number)>5:  added in the keras_lib/data_utils considers that they can have difference of 5. The code for that line is <a href='https://github.com/CSTR-Edinburgh/merlin/blob/master/src/keras_lib/data_utils.py#L43'> here </a>
when I checked removing the condition of difference and printing input and output features, they are different for all files used for testing but same for files in training

**Comment by ronanki** [comment]
Thanks for pointing out -- it's now fixed. 

For test files, the input (linguistic) features use predicted duration and doesn't match with length of output (acoustic) features. Therefore, code has been slightly modified -- to read only test input.
