### ISSUE TITLE
Is there any official tutorial/document for merlin ?

### ISSUE THREAD

**Issue by Jackiexiao** [CSTR-Edinburgh/merlin#159]
Is there any official tutorial/document for merlin ?

**Comment by ronanki** [comment]
For installation, check [INSTALL.md](https://github.com/CSTR-Edinburgh/merlin/blob/master/INSTALL.md) or go through this [blog post](https://cstr-edinburgh.github.io/install-merlin/) 

For example demos, you can try [slt arctic voice](https://github.com/CSTR-Edinburgh/merlin/tree/master/egs/slt_arctic/s1). There's a [blog post](http://jrmeyer.github.io/merlin/2017/02/14/Installing-Merlin.html) to help run the demo. 

1. Not much of a documentation -- check [wiki](https://github.com/CSTR-Edinburgh/merlin/wiki) here on Github. 
2. You can find under-construction documentation [here](http://104.131.174.95/Merlin/dnn_tts/doc/build/html/)
3. Some [tutorials](http://www.speech.zone/exercises/build-your-own-dnn-voice/) on theory

**Comment by Jackiexiao** [comment]
Thx!
