### ISSUE TITLE
Couldn't find any package by glob 'glibc-devel.i686'

### ISSUE THREAD

**Issue by Jackiexiao** [CSTR-Edinburgh/merlin#161]
according to [INSTALL.md](https://github.com/CSTR-Edinburgh/merlin/blob/master/INSTALL.md)
~~`sudo pip install glibc-devel.i686`~~
`sudo apt-get install glibc-devel.i686`

error:
~~`No matching distribution found for glibc-devel.i686`~~
`E: Couldn't find any package by glob 'glibc-devel.i686'`

I made a mistake...

**Comment by ronanki** [comment]
Those linux instructions were provided by other users -- just proceed to run the demo and see if it's working, after installing required python libraries.

**Comment by m-toman** [comment]
This should be apt-get, not pip.
But I think I accidentally added this to ubuntu, I think this was needed for AWS RHEL (but not 100% sure which machine it was that needed this package).

**Comment by chazo1994** [comment]
I download source package glibc-devel.i686, extract it and pack again with arm64 architecture, and then i install it with new package. may be this solution will help you :)

**Comment by Jackiexiao** [comment]
thx
