### ISSUE TITLE
Extracting MGC parameter

### ISSUE THREAD

**Issue by Ali20177** [CSTR-Edinburgh/merlin#166]
Dear all,

Regarding to the WORLD vocoder, does the Merlin toolkit use to extract the MGC parameter by using "CheapTrick" spectral estimation algorithm?

Best regards,

**Comment by bajibabu** [comment]
yes, https://github.com/CSTR-Edinburgh/merlin/blob/master/tools/WORLD/test/analysis.cpp#L139

**Comment by Ali20177** [comment]
Thank you very much ...
