### ISSUE TITLE
Error in phone_align during "normalizing label files for merlin" part

### ISSUE THREAD

**Issue by reiinakano** [CSTR-Edinburgh/merlin#172]
I'm trying to create phone alignment labels for my own wav files. I've finally gotten things to work but now I'm facing an error during this command of the `run_aligner` script

```
python ${frontend}/utils/normalize_lab_for_merlin.py \
                        full-context-labels/full \
                        label_phone_align \
                        phone_align \
file_id_list.scp 
```

Here is the error:
```
Error: zero duration for this phone
Traceback (most recent call last):
  File "/home/ubuntu/pynb/TFplay/merlin/misc/scripts/frontend/utils/normalize_lab_for_merlin.py", line 131, in <module>
    normalize_label_files(in_lab_file, out_lab_file, label_style, write_time_stamps)
  File "/home/ubuntu/pynb/TFplay/merlin/misc/scripts/frontend/utils/normalize_lab_for_merlin.py", line 87, in normalize_label_files
    raise
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType
```

**Comment by ronanki** [comment]
The duration for the phone is so short that when normalised, the start duration and end duration becomes same and hence zero duration. Try to skip if it is one of a file.

**Comment by reiinakano** [comment]
I decided to go with `state_align` instead since that worked without errors. Is that fine? Is phone_align somehow better?

**Comment by ronanki** [comment]
No, state_align is slightly better than phone_align.

**Comment by reiinakano** [comment]
Oh good. Thanks!
