### ISSUE TITLE
Please help to solve the promblems for outputing the HTS style lebel

### ISSUE THREAD

**Issue by TaoTaoFu** [CSTR-Edinburgh/merlin#175]
I have been  finished  the Merlin demo , now I want to make my own wav , but I don't konw how make the HTS style lebels using the documents like 

   ( 1589 "Once upon a time" )   and  1589.wav

now, I have installed the Festival , I hope someone can help me solve the problem . 
Thanks in advance !

**Comment by syltruong** [comment]
Hi,
the related scripts are in `merlin/misc/scripts/alignment`. From there you can choose to state_align or phone_align.

Please note that to state_align, you also need HTK installed.
Cheers

**Comment by TaoTaoFu** [comment]
Thanks a lot !

I will try it .
