### ISSUE TITLE
regex

### ISSUE THREAD

**Issue by dreamk73** [CSTR-Edinburgh/merlin#176]
After a recent git pull, in merlin/src/keras_lib/data_utils.py I had to comment out 
import regex as re
and include
import re
to get the code to work.  I am using python 2.7.5.

**Comment by ronanki** [comment]
I am also working with same version. I didn't have any problems.

**Comment by ecooper7** [comment]
I got an error too about module regex being missing, but I did 'pip install
regex' and it worked fine.

**Comment by ronanki** [comment]
I wonder why I've included that import when the code itself has nothing to do with regular expressions. I removed that line now and added a [requirements](https://github.com/CSTR-Edinburgh/merlin/blob/master/requirements.txt) file to the repo. 

With this, the installation should be easy now:
pip install -r requirements.txt
