### ISSUE TITLE
About  mgc / lf0 / bap :  How to generate these files  to train Acoustic Module ?

### ISSUE THREAD

**Issue by TaoTaoFu** [CSTR-Edinburgh/merlin#177]
Hi, guys.
I have finished the Merlin Demo and generated HTS style labels, now I want to generate the files for training Acoustic Module. Please give me some instructions for generating these files. Thanks in advance!

**Comment by Lukelluke** [comment]
> Hi, guys.
> I have finished the Merlin Demo and generated HTS style labels, now I want to generate the files for training Acoustic Module. Please give me some instructions for generating these files. Thanks in advance!

Hi, could u please teach us freshman how to generate these files quickly, hoping ur answer, THX!
