### ISSUE TITLE
train new voice

### ISSUE THREAD

**Issue by ikhfa** [CSTR-Edinburgh/merlin#18]
Hi. Is there any step-by-step guide to train new voice/language? Thanks

**Comment by gillesdegottex** [comment]
Basically no.
For new American or English voice, it's not very complicated.
You need to replace the files in the data directory.
If you ran the demo voice, you will find the data in: egs/slt_arctic/s1/experiments/slt_arctic_demo/{acoustic,duration}_model/data
For the acoustic model, you only need to change lf0, mgc and bap.
And adapt the file_id_list_demo.scp with the new list of filenames.

For new languages, you will need at least a different questions set (configuration question_file_name) (stored in misc/questions/). Though, personaly I'm working only with English up to now, so I can't really help on this.

**Comment by ikhfa** [comment]
I see. I have developed a voice in another language using HTS. Could I easily convert it to Merlin? Is it compatible?

**Comment by gillesdegottex** [comment]
Yes, they are quite compatible. E.g. I build the state-level alignement from HTS too.

For the acoustic data, just drop your features in the proper directories.
Careful about the lf0 that need to be encoded in log(Hz) with -1e+10 values in unvoiced regions.
And fill the filenames (without extension) in the file_id_list_demo.scp

For the questions set ... well I've never did this, but I suppose you can use the hed file of your HTS decision tree. Though, usually, this hed is greatly reduced for DNN because we want to avoid using questions that are useless (whereas the decision tree discard the useless questions automatically).
I can't really help on how to build such a reduced questions set (extract the first ~600 questions that are used at the most top of the tree?)

**Comment by zhizhengwu** [comment]
It is easy to work with HTS. Do the state-level alignment and provide your question set. I pruned the question set manually... For numerical values, you could use 'CQS' and use regular expression to reduce the number of questions. HTS usually lists all the possible questions, but most of them are not used. You can check the question set used in the example.

Simon also has a tutorial about how to build a new voice: http://www.speech.zone/exercises/build-your-own-dnn-voice/

**Comment by tuanad121** [comment]
Are those .lf0 and .mgc files in data extracted by SPTK? Are they similar to those in HTS?

**Comment by ronanki** [comment]
The scripts in below url are used for extraction of the vocoder parameters (.lf0 and .mgc)

https://github.com/CSTR-Edinburgh/merlin/tree/master/misc/scripts/vocoder/world

**Comment by tuanad121** [comment]
I'm a little bit confused by the hed file of Merlin, e.g., given a string in full context label for 5 phonemes  ah^v-dh+ax=d@, so for "right right phoneme", the question should be " *=d@* " instead of " *=d:* " as in Merlin .hed file. Is it a convention? 
Thank you very much.

**Comment by tuanad121** [comment]
Hi, I have successfully trained Vietnamese synthesized voice using Merlin. I used 450 trainning sentences, 30 sentences for validation and 30 for testing. I described 6 tones in Vietnamese as numerical values from 1 to 6. Here are some [samples]([url](https://drive.google.com/open?id=0ByWazFhIkXGaQi1BeVFEeEV3RE0)).  There are some cases, the tonal information is not precise. I wonder if it's because my data is too small.

**Comment by simonkingedinburgh** [comment]
Adding tutorials & recipes to help people use their own data in English, or work in another language, are all on our roadmap.

**Comment by zhizhengwu** [comment]
@tuanad121 I heard other people working on tonal language also meet this problem when using neural network. It may not related to the size of data. I have not found any paper mentioning this yet.

**Comment by tuanad121** [comment]
With manually corrected phone aligment files, HSMMALIGN with -f option will output time labels for each state. I used models trained in HTS demo for HSMMALIGN :D

**Comment by dreamk73** [comment]
Great info, thanks! Though my generated speech sounded surprisingly good given that it used automatically aligned phone labels that came from Festival and were sometimes not exactly what was being said.

**Comment by ronanki** [comment]
step-by-step guide to train new voice:
https://github.com/CSTR-Edinburgh/merlin/wiki/step-by-step-guide-to-train-new-voice

**Comment by dreamk73** [comment]
The instructions to train a new voice are not quite clear. Do you still need to use the slt_data if you want to align new wave files? 

Also, when I try to follow the steps in the build_new_voice directory when I run 02_prepare_data.sh it tells me to run 01_setup.sh even when I just did that.

**Comment by ronanki** [comment]
@dreamk73 The instructions for alignment are shown with slt data, but you can simply replace with your own data. Use your audio files and provide either txt directory or utts.data as in festival sceheme format. 

The bug you pointed out is fixed now, please pull the latest commit -- however, the steps for build_your_own_voice are not complete yet. 02_prepare_data.sh prints only the instructions on how to setup and prepare data. Use misc/scripts to prepare data and then the rest works without any problem.

**Comment by dreamk73** [comment]
I was able to follow the instructions for training phone-level alignment data. The resulting generated wavefiles are not as good as the state-level alignment trained data I used before. Especially plosives and fricatives seems to lack precision, making them sound sloppily articulated. Is this just a side-effect of not dividing the phonemes into states? Are you having similar problems when using phoneme alignments?

**Comment by ronanki** [comment]
If you have state-alignments, you are clearly differentiating the events such as bursts in plosives, friction of breath in fricatives. 

Where as phone-alignments don't have such hard boundaries, and therefore it has to learn automatically from the data and model. 

Using sequence models such as RNNs/LSTMs may reduce the performance gap between models trained with state alignments and phone alignments.

**Comment by dreamk73** [comment]
That is what I figured, thanks for the explanation!

I saw it mentioned somewhere that you can use HSMMAlign to get state-level alignments when you already have phone-level labels. Is there a link somewhere where I can see how to use it properly? Do I still need to train HMM models first using my phone set?

**Comment by ronanki** [comment]
You can use the scripts provided in the below link to get state-alignments:
https://github.com/CSTR-Edinburgh/merlin/tree/master/misc/scripts/alignment/state_align

**Comment by dreamk73** [comment]
But does that script allow for using your own aligned phoneme label files? I have my own phone set for English and pronunciation lexicon that is not the same as cmudict.

**Comment by ronanki** [comment]
The script works for any phone-set and label files corresponding to any language as long as they are in full-contextual HTS format.

In principle, run_aligner (https://github.com/CSTR-Edinburgh/merlin/blob/master/misc/scripts/alignment/state_align/run_aligner.sh) script follows a two-step procedure. 

You can do the first step and later replace them with your own files in the same format it specifies (without any start and end durations). And then, you can run the second step, without any further changes. Please configure the paths to tools, before you run the script.  

The alignment starts from scratch and provides state-level boundaries, with your own phone set and lexicon.

**Comment by dreamk73** [comment]
Thanks, I will try it out.

**Comment by syltruong** [comment]
@ronanki Can the step-by-step guide to train a new voice in
[https://github.com/CSTR-Edinburgh/merlin/wiki/step-by-step-guide-to-train-new-voice](url)
be used to synthesize a language other than English ?

**Comment by alokprasad** [comment]
> Hi, I have successfully trained Vietnamese synthesized voice using Merlin. I used 450 trainning sentences, 30 sentences for validation and 30 for testing. I described 6 tones in Vietnamese as numerical values from 1 to 6. Here are some samples: https://drive.google.com/open?id=0ByWazFhIkXGaQi1BeVFEeEV3RE0. There are some cases, the tonal information is not precise. I wonder if it's because my data is too small.

@tuanad121 Do you have blog or writeup how train with Vietnamese or any new language. Sound sample are really nice even with less data.Also How much is typical inference time on CPU for say about 10sec of audio.?
