### ISSUE TITLE
./run_state_aligner.sh skipping files?

### ISSUE THREAD

**Issue by reiinakano** [CSTR-Edinburgh/merlin#180]
I've figured out the problem of different synthesis files from #179, and it's because of state alignment skipping files.

Is there any reason that `run_state_aligner.sh`, particularly during `forced_alignment.py` would skip files? My .wav files are complete, my utts.data text file is fine. The reason I know this skipping happens during `forced_alignment.py` is because after `prepare_labels_from_txt.sh`, I look at the output label folders and they are all complete e.g. `label_no_align` is complete.

But after `forced_alignment.py`, the contents of the `label_state_align` folder is, for some inexplicable reason, missing one .lab file.

I'm trying to debug this, so if you could have some ideas on situations where `forced_alignment.py` would just skip files, it would be helpful. Thank you.

**Comment by ronanki** [comment]
Sometimes, the alignment breaks if it is unable to reach the final state while aligning the audio file with text -- this may happen if the audio doesn't have silence in the ending or if the audio is not clean and consistent with the text. For this reason, there can be one or two files missing in `label_state_align` -- which is completely fine. Just proceed to voice building, make sure you change the train, valid, and test numbers accordingly.
