### ISSUE TITLE
Generated voices missing 1st word pronounciation

### ISSUE THREAD

**Issue by sinlam** [CSTR-Edinburgh/merlin#193]
[test.zip](https://github.com/CSTR-Edinburgh/merlin/files/1152076/test.zip)
I am very new to speech synthesis and last week I started to play with Merlin. Thank you and it is a great tool for me to experiment speech synthesis. I attached two generated voice files with the text. You can hear that the 1st word is missing during synthesis. I use the example script from 'build_your_own_voice'. 
It is trained using the following (everything is default from the example):
[TANH TANH TANH TANH TANH TANH] [1024 1024 1024 1024 1024 1024]

What should I do to get the correct speech synthesis for 1st word? Hope to hear from you guys. Thank you!

**Comment by candlewill** [comment]
I have the same problem. Do you apply the HTS patch to HTK?

**Comment by sinlam** [comment]
Thank you Candlewill! 
Previously I installed HTK 3.5 beta 2 version without the patch and I have this 1st word missing problem. 

Now I follow the instruction from https://gist.github.com/kastnerkyle/a7614579c7a66d01a483cc9801b21db4
and install HTK 3.4.1 and apply the HTS patch from http://hts.sp.nitech.ac.jp/archives/2.2/HTS-2.2_for_HTK-3.4.1.tar.bz2. Recompile HTK 3.4.1. 

I just rerun the last step to generate the voice files and 1st word missing problem is gone. 
Hope I am using the right patch file and the right version of HTK. Thank you!

**Comment by sinlam** [comment]
Sorry, I reopen the issue as I found out that the same problem still exists. In some cases they are slightly better but most of the time it didn't solve the problem. I did fresh installed of Merlin in two different machines today with the related patch and I found out the same problem still happened. Please suggest anything I can do to fine tune the system. Thank you!

**Comment by ronanki** [comment]
Can you please send few label files from `gen_lab` corresponding to those cases?

**Comment by sinlam** [comment]
[genlab.zip](https://github.com/CSTR-Edinburgh/merlin/files/1157641/genlab.zip)
Hi Ronanki,
  Attached are the gen_lab files from those cases. I should be clearer describing the problem is that only the 1st phone of the 1st word is missing in all these generated voice files. Let me know if you need any further info! Thank you.

**Comment by sinlam** [comment]
I found out if I change the test_synth config file variable 'enforce_silence' to False, then the generated voice files are perfect. I am not sure if this change has any other consequences. Thanks for all the suggestions!
