### ISSUE TITLE
Slt_arcric memory problem

### ISSUE THREAD

**Issue by khusainovaidar** [CSTR-Edinburgh/merlin#196]
I’m trying to build duration model for full arctic example, but facing ‘out of memory’ problem (output: Kill process 2611 python score 990 or sacrifice child. Submit.sh line 35).
I have 16 GB RAM, 1070 GPU and also tried extending swap file up to 100 GB, but maximum is epoch 10 of the training process.
Can someone suggest what I’m doing wrong?

**Comment by candlewill** [comment]
@khusainovaidar I think it is not your mistake. I met the same error with a server of 128GB memory size. My solution is to change to the `Keras` backend, rather than the default `theano`. And this fixed my problem.

**Comment by khusainovaidar** [comment]
@candlewill Thanks, that's worked!

**Comment by ronanki** [comment]
I don't see why default theano didn't work in the first place -- can you guys please elaborate more on the error? It should work either on CPU/GPU with low memory as well.

**Comment by khusainovaidar** [comment]
I’m very new to Merlin, so don’t really know what can be helpful.
I haven’t made any changes in config files or anywhere else, just executed run_full_voice.sh step by step. And while training duration model it started to use RAM more and more epoch by epoch. 20 GB memory was enough for 2 epochs, 120 - for 10, I haven’t done experiments further.
Last Records in log file are not very informative:
INFO Main: Training DNN
...
INFO Main.train_DNN: epoch 10, validation error, etc.

**Comment by bajibabu** [comment]
Did you install new gpuarray as backend on your system? If yes, then disable that and run again. I heard some memory errors with new gpuarray backend.

**Comment by chazo1994** [comment]
do anyone resolved this problem ??? I got same issue.
