### ISSUE TITLE
STRAIGHT call: -cornf

### ISSUE THREAD

**Issue by gillesdegottex** [CSTR-Edinburgh/merlin#2]
Well, there are plenty of astrological arguments to provide to straight synthesizer, but I think there is a mistake on the -cornf argument when calling it:
https://github.com/CSTR-Edinburgh/merlin/blob/master/utils/generate.py#L214

The current value is 400, whereas the doc reads:
-cornf cornf[3500.0]            : corner frequency for random phase
so I suppose it should be more around 4000.

Also, this very low value generates hoarsness in CMU Arctic SLT voice.

EDIT: Keeping the default value (3500) might be a safe solution.

**Comment by ljuvela** [comment]
We also ran into this issue, and I think the old default values work better.

Here's some samples comparing the two settings (otherwise same TTS system) https://users.aalto.fi/~ljuvela/straight_demo/

**Comment by ronanki** [comment]
Comparing the two settings, I feel the same -- old default values work better and the current [copy-synthesis](https://github.com/CSTR-Edinburgh/merlin/blob/master/misc/scripts/vocoder/straight/extract_features_for_merlin.sh) reflects the same. 

May I know which version you used for bap extraction? Did you use cepstrum to extract bap or raw audio?

**Comment by ronanki** [comment]
Thank you for bringing this issue. Fixed it now.

**Comment by ljuvela** [comment]
We used a straight_bndap that takes in raw audio and F0, and outputs BAP in bark-bands. It's just AP-band energies (not warped cepstrum), but I don't think there's a major difference.

Specifically, the code is Junichi's implementation from around 2010 (mod to Banno's 1996 original), so it's probably also available at CSTR.
