### ISSUE TITLE
Incompatible binary files

### ISSUE THREAD

**Issue by erintaylor** [CSTR-Edinburgh/merlin#21]
I am excited to give merlin a try. I am working on getting started by building the slt_arctic voice example. In the acoustic model building phase it calls on binaries in both SPTK3 and WORLD which are provided. These aren't compatible with my current setup. I was able to rebuild SPTK3 and get it running, but I'm unsure of how to do this for synth and analysis in WORLD/build. They appear to have been added separately from the original World project. Any advice you can give would be great. Thanks!

**Comment by gillesdegottex** [comment]
For SPTK, it would be worth replacing the current binaries with a script that download the toolbox and compile it.

**Comment by erintaylor** [comment]
I apologize, I should have looked at that before making the issue. That solved my problem. Thank you for the quick reply.

**Comment by gillesdegottex** [comment]
04869e169269030b4ea3a8993d9e5341fbf73cdb
Hey,

I don't think binary files should be in the repo, they are very likely to be either incompatible or sub-optimized for the host architecture.

There are a two solutions for this that both request to run a "setup.sh" script before configuring/running Merlin. Then:
A) Download SPTK, compile it automatically (as suggested by @seblemaguer) and then install it in "tools/bin/".
B) Fork SPTK from Sourceforge to CSTR-Edinburgh/SPTK and add the fork as a submodule of Merlin in "tools". The SPTK sources will then be downloaded automatically with "git submodule update". And the auto compilation can run as in (A).
(I would strongly suggest to go for (B))

Note also that the setup.sh script could set the working directory path. It could also check the availability of theano, verify some versions, run very quick and simple tests, etc. many good stuffs that will avoid bad surprises to the user later on.

**Comment by ronanki** [comment]
I agree with this. But, when the setup.sh is ready -- we can remove the binaries. Also, I am currently working on WORLD bap -- to see whether the current version is better than previous one in terms of synthesis quality. Once, these issues are fixed, will remove the binaries.

**Comment by ronanki** [comment]
All binaries are removed now and the scripts are provided for automatic compilation of tools.
