### ISSUE TITLE
How can I transfer raw audio to lf0, mgcc and bap

### ISSUE THREAD

**Issue by willian56** [CSTR-Edinburgh/merlin#210]
I want to use merlin for chinese training, but I am confused about using World. How can I transfer raw audio to lf0, mgcc and bap? Could you show me some document or blog for learning, honestly appreciate.

**Comment by simonkingedinburgh** [comment]
willian56 wrote:
>
> I want to use merlin for chinese training, but I am confused about 
> using World. How can I transfer raw audio to lf0, mgcc and bap? Could 
> you show me some document or blog for learning, honestly appreciate.
>
see the example in

merlin/egs/build_your_own_voice/s1/03_prepare_acoustic_features.sh




-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by willian56** [comment]
Thanks for your replay, I will have a try.
