### ISSUE TITLE
HTK website is down, so compile_htk.sh doesn't work

### ISSUE THREAD

**Issue by qiusidong** [CSTR-Edinburgh/merlin#212]
The error line is like this:

> --2017-08-23 11:18:47--  http://htk.eng.cam.ac.uk/ftp/software/HTK-3.4.1.tar.gz
> Resolving htk.eng.cam.ac.uk... 129.169.10.146
> Connecting to htk.eng.cam.ac.uk|129.169.10.146|:80... connected.
> HTTP request sent, awaiting response... 503 Service Temporarily Unavailable
> 2017-08-23 11:19:13 ERROR 503: Service Temporarily Unavailable.
> 
> --2017-08-23 11:19:13--  http://htk.eng.cam.ac.uk/ftp/software/hdecode/HDecode-3.4.1.tar.gz
> Resolving htk.eng.cam.ac.uk... 129.169.10.146
> Connecting to htk.eng.cam.ac.uk|129.169.10.146|:80... connected.
> HTTP request sent, awaiting response... 503 Service Temporarily Unavailable
> 2017-08-23 11:19:14 ERROR 503: Service Temporarily Unavailable.

I don't know if it's a temporary issue or a long-time issue.

**Comment by seblemaguer** [comment]
it seems to be online on my side so it is back.

**Comment by qiusidong** [comment]
Yes!
