### ISSUE TITLE
bottleneck features?

### ISSUE THREAD

**Issue by madhavivr** [CSTR-Edinburgh/merlin#216]
HI!

I'm also looking into extracting bottleneck features, but I get the following error - 
predicted_parameter = dnn_model.generate_top_hidden_layer(test_set_x=test_set_x). 
AttributeError: 'DeepRecurrentNetwork' object has no attribute 'generate_top_hidden_layer'

Could you please let me know what I should do to fix this

**Comment by ronanki** [comment]
The bottleneck features function was never tested after making changes in the main script. It's now fixed and working with the latest commit. 

Bottleneck layer is automatically chosen based on minimum number of nodes for a given architecture. 

e.g., hiddlen_layer_size = [1024, 1024, 1024, 32, 1024, 1024], the layer with least number of nodes is selected i.e., layer 4. If there are more than one layer with least number of nodes, the one from the bottom is selected.

**Comment by madhavivr** [comment]
Wonderful, Thanks. I'll try it out.

**Comment by madhavivr** [comment]
HI! I think there is still the issue with 
 dnn_model.generate_hidden_layer(test_set_x, bottleneck_index) - The object "generate_hidden_layer" doesn't seem to exist in dnn_rnn.py

**Comment by ronanki** [comment]
The function is in [models/deep_rnn.py](https://github.com/CSTR-Edinburgh/merlin/blob/master/src/models/deep_rnn.py#L229-L247). And use process `GENBNFEA` instead of `DNNGEN` to generate bottleneck features.

**Comment by madhavivr** [comment]
Ofcourse! Sorry I forgot to download that. 
Yes, I did set GENBNFEA to true.
Thanks.
