### ISSUE TITLE
Create State Align Labels for Synthesis

### ISSUE THREAD

**Issue by rhajit1001** [CSTR-Edinburgh/merlin#217]
Hello there,
I am creating a TTS on a language which is not supported by festival.

I've trained a model based on state-aligned labels. I created the labels by myself, then aligned them using "run_state_aligner.sh". The training went well, but when I've reached the synthesis phase, there was a problem with my non-aligned labels, which I've tried to synthesis.

Is there any way to use non-aligned labels as an input for the synthesis? It worked well on my phone-align labels, but it throws the following error with the state-align labels.

```
state_index = int(state_index) - 1
ValueError: invalid literal for int() with base 10: '-'
```

**Comment by simonkingedinburgh** [comment]
rhajit1001 wrote:
>
> Is there any way to use non-aligned labels as an input for the 
> synthesis? It worked well on my phone-align labels, but it throws the 
> following error with the state-align labels.
>
You need to provide durations for the labels in the new sentences you 
are synthesising. To do that, you need to train a duration model. This 
should either be a phone-duration or a state-duration model, depending 
on how you have configured your acoustic model.


-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by rhajit1001** [comment]
I've trained a duration model, the problem is that I need to create state aligned labels for the synthesis.

Unfortunately, I have only labels that look like phone-aligned labels, but without the timings. Is there any way to use them on the models that I've trained?

The error I mentioned above is thrown on both parts of the synthesis.

**Comment by seblemaguer** [comment]
If I understand correctly you don't have state alignment but only phone alignment. To create state alignment, you can use something like HTK/HTS. You can also use your own tool but therefore you have to follow the HTS label format. 

Another solution is to only use phone aligment labels. According to  merlin/egs/build_your_own_voice/s1/01_setup.sh you can switch that in the conf/$global_config_file. Either change it manually, either you modify the 01_setup.sh script and then rerun it again. To do so you have to change this line
```sh
echo "Labels=state_align" >> $global_config_file
```

to 

```sh
echo "Labels=phone_align" >> $global_config_file
```

don't forget to rerun the scripts after

**Comment by chazo1994** [comment]
@rhajit1001 actually Merlin do not need time stamp in lab file for synthesis phase, it will be removed by merlin. But to match with input structure, time stamp need to be inserted to lab file. So the solution is insert a simple time stamp for all of line in labs file. it does not need to align with lab, just add a simple time stamp like "0 50000" to all of line in all of lab file.

**Comment by ronanki** [comment]
@chazo1994 You are right. 

We'll soon provide support for full-contextual labels without time-stamps at synthesis time in order to get rid of this confusion. In which case:

1. The Input to duration model is full-contextual labels without time-stamps and outputs labels with time-stamps (by adding predicted durations).
2. The acoustic model always takes labels with time-stamps in order to synthesize speech.

**Comment by chazo1994** [comment]
@ronanki  thank you, may be my version isn't updated. :)

**Comment by rhajit1001** [comment]
@chazo1994 You were right, thanks!
