### ISSUE TITLE
Junk at end of HTK transcription

### ISSUE THREAD

**Issue by rhajit1001** [CSTR-Edinburgh/merlin#218]
I'm using run_state_aligner.sh in order to align my non aligned labels. It had worked fine on datasets I have, but this time it threw this error:

```
ERROR [+6550] LoadHTKLabels: Junk at end of HTK transcription
```
I have no idea how could I fix it, or what does it mean. could anyone please help me please?

**Comment by simonkingedinburgh** [comment]
rhajit1001 wrote:
> |ERROR [+6550] LoadHTKLabels: Junk at end of HTK transcription|
probably a blank line in an HTK master label file (MLF) - just Google 
for "HTK +6550" - lots of people publish online lists of the most likely 
underlying cause for HTK errors

Simon


The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by rhajit1001** [comment]
Thank you!
