### ISSUE TITLE
LSTM generation?

### ISSUE THREAD

**Issue by madhavivr** [CSTR-Edinburgh/merlin#219]
HI! In run_merlin.py there is a dnn_generation_lstm function that is never called even when the layers are defined with an LSTM as in ['TANH','TANH','SIGMOID','BSLSTM']. Is this a bug? I'm wondering if the DNN test result is accurate if the layers are defined with LSTM, but the generation doesn't use LSTMs?

**Comment by ronanki** [comment]
I just deleted that function in the latest code. It was never used. The default function `dnn_generation` works for both feed-forward and LSTM-RNN layers.

**Comment by madhavivr** [comment]
okay, thanks.
