### ISSUE TITLE
How to implement the hybrid unit speech synthesis using merlin ?

### ISSUE THREAD

**Issue by huguanglong** [CSTR-Edinburgh/merlin#226]
Hi, @all,
  According to the survey, it is found that the hybrid unit speech synthesis is now the best system ( more natural than parametric speech synthesis like merlin or hts ) in both blizzard 2017 ( The top1 is iFlyteck's hybrid speech syntheis system, and iDST  ) and commercial systems ( like siri [https://machinelearning.apple.com/2017/08/06/siri-voices.html](url) ).  And I found a subfolder in merlin/misc/scripts/hybrid_voice, but there is no instruction about how to use it.  
1) Does anybody know how to use the hybrid_voice scripts for hybrid speech synthesis ? If it is incomplete, how to implement it fully ? 
2) It seems that the MultiSyn in Festival can do this ( should replace the target and join cost using hmm or dnn according to the literature ), is there any successful guidance ?

**Comment by ronanki** [comment]
The hybrid unit-selection synthesis requires two models:
1. Unit selection voice -- can be built using Festival Multisyn
2. Parametric voice -- can be built using Merlin

The scripts are being prepared for a reproducible demo. 

You can follow [this blog post](https://cstr-edinburgh.github.io/Multisyn_unit_selection/) to get an overview of unit-selection voice with Festival Multisyn. The next post will show how to use Merlin to perform hybrid speech synthesis. We'll soon provide all the necessary scripts and a demo with SLT voice.

**Comment by huguanglong** [comment]
@ronanki Thank you for your reply. It is exited to hear that the next post will show the pipeline for hybrid speech synthesis. I will be familiar with the Festival MultiSyn framework according to the post you provided. Looking forward to the next post.

**Comment by lomizandtyd** [comment]
@ronanki , Thanks for the blog post. 
I get stuck in the python wrapper of speech tool. Please give me a hand. 

While I import the python wrapper, an error occured.

```
ImportError: ./_EST_Wave.so: undefined symbol: _ZN8EST_Wave19default_sample_rateE
```

**Comment by huguanglong** [comment]
@ronanki Hi, I'm trying to do the experiment follow [the post](https://cstr-edinburgh.github.io/Multisyn_unit_selection/) you provided. Now I have completed the 15 steps and entered the last synthesis step, but it indicate there is no cstr_edi_awb_multisyn.scm in the festival/lib/voices/english/cstr_edi_awb_multisyn/festvox/ folder. In the step of "Build unit-selection model", it just create an empty festvox folder: "mkdir $FESTDIR/lib/voices/english/cstr_edi_awb_multisyn/awb/festvox", but no scm files . How to genetate these scm files in festvox or copy from somewhere else ? Looking forward to your guidance, thanks.

**Comment by chenht2010** [comment]
@lomizandtyd I meet this problem on Ubuntu 17.10 too, but I switch to centos 7, problem solved. may be this problem related to gcc? You can read this link https://bugzilla.redhat.com/show_bug.cgi?id=1336981

**Comment by chenht2010** [comment]
@huguanglong You can download the multisyn voice, for example "festvox_cstr_us_awb_arctic_multisyn-1.0.tar.gz",  provided from this link http://www.festvox.org/packed/festival/1.96/ , and extract the scm in festvox folder, and change the name to yours. The problem should be solved!

**Comment by huguanglong** [comment]
@chenht2010 Thank you, it does work. Are you working on Chinese speech synthesis ?

**Comment by chenht2010** [comment]
@huguanglong Yes.

**Comment by auzxb** [comment]
Hi, when I run the following script, I met an error.
script: $MULTISYN_BUILD/bin/add_noise wav utts.data  
error: ImportError: No module named _EST_Wave

**Comment by auzxb** [comment]
Hi, @huguanglong @chenht2010  when I run the following script, I met an error. Can you help me?
script: $MULTISYN_BUILD/bin/add_noise wav utts.data
error: ImportError: No module named _EST_Wave

**Comment by auzxb** [comment]
Hi,all! @huguanglong @ronanki @chenht2010 
Do you meet the the following problem when do the experiment follow the blog?
```
 WARNING [-8232]  ExpandWordNet: Pronunciation 1 of sp is 'tee' word in HVite
 WARNING [-8232]  ExpandWordNet: Pronunciation 1 of sp is 'tee' word in HVite
 WARNING [-8232]  ExpandWordNet: Pronunciation 1 of sp is 'tee' word in HVite
 WARNING [-8232]  ExpandWordNet: Pronunciation 1 of sp is 'tee' word in HVite
 WARNING [-8232]  ExpandWordNet: Pronunciation 1 of sp is 'tee' word in HVite
 WARNING [-8232]  ExpandWordNet: Pronunciation 1 of sp is 'tee' word in HVite
  ERROR [+8522]  LatFromPaths: Align have dur<=0 
 FATAL ERROR - Terminating program HVite
second alignment failed, Aborted!

```

**Comment by simonkingedinburgh** [comment]
auzxb wrote:
> |  WARNING [-8232]  ExpandWordNet: Pronunciation 1 of sp is 'tee' word in HVite|
It's just a warning during forced alignment, not an error. This is 
normal and can be ignored.

HTK is noting that the sp (short pause) model has a skip transition that 
allows it to be traversed without emitting any observations.

Simon



The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by caicaibin** [comment]
HVite -l \* -C config -a  -m -i aligned.2.mlf -I aligned.0.mlf -T 1  -H hmm${i}/MMF  -S train.scp -y lab dict2 phone_list 
14020 REALIGNMENT (ITERATION 6)
14021  output file is aligned.2.mlf
14022 Read 60 physical / 60 logical HMMs
14023 Label file will be used to align each file
14024 Aligning File: ../mfcc/arctic_a0001.mfcc
14025 Created lattice with 50 nodes / 49 arcs from label file
14026  WARNING [-8232]  ExpandWordNet: Pronunciation 1 of sp is 'tee' word in HVite
14027  WARNING [-8232]  ExpandWordNet: Pronunciation 1 of sp is 'tee' word in HVite
14028  WARNING [-8232]  ExpandWordNet: Pronunciation 1 of sp is 'tee' word in HVite
14029  WARNING [-8232]  ExpandWordNet: Pronunciation 1 of sp is 'tee' word in HVite
14030  WARNING [-8232]  ExpandWordNet: Pronunciation 1 of sp is 'tee' word in HVite
14031  WARNING [-8232]  ExpandWordNet: Pronunciation 1 of sp is 'tee' word in HVite
14032 second alignment failed, Aborted!

**Comment by ddavout** [comment]
for the FAIL part, 

> 14032 second alignment failed, Aborted!

I've put some links in
https://cstr-edinburgh.github.io/Multisyn_unit_selection/
