### ISSUE TITLE
run_demo problem, no keras module, no tensorflow module??

### ISSUE THREAD

**Issue by dza6549** [CSTR-Edinburgh/merlin#230]
Hi, trying to run run_demo.sh but have:

No module named keras error. And then I pip install keras and then
No module named tensorflow error.  

I don't understand. Theano is installed but then run_demo wants Keras, then it wants Tensorflow?
Why does Merlin want Keras and Tensorflow? I understood this was a Theano based project. Very confused newbie.

Everything is good per Josh Meyer's tutorial up to run_demo.sh

I am running on CPU
Virtualbox 5.1.26
Lubuntu 17.04
on Mac Sierra 10.12.5

Thank you for any advice to move ahead

**Comment by ronanki** [comment]
Keras by default uses tensorflow and hence the requirement. 

You can do either of these two things:
1. Comment [line no. 81 in run_merlin.py](https://github.com/CSTR-Edinburgh/merlin/blob/master/src/run_merlin.py#L81)
2. or you can change keras backend to theano in `~/.keras/keras.json`

**Comment by dza6549** [comment]
Thanks ronanki for your most rapid reply.
I shall assimilate this information and attempt another rebuild.
Cheers and thanks!

**Comment by dza6549** [comment]
I pip installedTensorflow and got it running.
Thanks
