### ISSUE TITLE
Has anyone ever tried using WaveNet or Griffin-lim instead of World vocoder ?

### ISSUE THREAD

**Issue by huguanglong** [CSTR-Edinburgh/merlin#238]
In Blizzard 2017, the [USTC](http://festvox.org/blizzard/bc2017/USTC-NELSLIP_Blizzard2017.pdf) has submitted a parametric speech synthesis system using WaveNet as vocoder and got a very good result (2nd place, and supass all the other hybrid unit selection systems except iFlytech's. ) It seems that the WaveNet vocoder played a very big role. Has anyone ever tried it or Griffin-lim in merlin?

**Comment by dreamk73** [comment]
I haven't tried it yet, but it would be interesting. I did hear at the
Blizzard challenge that it took 20s to generate 1s of speech. So for
research purposes it may be a good tool but it is not feasible yet for
commercial applications.

**Comment by ljuvela** [comment]
Wow they really threw everything at it, even the GAN MGC post-filter 😄  (which is quite a useful architecture, BTW) 

There was a WaveNet hands-on at SPCC http://spcc.csd.uoc.gr/program.html
Vassilis Tsiaras' implementation is actually quite good (clean code and relatively fast). The code was available for the course participants, and he might make it publicly available if asked nicely.

**Comment by simonkingedinburgh** [comment]
huguanglong wrote:
> got a very good result (2nd place, and supass all the other hybrid 
> unit selection systems except iFlytech's. ) 
That statement is factually incorrect. The USTC system was *equally* 
natural to several other systems (in terms of isolated sentence 
naturalness, when combining results from all listener types). It did not 
surpass them.

Please take more care when interpreting Blizzard results, and always 
consult the statistical significance tests before making statements 
about system performance.

Simon


-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by wotulong** [comment]
@ljuvela ，Is there any video resources about the course sharing?

**Comment by ljuvela** [comment]
Here's Simon's lecture at SPCC: http://www.speech.zone/courses/one-off/spcc2017/

About WaveNet and other stuff there, I can't distribute any material that the authors haven't made public themselves.

**Comment by huguanglong** [comment]
@dreamk73 Yeah, the WaveNet is too complex to be used commercially. [DeepVoice](https://arxiv.org/pdf/1702.07825.pdf) has taken some optimization techniques to make it run in real-time. Maybe it can help.

**Comment by huguanglong** [comment]
@ljuvela Thank you for your advice. The USTC system might run very slowly.

**Comment by huguanglong** [comment]
@simonkingedinburgh Thank you for your correction. I'm sorry that I just copy the statement from the paper:
`Figure 6 shows the boxplot of MOS of each system on
naturalness. Our system achieved MOS of 3.6, which shows
no statistical difference with system E, L, P and ranks 2nd
place in all submitted system. It’s a considerable performance
comparing with unit selection systems.`  . From the figure of Mean Opinion Scores (naturalness) , it does show no difference between the GLEP systems.

**Comment by wotulong** [comment]
@ljuvela Thanks, it's helpful.

**Comment by simonkingedinburgh** [comment]
huguanglong wrote:
> I'm sorry that I just copy the statement from the paper:
Actually, no. You added the further claim "supass [sic] all the other 
hybrid unit selection systems except iFlytech's". This is *not* claimed 
in the paper, because it is not the case.

What the paper says is correct. The authors have made reasonable claims 
supported by the evidence.

Simon





-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by huguanglong** [comment]
@simonkingedinburgh Thank you for your further correction. You are right. It's exciting to see the SPSS system can achieve such result.

**Comment by simonkingedinburgh** [comment]
The most interesting result from Blizzard this year was that multiple 
approaches to waveform generation are all competitive within that group 
of equally-natural systems.


-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.
