### ISSUE TITLE
Any Ref about the MCEP post-processing ?

### ISSUE THREAD

**Issue by gillesdegottex** [CSTR-Edinburgh/merlin#241]
Hi,

Does anybody has any bibliographic reference about the post-processing used in Merlin ?

Starting at https://github.com/CSTR-Edinburgh/merlin/blob/7c458c7852d8bae3a2e4d3044a2160f465e4d467/src/utils/generate.py#L199

I dare saying the SPTK code is a bit cryptic.

**Comment by ronanki** [comment]
I believe @zhizhengwu wrote this piece of code -- he might have some reference. I once had it, but can't find now.

**Comment by bajibabu** [comment]
This might be helpful https://github.com/CSTR-Edinburgh/merlin/issues/38

**Comment by ljuvela** [comment]
The main idea seems to be multiplying the MGC coefficients, excluding c(0) and c(1), with some post-filtering constant.

I think the post-filter is similar to what Takaki et al. used in their recent paper:
http://www.isca-speech.org/archive/Interspeech_2017/pdfs/0488.PDF

Both that and Baji's reference point to this paper:
http://ieeexplore.ieee.org/document/479266/

**Comment by zhizhengwu** [comment]
It is originally from HTS. Please check this paper: https://docslide.us/documents/incorporating-a-mixed-excitation-model-and-postfilter-into-hmm-based-text-to-speech.html

**Comment by gillesdegottex** [comment]
Thanks a lot guys! (and sorry for the duplicate ...)

The HTML link is dead though.
I'll have a look at Takaki's

**Comment by chazo1994** [comment]
I see some confusion, in the paper referenced by @zhizhengwu, they describe a postfilter on Mel frequency cepstral coefficients but in your code (in generate.py), the input file mgc is Mel generalized cepstral coenficients. So I think, it have a bit differences.
