### ISSUE TITLE
Problem about voice definition in hybrid synthesis.

### ISSUE THREAD

**Issue by lomizandtyd** [CSTR-Edinburgh/merlin#242]
I followed the updated hybrid speech synthesis example.

-----

Little Bugs:
- line 87 in [02_build_unit_selection_model.sh](https://github.com/CSTR-Edinburgh/merlin/blob/master/egs/hybrid_synthesis/s1/02_build_unit_selection_model.sh), it should be `cd .. #cd..`
- labs of demo data are reduced (60 -> 53) when prepare labels in [step 3](https://github.com/CSTR-Edinburgh/merlin/blob/master/egs/hybrid_synthesis/s1/03_build_parametric_model.sh). I didn't check it, just changed the value in config file..
- I can not train duration model in step 3 until I changed [line 258](https://github.com/CSTR-Edinburgh/merlin/blob/master/src/run_merlin.py) in src/run_merlin.py from `if init_dnn_model_file != "'_'":` to `if init_dnn_model_file != '_':`.

It is supposed to change some directory definition after step3.
Whatever, I follow the scripts and step into 05_run_hybrid_voice.sh

code in [line 42~44](https://github.com/CSTR-Edinburgh/merlin/blob/master/egs/hybrid_synthesis/s1/05_run_hybrid_voice.sh) of step 5
```
### generate wav
echo "generating wav from scheme file"
${FESTDIR}/bin/festival -b ${out_dir}/$scheme_file
```
 could not generate wavs but only utt files. 

Here is my problem: I could not add the hybrid voice into festival library,
because I have no voice definition scm files for the generated hybrid voice.

In the example directory, I found a [voice_definition_file](https://github.com/CSTR-Edinburgh/merlin/tree/master/egs/hybrid_synthesis/s1/voice_definition_files) directory with scm files.
The file seems to be available for hts based hybrid system. However, related modules are missing.

 My question is:
- Can you give me some guidance to complete the defintion file from hts to merlin hyrbid.
- Could you provide completely hts related voice definition files ? I expect to use it as a reference.
- Do you have a time schedule for completing such scm files?

**Comment by ronanki** [comment]
Thank you for listing all possible bugs. Hybrid synthesis is still in experimental phase for two reasons:
1. A working version of this system is hard-wired to combilex phoneset (commercial licensed)
2. The voice definition file is somewhat hardwired with hts based system -- although, we're not using any part of it, except for loading the model.   

We're working on resolving these issues and hope to make this bug free by the end of September.

**Comment by navidnadery** [comment]
step 04 some variables are written bad spelling.
