### ISSUE TITLE
data prepare

### ISSUE THREAD

**Issue by SHU-HAN** [CSTR-Edinburgh/merlin#25]
if i want to train my own model
what ingredients should i prepared??

**Comment by gillesdegottex** [comment]
Have a look at the demo voices (egs/slt_arctic/s1/) and see what's happening in 'experiments'.
You basically need to:
1) copy the content of 'egs/slt_arctic/s1/' to 'egs/mynewvoice/s1/'
2) adapt the configuration scripts in 'egs/mynewvoice/s1/'
3) compute the features of your new voice (lf0, bap, mgc)
4) generate the state-aligned labels (you can use those from HTS)
5) put features labels in 'egs/mynewvoice/s1/experiments/mynewvoice_dnn_world/acoustic_model/data'
6) run Merlin: ./scripts/submit.sh ${MerlinDir}/src/run_merlin.py conf/acoustic_configfile.conf 
(and similarly for the duration model)
(I think there should be a tutorial coming at some point for this)

**Comment by gillesdegottex** [comment]
and you can have a look at #18 also.

**Comment by rhoposit** [comment]
Are state-aligned label necessary, or is it possible to train using only phone-aligned labels?

**Comment by ronanki** [comment]
state-alignments are not compulsory. You can even use phone alignments. 

change Labels to phone_align in conf/global_settings.conf and re-create all the configuration files.

**Comment by rhoposit** [comment]
Possible bug? Let me know if you want this in a separate issue. 

I changed to phone_align in conf/global_settings.conf and re-created all the configuration files. 
The value for label_type was not updated automatically inside of duration config files (duration.conf and test_dur_synth.conf). In other words, it remained state_align even though I changed my global config file. However, it did correctly change automatically in acoustic.conf and test_synth.conf. I was running scripts/prepare_config_files.sh and prepare_config_files_for_synthesis.sh

**Comment by ronanki** [comment]
Are you using latest commit. If not, please update. I found this bug two days before and fixed it.

**Comment by rhoposit** [comment]
Ok thanks. I just pulled down and used the latest commit and now it does work for prepare_config_files.sh, but it did not work for prepare_config_files_for_synthesis.sh.

**Comment by ronanki** [comment]
Can you please check once again? I didn't find anything wrong even with prepare_config_files_for_synthesis.sh when I updated Labels to phone_align in conf/global_settings.cfg

**Comment by rhoposit** [comment]
Ok yes I confirm the prepare_config_files_* scripts are fixed.

**Comment by ronanki** [comment]
Some steps for data preparation and model building:
https://github.com/CSTR-Edinburgh/merlin/wiki/step-by-step-guide-to-train-new-voice
