### ISSUE TITLE
ImportError: Cannot import name 'prepare_file_path_list'

### ISSUE THREAD

**Issue by BiaWie** [CSTR-Edinburgh/merlin#252]
Hello everybody,

I'm taking my first steps with merlin and wanted to run the demo to get a first impression.  
I followed the blog on Josh Meyer's website step by step  for intallation (and the installation was successful (checked with test_install.sh))
Now I wanted to run the demo (run_demo.sh) and it failed, giving back the error: 
"ImportError: cannot import name 'prepare_file_path_list'", so I  guess there's something wrong with utils? (Same with test_file_paths-py and run_full_voice.sh)

Is that a common problem, does anyone have a clue and could help me?

(Unfortunately I'm a total noob in python, too, so my own attempts in troubleshooting seem more like groping in the dark..)

Thank you in advance for any advice!

**Comment by r9y9** [comment]
https://github.com/CSTR-Edinburgh/merlin/pull/249 should have fixed the issue. Do you still see the problem with latest Merlin?

**Comment by BiaWie** [comment]
Wow, that was fast - many thanks!
To your question - I downloaded Merlin three days ago, so yes, I guess, it's the latest version..?
