### ISSUE TITLE
Why is the bap order hard-coded in analysis script?

### ISSUE THREAD

**Issue by bajibabu** [CSTR-Edinburgh/merlin#26]
I checked the analysis script and figured that number of aperiodicites are depend upon the sampling frequency https://github.com/CSTR-Edinburgh/merlin/blob/master/tools/WORLD/test/analysis.cpp#L180. You will get 5 bands when the sampling frequency is 48000 Hz. Instead of hard-coding the number of bands on the analysis script why don't we take the envelops and do the band analysis as spectral envelops.

**Comment by gillesdegottex** [comment]
For compressing the aperiodicity from STRAIGHT analysis, I'm using:
cmd = 'mcep -a '+str(alpha)+' -m '+str(int(order))+' -l '+str(dftlen)+' -e 1.0E-8 -j 0 -f 0.0 -q 3 '+tmpspecfile+' > '+outspecfile
And it works great.

Can someone try it on WORLD's aperiodicity ?

**Comment by bajibabu** [comment]
https://github.com/CSTR-Edinburgh/merlin/pull/27
