### ISSUE TITLE
Current release distort TTS voices compared to before REAPER support

### ISSUE THREAD

**Issue by sinlam** [CSTR-Edinburgh/merlin#273]
Hi all,
  I spent many hours trying to verify why the TTS voices generated have worse output compare to before the recent update. 

I have a voice model with 3000 voices and trained with most recent version (all default parameters) and the TTS voice is somewhat distorted. Then I checkout the version before REAPER update, reinstall Merlin and train the model, and the TTS voices are OK. 

Can someone please confirm this problem? I would like to use the latest update but currently I cannot. Thanks for any info!

**Comment by ronanki** [comment]
You can fall back to using old version i.e., using original World F0 by setting Reaper to False:
https://github.com/CSTR-Edinburgh/merlin/blob/master/misc/scripts/vocoder/world/extract_features_for_merlin.py#L79

**Comment by sinlam** [comment]
Yes, the fall back approach works. I close this issue now. Thanks Srikanth!
