### ISSUE TITLE
how to use tensorflow to train the source?

### ISSUE THREAD

**Issue by hwong39** [CSTR-Edinburgh/merlin#280]
i am using tensorflow to train with switch_to_tensorflow as True, i get error when training the source to target.
2017-11-21 16:16:04,976    DEBUG  configuration: configuration completed
--- Job started ---
Traceback (most recent call last):
   File
"/home/hwong/merlin-master/src/run_tensorflow_with_merlin_io.py", line
249, in <module>
     tensorflow_instance = TensorflowClass(cfg)
   File
"/home/hwong/merlin-master/src/run_tensorflow_with_merlin_io.py", line
117, in __init__
     self.GenTestList = cfg.GenTestList
AttributeError: 'configuration' object has no attribute 'GenTestList'

**Comment by jess-ieee** [comment]
how did you end up solving the issue?
