### ISSUE TITLE
ERROR [+7031] during forced_alignment.py

### ISSUE THREAD

**Issue by HandsomeDevilv112** [CSTR-Edinburgh/merlin#293]
Trying to run forced_alignment while creating a new voice results in an HTK error that reads
"ERROR [+7031]  PutTransMat: Row 6 of transition mat sum = 1.011627"
Looking up that error, I've found http://disfruta555.blogspot.com/2015/04/trouble-shooting-htk-error-7031.html, which makes it seem like it could be relatively easy to fix, but I'm not quite grasping what I need to do with code block as is.
line 281-286 of forced_alignment.py looks to be what needs changed, but I'm just a little to amateur it seems. 

Call stack:
Mon Jan  1 15:53:14 2018
---training HMM models
  ERROR [+7031]  PutTransMat: Row 6 of transition mat sum = 1.011627

 FATAL ERROR - Terminating program /home/al/merlin/tools/bin/htk/HERest
Traceback (most recent call last):
  File "forced_alignment.py", line 382, in <module>
    aligner.train_hmm(7, 32)
  File "forced_alignment.py", line 286, in train_hmm
    stdout=PIPE)
  File "/home/al/miniconda2/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/al/merlin/tools/bin/htk/HERest', '-C', '/home/al/merlin/egs/build_your_own_voice/s1/config/cfg', '-S', '/home/al/merlin/egs/build_your_own_voice/s1/config/train.scp', '-I', '/home/al/merlin/egs/build_your_own_voice/s1/config/mono_phone.mlf', '-M', '/home/al/merlin/egs/build_your_own_voice/s1/model/hmm_mix_1_iter_1', '-H', '/home/al/merlin/egs/build_your_own_voice/s1/model/hmm0/macros', '-H', '/home/al/merlin/egs/build_your_own_voice/s1/model/hmm0/hmmdefs', '-t', '250.0', '150.0', '2000.0', '/home/al/merlin/egs/build_your_own_voice/s1/mono_phone.list']' returned non-zero exit status 119

**Comment by moshiul-rabbi** [comment]
Hi handsomeDevilv112,
I am having the same problem. Did you find any solution or some way. Thanks

**Comment by HandsomeDevilv112** [comment]
I haven't made any progress on it. I really feel there should be a way to edit the htk code mentioned, but it is beyond my understanding.

**Comment by m-toman** [comment]
Hi,
I planned to submit a PR for that but to give you a potential solution earlier, please try this: 
[forced_alignment_parallel.txt](https://github.com/CSTR-Edinburgh/merlin/files/1736012/forced_alignment_parallel.txt)

I'm currently on my phone so sorry for the txt extension ;)

**Comment by HandsomeDevilv112** [comment]
it kinda took 19 hours, but I received the message that all labels had been successfully created! Huzzah!
Fix verified on 2/21/18 m-toman is a surely a wizard.
Closing.

**Comment by gillesdegottex** [comment]
This script is priceless, just replaced forced_alignment_parallel.py by it and labs have been generated.
You should consider making a PR for it.

**Comment by m-toman** [comment]
Thanks, you are right, finally merged my version with the latest merlin version.

**Comment by patrickzzy** [comment]
I met the same issue of "ERROR [+7031] PutTransMat", and I change to use the updated forced_alignment.py, seems this error has gone, but now I get lots of "WARNING [-7324]  StepBack: Bad data or over pruning" when doing "#estimate per chunk",  and it stucks at "# wait until all HERest calls are finished", anybody knows how I can fix this problem?

**Comment by lardontis** [comment]
I managed to make a fix for do_alignment as commented in comments above:

https://github.com/lardontis/fix-do_alignment-multisyn
