### ISSUE TITLE
bug: frontend/acoustic_composition.py

### ISSUE THREAD

**Issue by Jackiexiao** [CSTR-Edinburgh/merlin#302]
if you uncomment file merlin/src/frontend/acoustic_composition.py line110-112 which is 
```
#if os.path.isfile(out_file_name):
#    logger.info('processing file %4d of %4d : %s exists' % (i+1, self.file_number, out_file_name))
#    continue
```
the program won't run as I expected but showed something strange like 
```
WARNING: no silence found!
CRITICAL: ListDataProvider: the number of frames in label and acoustic features are different
```
And if I change the code back, everything works fine again 

I wonder how to speed up MAKECMP, because it really cost time, for example if I have 15000 wav files, it will cost nearly 6 hours in this part

**Comment by seblemaguer** [comment]
I am confused, why do you want to decomment these lines? I think they are here for debugging purpose as the "continue" won't let you go to the inner loop so you don't have the files you want/need after.

**Comment by Jackiexiao** [comment]
I know, I want to skip the cmp file that I already have, so I don't need to prepare the cmp file again (it costs time ) if I train the network again
