### ISSUE TITLE
Running with GPU

### ISSUE THREAD

**Issue by martedva** [CSTR-Edinburgh/merlin#305]
Hello,

I've tried researching and looking through the code, but I am having a hard time trying to switch Merlin over to my GPU instead of my CPU. It just keeps on showing me this message:
![image](https://user-images.githubusercontent.com/6831315/36108550-621eca2a-101d-11e8-9066-3c465279cc0a.png)

I am unsure what to do - I have a hunch, that it is because I have a never version of CUDA installed, but can that really be true?

Thanks in advance,
Martin

**Comment by khusainovaidar** [comment]
I have it working with cuda 9.0.176, 384.81 driver, but it seems to be not very efficient from speed point of view. I get only ~5.5 sents/s with cudnn installed (tried 7.0.4 and 7.0.5 ver) and ~16 sents/s without it. Expected much faster training with 1080 gpu.

**Comment by RasmusD** [comment]
I'm not sure a newer cuda might mess things up.
Do you get anything from the nvidia-smi command?

**Comment by martedva** [comment]
It says:

"_nvidia-smi: command not found_"

Any chance i haven't installed CUDA properly? I followed the guide in the following link:
https://gist.github.com/wangruohui/df039f0dc434d6486f5d4d098aa52d07#install-cuda

**Comment by RasmusD** [comment]
Yeah, if it says nvidia-smi not found. Then there's something wrong with your cuda installation.

That'd explain why you can't get merlin to detect your gpu.

I don't know the guide you've linked. Why not follow the official nvidia stuff from nvidia's website?

**Comment by martedva** [comment]
I had trouble using their guide, as I am using "_Bash on Ubuntu on Windows_", where I want to install my CUDA setup.

**Comment by RasmusD** [comment]
Yup - that'd seem like the right thing to do.
Or dual-boot your pc with Windows/Ubuntu.

**Comment by akashmishra23** [comment]
CUDA 9 and CuDNN 7 for CUDA 9 is only Supported by Tensorflow r1.5 and onwards, Try Upgrading Tensorflow
