### ISSUE TITLE
train_DNN ValueError: could not broadcast input array

### ISSUE THREAD

**Issue by ecooper7** [CSTR-Edinburgh/merlin#308]
Hello,

I am running the build_your_own_voice recipe with about 3.5 hours of data, phone-aligned labels, a custom questions file for my phoneset, and a reduced buffer size because I had been getting an out-of-memory error previously.  Now, in step 06_train_acoustic_model.sh, I get a failure in the train_DNN step:

```
2018-02-13 18:31:47,639 CRITICAL       main    : train_DNN threw an exception
Traceback (most recent call last):
  File "/proj/tts/tools/ecooper/merlin/src/run_merlin.py", line 1270, in <module>
    main_function(cfg)
  File "/proj/tts/tools/ecooper/merlin/src/run_merlin.py", line 820, in main_function
    cmp_mean_vector = cmp_mean_vector, cmp_std_vector = cmp_std_vector,init_dnn_model_file=cfg.start_from_trained_model)
  File "/proj/tts/tools/ecooper/merlin/src/run_merlin.py", line 337, in train_DNN
    _, temp_train_set_x, temp_train_set_y = train_data_reader.load_one_partition()
  File "/proj/tts/tools/ecooper/merlin/src/utils/providers.py", line 296, in load_one_partition
    shared_set_xy, temp_set_x, temp_set_y = self.load_next_partition()
  File "/proj/tts/tools/ecooper/merlin/src/utils/providers.py", line 736, in load_next_partition
    temp_set_x[current_index:self.remain_frame_number, ] = self.remain_data_x
ValueError: could not broadcast input array from shape (804,1657) into shape (768,1657)
Lock freed
```

Any suggestions for where to start looking into what might be going wrong here?
Thanks

**Comment by felipeespic** [comment]
Hi,
It looks like you are having inconsistent number of frames (804 vs 768). It usually happens when there is data with silence trimmed and other that don't.

I suggest playing with the parameters:
```
enforce_silence: False
silence_pattern: ['*-sil+*']
```

**Comment by haiewu** [comment]
can you solve the problem? I met same problem.....

**Comment by theabc123** [comment]
Hi, try to increase the buffer size in your config files. This resolved the problem for me.

**Comment by ecooper7** [comment]
apologies for the extremely late reply, but -- increasing the buffer size did in fact resolve the issue.  I had lowered the buffer size to try to solve a MemoryError, but I made it too low.  Thank you!
