### ISSUE TITLE
Force-alignment unsuccessful for speaker adaptation!

### ISSUE THREAD

**Issue by martedva** [CSTR-Edinburgh/merlin#320]
Hello,

I am trying to implement the speaker adaptation, but run into a problem, when i run the ./02_prepare_labels.sh script, as it give me the following error message, which leaves my label_state_align folder empty despite having run the script.

![image](https://user-images.githubusercontent.com/6831315/37802944-c5850d72-2e2c-11e8-9b13-4d2403152d8a.png)

I tried with a smaller dataset, as i was trying to train on almost the entire VCTK speech corpus, which probably could be the problem, somehow (despite not experiencing any RAM or GPU problems), however, this gave me the same error message (in a more concise manner).

![image](https://user-images.githubusercontent.com/6831315/37802815-43519410-2e2c-11e8-83e7-c686d1f518b8.png)

The problem is that this script works impeccably on both slt_arctic_full and build_your_own_voice. I have made sure that my global_settings.cfg file has the same properties and paths, with the exception of the information, which is specific for my speaker adaptation data.

I have tried looking through the scripts and python files used when running the script, ./02_prepare_labels.sh, however, with no luck.

Any thoughts? Thanks in advance,

**Comment by simonkingedinburgh** [comment]
Martin Edvardsen wrote:
> it give me the following error message
screen shots are not a helpful way to show error messages - paste the 
text into your message instead - then, it's easier to read and also 
becomes searchable

Simon


-- 
Prof. Simon King
Professor of Speech Processing and Director of the Centre for Speech 
Technology Research
University of Edinburgh,UK
www.cstr.ed.ac.uk


The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by martedva** [comment]
https://github.com/CSTR-Edinburgh/merlin/pull/319

This pull requests fixes it with fixed paths.
