### ISSUE TITLE
instruction of code

### ISSUE THREAD

**Issue by willian56** [CSTR-Edinburgh/merlin#327]
If there any help to learn more about the merlin coding structure? I have spent a whole day to read the src/run_merlin.py carefully and can only read about 100 lines, it wastes a lot of time because of a lot of packages invoked, so can you give me some advice or instruction? I want to learn more about the merlin code. @ronanki

**Comment by simonkingedinburgh** [comment]
> willian56 <mailto:notifications@github.com>
> 2 April 2018 at 11:45
>
> If there any help to learn more about the merlin coding structure?
>

http://www.speech.zone/courses/one-off/merlin-interspeech2017/

might help, to some extent, with the higher-level parts (e.g., config 
files).

You say that understanding code "wastes a lot of time" but please do 
remember that this is an Open Source research tool and therefore 
requires you to invest your own time and effort. If you don't want to do 
that, then don't use research code.

Simon

-- 
Prof. Simon King
Professor of Speech Processing and Director of the Centre for Speech 
Technology Research
University of Edinburgh,UK
www.cstr.ed.ac.uk

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by willian56** [comment]
@simonkingedinburgh yeah，it helps a lot. Thanks for your advice.
