### ISSUE TITLE
mandarin_voice:WARNING:no silence found and FileNotFoundEroor:feed_forward_6_tanh.model

### ISSUE THREAD

**Issue by Ka6utack** [CSTR-Edinburgh/merlin#328]
i try to find a feasible way to synthesis mandarin! refer to Jackiexiao's TTS frontend and Merlin! Almost succeed! but always met this situation in the end: no silence found and FileNotFoundEroor:feed_forward_6_tanh.model
! which step i did wrong or omit! who can tell me! thank you sincerely
the error like this:
WARNING: no silence found!
WARNING: no silence found!
2018-04-03 11:45:46,781 INFO      acoustic_norm: Loaded min max values from the trained data for feature dimension of 471
2018-04-03 11:45:50,391 INFO           main    : label dimension is 471
2018-04-03 11:45:50,392 INFO           main    : generating from DNN
Traceback (most recent call last):
  File "/home/ka6utack/PycharmProjects/amazeWork/merlin/src/run_merlin.py", line 1308, in <module>
    main_function(cfg)
  File "/home/ka6utack/PycharmProjects/amazeWork/merlin/src/run_merlin.py", line 933, in main_function
    dnn_generation(test_x_file_list, nnets_file_name, lab_dim, cfg.cmp_dim, gen_file_list, reshape_io)
  File "/home/ka6utack/PycharmProjects/amazeWork/merlin/src/run_merlin.py", line 419, in dnn_generation
    dnn_model = pickle.load(open(nnets_file_name, 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: '/home/ka6utack/PycharmProjects/amazeWork/merlin/egs/mandarin_voice/s1/experiments/0402_try/acoustic_model/nnets_model/feed_forward_6_tanh.model'

**Comment by Ka6utack** [comment]
You are sort of bingism! i have seen you in issues area before!  Also，I have ran through all the processes successfully with the help of @Jackiexiao  ！THANKS AGAIN! @Jackiexiao ! It is proved that this model is available for Mandarin TTS！And the effect is also impressive, if you have a not bad corpus! The only short board may be the generation voice time is a bit slow but everything else is very good! The above problem i mentioned is a little stupid, and i already solved it! Work hard! it really does work!

**Comment by Ka6utack** [comment]
You are sort of bringism! i have seen you in issues area before! Also，I have ran through all the processes successfully with the help of @Jackiexiao ！THANKS AGAIN! @Jackiexiao ! It is proved that this model is available for Mandarin TTS！And the effect is also impressive, if you have a not bad corpus! The only short board may be the generation voice time is a bit slow but everything else is very good! The above problem i mentioned is a little stupid, and i already solved it! Work hard! it really does work!

**Comment by jinfagang** [comment]
@Ka6utack Glad to hear that. Then is there any guidance or whitepaper how to implement a worked Mandarin voice system?

**Comment by v-yunbin** [comment]
@how do you solve it, i met same problem with you and The speed of the synthesis is very fast .
Look forward to your reply.

**Comment by v-yunbin** [comment]
@Ka6utack @jinfagang hello, do you test the model with a new text? when i test with new text, the voice of the synthetic voice is fast. 
Looking forward to your reply

**Comment by Ka6utack** [comment]
it is fine！maybe some problems is existed in your code process！maybe you don't know clearly
 about the merlin synthesis process！ a synthsis process takes about thirty or fourty seconds! just claer the merlin synthesis processes and rewrite several scripts, good luck!

**Comment by v-yunbin** [comment]
@Ka6utack my code come from Jackiexiao
