### ISSUE TITLE
How to run merlin with GPU

### ISSUE THREAD

**Issue by willian56** [CSTR-Edinburgh/merlin#341]
Hello, everyone. I want to run merlin in GPU using the theano backend, but i find it actually run in CPU.

Running on GPU id=1 ...

but actually when I type 'nvidia-smi' there is no program running in the GPU. Is there any advice for this problem. Any comment about "theano and gpu" is welcomed. It might due to the 'THEANO_FLAGS' problem, I guess.

**Comment by huguanglong** [comment]
It seems that the newest theano does't support old parameter format. You can try this in scripts/submit.sh:
replace string "gpu" by "cuda", for example change the line 20:
"THEANO_FLAGS="mode=FAST_RUN,device=gpu$gpu_id,"$MERLIN_THEANO_FLAGS" to "THEANO_FLAGS="mode=FAST_RUN,device=cuda$gpu_id,"$MERLIN_THEANO_FLAGS"

Hope this can help you.
