### ISSUE TITLE
run_merlin.sh success met error: "out of bounds for axis 0 with size 0"

### ISSUE THREAD

**Issue by v-yunbin** [CSTR-Edinburgh/merlin#352]
when run" 07_run_merlin.sh <path_to_text_dir> <path_to_test_dur_conf_file> <path_to_test_synth_conf_file>" met follows errors:

_**Traceback (most recent call last):
  File "/home/yunbin.zhang/merlin/src/run_merlin.py", line 1308, in <module>
    main_function(cfg)
  File "/home/yunbin.zhang/merlin/src/run_merlin.py", line 959, in main_function
    generator.acoustic_decomposition(gen_file_list, cfg.cmp_dim, cfg.out_dimension_dict, cfg.file_extension_dict, var_file_dict, do_MLPG=cfg.do_MLPG, cfg=cfg)
  File "/home/yunbin.zhang/merlin/src/frontend/parameter_generation.py", line 164, in acoustic_decomposition
    gen_features = mlpg_algo.generation(current_features, var, out_dimension_dict[feature_name]//3)
  File "/home/yunbin.zhang/merlin/src/frontend/mlpg_fast.py", line 122, in generation
    var_frames[0, 1] = 100000000000;
IndexError: index 0 is out of bounds for axis 0 with size 0
(py3virtualenv) [root@node1 s1]# ./07_run_merlin_text.sh  experiments/mandarin_voice/test_synthesis/txt/A2_69.txt conf/test_dur_synth_mandarin_voice.conf conf/test_synth_mandarin_voice.conf**_

**Comment by v-yunbin** [comment]
it seems that synthesised wav is background voice but not person voice,

**Comment by Jackiexiao** [comment]
do you use festival to generate mandarin lab? festival don't support mandarin

**Comment by v-yunbin** [comment]
hi happy to see you
i just use the script "prepare_labels_from_txt.sh" to generate the lab and the script use the festival .
how i should generate the lab according to txt?

**Comment by v-yunbin** [comment]
but i use the script "prepare_labels_from_txt.sh" to genrate english lab , met same error

**Comment by v-yunbin** [comment]
@Jackiexiao to validate whether it work that festival_utt_to_lab in frontend,  I test it with running "./make_labels ./test/labels/ ./test/utts  $FESTDIR/examples/dumpfeats ."  but it really don't work and i am very confused. can you help me?

**Comment by v-yunbin** [comment]
@Jackiexiao Thank you very much, i will follow your log to redo it. and can i konw your gcc version when you using festival?

**Comment by Jackiexiao** [comment]
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609

**Comment by shartoo** [comment]
Have you guys solved the problem?
