### ISSUE TITLE
install error on ubuntu

### ISSUE THREAD

**Issue by v-yunbin** [CSTR-Edinburgh/merlin#353]
i install all on my centos system and i try to install on my ubuntu system , but not success:
Receiving objects: 100% (751/751), 18.98 MiB | 102.00 KiB/s, done.
Resolving deltas: 100% (379/379), done.
Checking connectivity... done.
configuring MagPhase...
cp: cannot stat 'SPTK-3.9/build/bin/b2mc': No such file or directory
cp: cannot stat 'SPTK-3.9/build/bin/bcp': No such file or directory
cp: cannot stat 'SPTK-3.9/build/bin/c2acr': No such file or directory
cp: cannot stat 'SPTK-3.9/build/bin/freqt': No such file or directory
cp: cannot stat 'SPTK-3.9/build/bin/mc2b': No such file or directory
cp: cannot stat 'SPTK-3.9/build/bin/mcep': No such file or directory
cp: cannot stat 'SPTK-3.9/build/bin/merge': No such file or directory
cp: cannot stat 'SPTK-3.9/build/bin/sopr': No such file or directory
cp: cannot stat 'SPTK-3.9/build/bin/vopr': No such file or directory
cp: cannot stat 'SPTK-3.9/build/bin/x2x': No such file or directory
cp: cannot stat 'REAPER/build/reaper': No such file or directory
deleting downloaded tar files...
cp: cannot stat 'SPTK-3.9/build/bin/*': No such file or directory
cp: cannot stat 'postfilter/bin/*': No such file or directory
cp: cannot stat 'REAPER/build/reaper': No such file or directory
Error installing SPTK tools! Try installing dependencies!!
sudo apt-get install csh
root@ubuntu:/home/yunbin/merlin# gcc
gcc: fatal error: no input files
compilation terminated.

**Comment by felipeespic** [comment]
Hi @v-yunbin ,

Did you fix the issue? How you did it?

**Comment by sausax** [comment]
Fixed after installing csh `sudo apt-get install csh`

**Comment by sausax** [comment]
No. I think it needs csh.

**Comment by felipeespic** [comment]
That's strange. The script was written specifically for bash (see the first line in the script). 
Well, if it works with csh for you, it's OK I guess.

**Comment by v-yunbin** [comment]
@felipeespic , i try it again, it works.  i think its very strange that it sometimes work and it sometimes not work. i have give the tool because decode is worse

**Comment by orhaneee** [comment]
I can confirm that it is NOT working with bash.. I installed csh and issue resolved.

**Comment by Yogatiara** [comment]
I currently also have the same error, and have successfully installed CSH with "sudo apt-get install CSH". but the error is still there

**Comment by Yogatiara** [comment]
@ben-8878 I currently also have the same error, and have successfully installed CSH with "sudo apt-get install CSH". but the error is still there
