### ISSUE TITLE
Running on GPU.

### ISSUE THREAD

**Issue by Chaos-XingChao** [CSTR-Edinburgh/merlin#36]
Hi, guys,
  I found out I can not use GPU when running merlin example.
  And I seems find out why : 
  First, there always lock gpu when running demo but only when successfully running down, there will be free lock. So I add free lock in each step.
  Second, seems that github code miss a file named "run_on_me_or_pid_quit", I download it from 
  "http://homepages.inf.ed.ac.uk/imurray2/code/gpu_monitoring/gpu_lock/run_on_me_or_pid_quit"
  And now I can use gpu normally.

**Comment by rhoposit** [comment]
I had a similar GPU lock issue after killing processes during the demo. I had to free the GPUs (even though no processes were running) with this script:
https://github.com/CSTR-Edinburgh/merlin/blob/master/src/gpu_lock.py
```python gpu_lock.py --free <gpu_id>```
