### ISSUE TITLE
phoneme symbols

### ISSUE THREAD

**Issue by ecooper7** [CSTR-Edinburgh/merlin#365]
Hello,

I am recalling that there were certain symbols that should be avoided as phoneme names in HTS:

http://hts.sp.nitech.ac.jp/hts-users/spool/2007/msg00305.html

I am wondering to what extent this is the case with Merlin as well.  Clearly symbols which are used as delimiters in the label files should be avoided, but I am wondering whether Merlin can accept e.g. phoneme names which are numerals, or if it is better to play it safe and follow the same restrictions on phoneme names as with HTS.

**Comment by felipeespic** [comment]
Maybe @RasmusD knows?

**Comment by dreamk73** [comment]
I have used different phoneme symbols including ones with numerals and it is no problem. As you said, the only issue is not using symbols that are used as delimiters.

**Comment by ecooper7** [comment]
ok, that's good to know, thanks so much!

**Comment by RasmusD** [comment]
Just a quick note.
If you use an HTK based alignment system you'd have to follow the HTK/HTS conventions during alignment.
So while changing the symbols is fine from merlins perspective (bar what @dreamk73 pointed out) - it might not be from other non-merlin parts.
