### ISSUE TITLE
Not find mgc file in acoustic modeling stage

### ISSUE THREAD

**Issue by v-yunbin** [CSTR-Edinburgh/merlin#368]
_zhangyb/merlin/egs/mandarin_voice/s1/experiments/mandarin_voice/acoustic_model/inter_module/nn_mgc_lf0_vuv_bap_187/A11_11.cmp
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/data02/zhangyb/anaconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/data02/zhangyb/anaconda3/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/data02/zhangyb/merlin/src/run_merlin.py", line 487, in perform_acoustic_composition_on_split
    acoustic_worker.prepare_nn_data(in_file_list_dict, nn_cmp_file_list, in_dimension_dict, out_dimension_dict)
  File "/data02/zhangyb/merlin/src/frontend/acoustic_base.py", line 122, in prepare_nn_data
    self.prepare_data(in_file_list_dict, out_file_list, in_dimension_dict, out_dimension_dict)
  File "/data02/zhangyb/merlin/src/frontend/acoustic_composition.py", line 124, in prepare_data
    features, frame_number = io_funcs.load_binary_file_frame(in_file_name, in_feature_dim)
  File "/data02/zhangyb/merlin/src/io_funcs/binary_io.py", line 64, in load_binary_file_frame
    fid_lab = open(file_name, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/data02/zhangyb/merlin/egs/mandarin_voice/s1/experiments/mandarin_voice/acoustic_model/data/mgc/A11_0.mgc'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data02/zhangyb/merlin/src/run_merlin.py", line 1320, in <module>
    main_function(cfg)
  File "/data02/zhangyb/merlin/src/run_merlin.py", line 692, in main_function
    perform_acoustic_composition(delta_win, acc_win, in_file_list_dict, nn_cmp_file_list, cfg, parallel=True)
  File "/data02/zhangyb/merlin/src/run_merlin.py", line 510, in perform_acoustic_composition
    pool.map(perform_acoustic_composition_on_split, splits_full)
  File "/data02/zhangyb/anaconda3/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/data02/zhangyb/anaconda3/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: '/data02/zhangyb/merlin/egs/mandarin_voice/s1/experiments/mandarin_voice/acoustic_model/data/mgc/A11_0.mgc'
Lock freed_

**Comment by v-yunbin** [comment]
anyone met the Situation？

**Comment by Jackiexiao** [comment]
see : https://github.com/CSTR-Edinburgh/merlin/pull/338, change `${Vocoder,,}` to `${Vocoder}`

**Comment by v-yunbin** [comment]
@Jackiexiao have modified it fllow #338, but same error still exist

**Comment by Jackiexiao** [comment]
Are you sure your vocoder install correctly? If you install World, SPTK correctly, it could extract mgc using this script [extract_features_for_merlin.py](https://github.com/CSTR-Edinburgh/merlin/blob/master/misc/scripts/vocoder/world/extract_features_for_merlin.py)

**Comment by v-yunbin** [comment]
@Jackiexiao last month , i have train acoustic model successfully on a cpu.
today i train acoustic model failture on another cpu.
i flow the instruction to insall SPTK and World with "bash conpile_toos.sh":_


mv -f .deps/mcpf-mcpf.Tpo .deps/mcpf-mcpf.Po
gcc -I./SPTK/include -g -O2   -o mcpf mcpf-mcpf.o -L./SPTK/lib -lSPTK -lm 
gcc -DPACKAGE_NAME=\"Postfilter\" -DPACKAGE_TARNAME=\"postfilter\" -DPACKAGE_VERSION=\"1.0\" -DPACKAGE_STRING=\"Postfilter\ 1.0\" -DPACKAGE_BUGREPORT=\"BUG-REPORT-ADDRESS\" -DPACKAGE_URL=\"\" -DPACKAGE=\"postfilter\" -DVERSION=\"1.0\" -DPACKAGE=\"postfilter\" -DVERSION=\"1.0\" -DHAVE_LIBM=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_STDIO_H=1 -DHAVE_STRING_H=1 -DHAVE_MATH_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STRRCHR=1 -I.    -I./SPTK/include -g -O2 -MT lsppf-lsppf.o -MD -MP -MF .deps/lsppf-lsppf.Tpo -c -o lsppf-lsppf.o `test -f 'lsppf.c' || echo './'`lsppf.c
mv -f .deps/lsppf-lsppf.Tpo .deps/lsppf-lsppf.Po
gcc -I./SPTK/include -g -O2   -o lsppf lsppf-lsppf.o -L./SPTK/lib -lSPTK -lm 
make[1]: 进入目录“/data02/zhangyb/merlin/tools/postfilter/src”
 /bin/mkdir -p '/data02/zhangyb/merlin/tools/postfilter/bin'
  /bin/install -c mcpf lsppf '/data02/zhangyb/merlin/tools/postfilter/bin'
make[1]: 对“install-data-am”无需做任何事。
make[1]: 离开目录“/data02/zhangyb/merlin/tools/postfilter/src”
compiling WORLD...
make: 对“default”无需做任何事。
g++ -O1 -g -Wall -fPIC -o ./build/analysis ./build/objs/test/audioio.o ./build/objs/test/analysis.o ./build/libworld.a -lm
g++ -O1 -g -Wall -fPIC -o ./build/synth ./build/objs/test/audioio.o ./build/objs/test/synth.o ./build/libworld.a -lm
Removing all temporary binaries... 
Done.
downloading REAPER...
fatal: 目标路径 'REAPER' 已经存在，并且不是一个空目录。
compiling REAPER...
mkdir: 无法创建目录"build": 文件已存在
-- Configuring done
-- Generating done
-- Build files have been written to: /data02/zhangyb/merlin/tools/REAPER/build
[ 26%] Built target core
[ 53%] Built target wave
[ 86%] Built target epoch_tracker
[100%] Built target reaper
downloading MagPhase vocoder...
正克隆到 'magphase'...
remote: Counting objects: 755, done.
remote: Compressing objects: 100% (243/243), done.
remote: Total 755 (delta 241), reused 448 (delta 226), pack-reused 281
接收对象中: 100% (755/755), 18.99 MiB | 2.71 MiB/s, done.
处理 delta 中: 100% (382/382), done.
configuring MagPhase...
deleting downloaded tar files...
All tools successfully compiled!!

**Comment by Jackiexiao** [comment]
have you try to use script [extract_features_for_merlin.py](https://github.com/CSTR-Edinburgh/merlin/blob/master/misc/scripts/vocoder/world/extract_features_for_merlin.py), have it extract mgc f0 successfully?

**Comment by v-yunbin** [comment]
I have tried it, using script extract_features_for_merlin.py can generate mgc file and other file successfully

**Comment by Jackiexiao** [comment]
Then ... just copy mgc and other files to your dir `/s1/experiments/mandarin_voice/acoustic_model/data`, I think `run_mandarin_voice.sh` skip this step

**Comment by v-yunbin** [comment]
i see, 3ks

**Comment by yangxiaokang** [comment]
问题跟我一样，解决了吗？
