### ISSUE TITLE
cannot run merlin/egs/build_your_own_voice/s1

### ISSUE THREAD

**Issue by monaabdelazim** [CSTR-Edinburgh/merlin#381]
I have tried to run build_your_own_voice but the labels are not created and i cannot figure out why? the full log file is here
[monalog.txt](https://github.com/CSTR-Edinburgh/merlin/files/2194396/monalog.txt)

And this is a sample of the terminal output where the error appeared :
Step 1:
Merlin default voice settings configured in "conf/global_settings.cfg"
Modify these params as per your data...
eg., sampling frequency, no. of train files etc.,
setup done...!
Step 2: 
Preparing labels...
preparing full-contextual labels using Festival frontend...
creating a scheme file from text file
generating utts from scheme file
converting festival utts to labels...
01_setup.sh 02_prepare_labels.sh 03_prepare_acoustic_features.sh 04_prepare_conf_files.sh 05_train_duration_model.sh 06_train_acoustic_model.sh 07_run_merlin.sh conf database experiments monalog.txt README.md run_demo_voice.sh scripts wav
normalizing label files for merlin...
arctic_a0001.lab
forced-alignment using HTK tools...
---preparing enverionment
---checking data
---extracting features
Thu Jul 12 00:07:15 2018
---feature_normalisation
Thu Jul 12 00:07:15 2018
---making proto
Thu Jul 12 00:07:15 2018
---training HMM models
Force-alignment unsucessful!! Please check /home/mona/Downloads/merlin/misc/scripts/alignment/state_align/forced_alignment.py
Copying labels to duration and acoustic data directories...
done...!

**Comment by Jackiexiao** [comment]
check `experiments/slt_arctic/test_synthesis/gen-lab`

**Comment by fuzeller** [comment]
Hello @monaabdelazim - One of the most common causes of that is the text data isn't correct in one or more utterances. Have you confirmed each text input exactly matches the audio? I know it's a tedious task and is not easily replicated with most speech to text solutions.

If you do need to check the audio, you could at least speed up the audio to make the listening task go more quickly.

**Comment by fuzeller** [comment]
@monaabdelazim - Happy to help.

The utts.data format is the same used by Festival TTS (one of CSTR-Edinburgh's first projects). You can see an example here:
http://festvox.org/cmu_arctic/cmuarctic.data

That would be placed in the database directory.

If using a single text file with matching file name (in the txt dir) for each wav, that's another good option.

Good luck!

**Comment by monaabdelazim** [comment]
Dear fuzeller
Thanks alot for your help. I really appreciate it.I have placed the txt data as you said but nothing changed. When I tried the run_state_aligner.sh the following error occurred.
free(): invalid next size (fast)
and i guess that is why the labels are not generated so the following steps fail as well.

**Comment by fuzeller** [comment]
@monaabdelazim  - it may be related to issue 255, so I'd suggest trying the gcc recompile to at least rule it out.

https://github.com/CSTR-Edinburgh/merlin/issues/255

**Comment by huangjun0413** [comment]
@monaabdelazim  I have the same problem, have you solved it ?

**Comment by mirfan899** [comment]
I'm having the same problem and my global_config.cfg is good and HTK installed successfully
```text
######################################
############# PATHS ##################
######################################

MerlinDir=/home/virtuoso_irfan/merlin
WorkDir=/home/virtuoso_irfan/merlin/egs/build_your_own_voice/s1

######################################
############# PARAMS #################
######################################

Voice=irfan
Labels=state_align
QuestionFile=questions-radio_dnn_416.hed
Vocoder=WORLD
SamplingFreq=16000
SilencePhone='sil'
FileIDList=file_id_list.scp

######################################
######### No. of files ###############
######################################

Train=50
Valid=5
Test=5

######################################
############# TOOLS ##################
######################################

ESTDIR=/home/virtuoso_irfan/merlin/tools/speech_tools
FESTDIR=/home/virtuoso_irfan/merlin/tools/festival
FESTVOXDIR=/home/virtuoso_irfan/merlin/tools/festvox

HTKDIR=/home/virtuoso_irfan/merlin/tools/bin/htk
```
Here is the output on console
```shell
---preparing enverionment
---checking data
---extracting features
Tue Jun  4 19:11:15 2019
---feature_normalisation
Tue Jun  4 19:11:21 2019
---making proto
Tue Jun  4 19:11:22 2019
---training HMM models
Traceback (most recent call last):
  File "/home/virtuoso_irfan/merlin/misc/scripts/alignment/state_align/forced_alignment.py", line 381, in <module>
    aligner.train_hmm(7, 32)
  File "/home/virtuoso_irfan/merlin/misc/scripts/alignment/state_align/forced_alignment.py", line 285, in train_hmm
    stdout=PIPE)
  File "/root/anaconda3/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/virtuoso_irfan/merlin/tools/bin/htk/HERest', '-C', '/home/virtuoso_irfan/merlin/egs/build_your_own_voice/s1/database/labels/config/cfg', '-S', '/home/virtuoso_irfan/merlin/egs/build_your_own_voice/s1/database/labels/config/train.scp', '-I', '/home/virtuoso_irfan/merlin/egs/build_your_own_voice/s1/database/labels/config/mono_phone.mlf', '-M', '/home/virtuoso_irfan/merlin/egs/build_your_own_voice/s1/database/labels/model/hmm_mix_1_iter_1', '-H', '/home/virtuoso_irfan/merlin/egs/build_your_own_voice/s1/database/labels/model/hmm0/macros', '-H', '/home/virtuoso_irfan/merlin/egs/build_your_own_voice/s1/database/labels/model/hmm0/hmmdefs', '-t', '250.0', '150.0', '2000.0', '/home/virtuoso_irfan/merlin/egs/build_your_own_voice/s1/database/labels/mono_phone.list']' returned non-zero exit status -11
Force-alignment unsucessful!! Please check /home/virtuoso_irfan/merlin/misc/scripts/alignment/state_align/forced_alignment.py
Copying labels to duration and acoustic data directories...
done...!
```
