### ISSUE TITLE
Bad link to Merlin paper in README

### ISSUE THREAD

**Issue by wooters** [CSTR-Edinburgh/merlin#382]
It appears that the `ssw9.net` domain name has expired. So the link to the Merlin paper in the `README.md` (http://ssw9.net/papers/ssw9_PS2-13_Wu.pdf) fails.

**Comment by seblemaguer** [comment]
ah oups yes :D thanks a lot

**Comment by dreamk73** [comment]
I would advise to use the ISCA archive link to the correct paper: 

https://isca-speech.org/archive/SSW_2016/abstracts/ssw9_PS2-13_Wu.html

**Comment by ronanki** [comment]
Thanks, done now!
