### ISSUE TITLE
Error of number of frames on build_your_own_voice when use new language.

### ISSUE THREAD

**Issue by rabbitfoot530** [CSTR-Edinburgh/merlin#387]
Hi. 
I'm trying to train for a new language.
Then, I got the following an error by executing this command `06_train_acoustic_model.sh conf/acoustic_jsut.conf`

> the number of frames in input and output features are different: 660 vs 643 (my_voice_001)
> 2018-08-06 14:30:57,997 CRITICAL       main    : train_DNN threw an exception
> Lock freed

I prepared next files for a new language.

* new wav files.
* text file for wav files.
* phone aligne by another frontend(without FESTIVAL)
* lf0, mgc, bap files generated by misc/scripts/vocoder/world/extract_features_for_merlin.sh.
* new questions file for new wav files.
* Changed DNN Frame work default to Tensorflow.
* Changed following on global_settings.cfg.
    * Labels: phone_align
    * SamplingFreq: 48000

Why I got the error ?

**Comment by 1271086950** [comment]
@rabbitfoot530 I have the same problem with 16000k,have you solved it?
