### ISSUE TITLE
vmess protocol and port-forward

### ISSUE THREAD

**Issue by liCN** [CSTR-Edinburgh/merlin#389]
I use merlin 7.9  on netgear R6300v2.
It is same problem when I try to making a port-forward from Wan to the NAS which running a V2Ray port.
As I know vmess protocol using UDP protocol to translating date,so I set the config as 0.0.0.0, 8888 to 8888,TCP/UDP but It don't work.
The router have other port forward like SSH and TLS,and it work well,so I think that the Merlin don't 
identify vmess.

**Comment by ZackHodari** [comment]
I think you have found the wrong GitHub, its possible this is what you were searching for https://github.com/RMerl/asuswrt-merlin
