### ISSUE TITLE
label_type = phone_align not recognized?

### ISSUE THREAD

**Issue by dreamk73** [CSTR-Edinburgh/merlin#39]
In my global config file I set the line
Labels=phone_align

When trying to train the duration model for my database I have label files in the label_phone_align directory. The correct label files are found but then the label_normalisation.py script still tries to read it with the load_labels_with_state_align function? Is there some problem with the propagation of this feature to the label_type variable?

**Comment by ronanki** [comment]
Whenever you change something in global config file, you need to recreate your configuration files using the provided scripts. 

And also, there is a small bug with this variable which got fixed in the recent commit. So, please update your repository as well.

**Comment by dreamk73** [comment]
I ran git pull before I ran this code and recreated the duration and acoustic config files after changing the Labels line in the global config file. The problem seems to be that the label_type line is not added to the duration and acoustic config files.

**Comment by ronanki** [comment]
It can't be the case -- as the current scripts copy a general config file from here
https://github.com/CSTR-Edinburgh/merlin/blob/master/misc/recipes/acoustic_demo.conf
and modifies the parameters as per the global config file. 

Since, the above file has that variable, it should either show state_align or phone_align when you re-create your files.

**Comment by dreamk73** [comment]
Maybe it is because I skipped the setup.sh part in the script as I copied from an existing slt_arctic_full. 

Also, when using phone_align should the dur output be only dimension 1 instead of 5?

**Comment by ronanki** [comment]
Yes -- since there are no states, the duration dimension is just 1 i.e., phone duration.
