### ISSUE TITLE
mismatched frame number of acoustic features and phone align file

### ISSUE THREAD

**Issue by moonnee** [CSTR-Edinburgh/merlin#390]
I used merlin to extract my own data and found that the frame number of acoustic features file and phone align file is mismatched. The frames number get from acoustic file is always 3 more frames than corresponding phone align file. I don't know why this could happen? Could anyone help me?

BTW, I wanna ask the meaning of alignment file.
Below are part of the phone align file I get. The numbers of each line are start _frame*50000 and end_frame* 50000. Is it right? 
> 0 2100000 x^x-sil+sil=ey@x_x/A:0_0_0/B:x-x-x@x-x&x-x#x-x$x-x!x-x;x-x|x/C:0+0+0/D:0_0/E:x+x@x+x&x+x#x+x/F:0_0/G:0_0/H:x=x@1=1|0/I:0=0/J:6+5-1
> 2100000 2700000 sil^sil-ey+m=ih@1_1/A:0_0_0/B:1-0-1@1-1&1-6#1-5$1-4!0-1;0-1|ey/C:1+1+3/D:0_0/E:det+1@1+5&1+4#0+1/F:content_3/G:0_0/H:6=5@1=1|L-L%/I:0=0/J:6+5-1
> 2700000 3550000 sil^ey-m+ih=d@1_3/A:1_0_1/B:1-1-3@1-3&2-5#1-4$1-3!1-1;0-1|ih/C:1+1+2/D:det_1/E:content+3@2+4&1+3#0+1/F:content_1/G:0_0/H:6=5@1=1|L-L%/I:0=0/J:6+5-1
> 3550000 4300000 ey^m-ih+d=s@2_2/A:1_0_1/B:1-1-3@1-3&2-5#1-4$1-3!1-1;0-1|ih/C:1+1+2/D:det_1/E:content+3@2+4&1+3#0+1/F:content_1/G:0_0/H:6=5@1=1|L-L%/I:0=0/J:6+5-1
> 4300000 4850000 m^ih-d+s=ah@3_1/A:1_0_1/B:1-1-3@1-3&2-5#1-4$1-3!1-1;0-1|ih/

Thank you.

**Comment by ZackHodari** [comment]
It is common for the forced alignment and feature extraction to end up with a different number of frames. If you pass these into merlin I think it will handle a small difference automatically (i.e. it will ignore the next 3 frames).

The alignment file contains start and end time (which are in `milliseconds * 10000`), followed by HTS features, this pdf illustrates the format https://wiki.inf.ed.ac.uk/twiki/pub/CSTR/F0parametrisation/hts_lab_format.pdf
