### ISSUE TITLE
file_id_list.scp is empty

### ISSUE THREAD

**Issue by onratlgn** [CSTR-Edinburgh/merlin#392]
Hi,

I am trying to train another voice by using build_your_own_voice example, I have 60 voice samples which are about 2 minutes, it is a small set to test tool. However in the 

./05_train_duration_model.sh conf/duration_${voice_name}.conf

command, it exits with

Traceback (most recent call last):
  File "/mnt/c/Users/onrat/Documents/IoX-Projects/merlin-tts/merlin/src/run_merlin.py", line 1320, in <module>
    main_function(cfg)
  File "/mnt/c/Users/onrat/Documents/IoX-Projects/merlin-tts/merlin/src/run_merlin.py", line 551, in main_function
    assert cfg.train_file_number+cfg.valid_file_number+cfg.test_file_number == total_file_number, 'check train, valid, test file number'
AssertionError: check train, valid, test file number

for debugging purposes I log the file numbers individually to the promt, it gives

File Numbers:
train:  49
valid:  5
test:   5
total:  0

Then I checked the file_id_list.scp under the folder 
$Merlin\egs\build_your_own_voice\s1\experiments\$voice_name\acoustic_model\data
and it was empty. 

For what reason it might be ?

**Comment by forwiat** [comment]
acoustic_model isn't duration_model,so u should check duration_model\data\...

**Comment by ZackHodari** [comment]
Make sure you have placed your data in `build_your_own_voice/s1/database`, this must include `file_id_list.scp`. After running `01_setup.sh`, `02_prepare_labels.sh`, and `03_prepare_acoustic_features.sh` check that the directories `experiments/${voice_name}/*/data` contain your data.

If they do not contain the `file_id_list.scp` then copy this over manually yourself.

Additionally, I think you need the file numbers to sum to the length of `file_id_list.scp`, so make sure they sum to 60 in your case.
