### ISSUE TITLE
在Merlin合成语音出现问题

### ISSUE THREAD

**Issue by doctor-xiang** [CSTR-Edinburgh/merlin#396]
大家好，我已经安装好Merlin，但是在run ./merlin_synthesis.sh 时出现问题，发现最后合成的是一个空文件。错误提示如下:
1.no such file or directory:'experiments/slt_arctic_demo/test_synthesis/prompt-lab/full/arctic_a0001.lab
2.File"home/guo/merlin/src/frontend/parameter_generation.py",line164,in acoustic_decomposition
   gen_features=mlpg_algo.generation(current_features,var,out_dimension_dict[feature_name]/3]
File"home/guo/merlin/src/frontend/mlpg_fast.py,line 125,in generation var_frames[0,1]=100000000000;
indexError:index 0 is out of  bounds for  axis 0 with size 0
我怎么能解决这个问题，谢谢大家了

**Comment by Jackiexiao** [comment]
use English to describe your question

**Comment by doctor-xiang** [comment]
hello.everyone.i have installed merlin,However,there was a problem when i run ./merlin_synthesis.sh and  found that the last synthesized file was an empty file.The erro message is as follows:
1.gawk:fatal:cannot open file'experiments/slt_arctic_demo/test_synthesis/prompt-lab/tmp' for reading
(no such file or directory)
no such file or directory:'experiments/slt_arctic_demo/test_synthesis/prompt-lab/full/arctic_a0001.lab'
2.File"home/guo/merlin/src/frontend/parameter_generation.py",line164,in acoustic_decomposition
gen_features=mlpg_algo.generation(current_features,var,out_dimension_dict[feature_name]/3]
File"home/guo/merlin/src/frontend/mlpg_fast.py,line 125,in generation var_frames[0,1]=100000000000;
indexError:index 0 is out of bounds for axis 0 with size 0.
How can i solve the problem,thanks!

**Comment by doctor-xiang** [comment]
hi,friend.i have installed merlin,However,there was a problem when i run ./merlin_synthesis.sh and found that the last synthesized file was an empty file.The erro message is as follows:
1.gawk:fatal:cannot open file'experiments/slt_arctic_demo/test_synthesis/prompt-lab/tmp' for reading
(no such file or directory)
no such file or directory:'experiments/slt_arctic_demo/test_synthesis/prompt-lab/full/arctic_a0001.lab'
2.File"home/guo/merlin/src/frontend/parameter_generation.py",line164,in acoustic_decomposition
gen_features=mlpg_algo.generation(current_features,var,out_dimension_dict[feature_name]/3]
File"home/guo/merlin/src/frontend/mlpg_fast.py,line 125,in generation var_frames[0,1]=100000000000;
indexError:index 0 is out of bounds for axis 0 with size 0.
How can i solve the problem,thanks!





在 2018-09-30 11:04:44，"鉴津Jackie" <notifications@github.com> 写道：


use English to describe your question

**Comment by rhoposit** [comment]
looks like an issue with the path that you've set - the path cannot be found and that error is propagated later when the tool looks for those missing files. Check your paths
