### ISSUE TITLE
Tinny bug in misc/scripts/alignment/state_align/forced_alignment.py

### ISSUE THREAD

**Issue by Chaos-XingChao** [CSTR-Edinburgh/merlin#40]
In several using of check_all method,  the HTK path turns to 'HCopy'... 
If you have same problems acting as check_all([‘HCopy’, \* *]), just change the string format to variable format, and you can work well.

**Comment by m-toman** [comment]
Should be fixed with 3332ebbe9c405d8208b3ce70a0b5ff3485d0dc1e
