### ISSUE TITLE
Speaker adaptation - error when synthesising new text using adapted models

### ISSUE THREAD

**Issue by anushaprakash90** [CSTR-Edinburgh/merlin#402]
I am working on speaker adaptation in Merlin using the VCTK data. I had no problems in training the average and adapted voices. The script has a module for synthesising text using the average voice (07_run_merlin.sh), and it worked. But it has no recipe for synthesising text using the adapted voice. I tried using the same script that I use for classic merlin synthesis (with minor modifications) and also a modified version of 07_run_merlin.sh, but I am getting the following error:

IOError: [Errno 2] No such file or directory: '/speech/anusha/Downloads/merlin-master/egs/speaker_adaptation/s1/experiments/adapt_p234/acoustic_model/inter_module/label_norm_HTS_425.dat'

The above mentioned model is not generated during training for the adapted voice, but is generated for the average voice. Is there something that I am missing? Please let me know how to proceed.

Thanks

**Comment by anushaprakash90** [comment]
I was able to solve this issue by changing the last line of run_demo_voice.sh of adaptation (https://github.com/CSTR-Edinburgh/merlin/blob/master/egs/speaker_adaptation/s1/run_demo_voice.sh).

Instead of using duration configuration for acoustic training (./13_adapt_acoustic_model.sh conf/duration_adapt_p234_fine_tune.conf), acoustic configuration was used for acoustic training (./13_adapt_acoustic_model.sh conf/acoustic_adapt_p234_fine_tune.conf).

**Comment by jasonlilley** [comment]
I just discovered this bug too. Someone needs to fix it.

**Comment by jasonlilley** [comment]
Another issue: The synthesis configuration files generated for the adapted models expect the model name "feed_forward_6_tanh", but the generated adapted models have the name "models_adapted_using_fine_tune".

**Comment by RasmusD** [comment]
@jasonlilley if you have a fix, please open a PR with the changes to make this work. That's the fastest and best way to get something fixed on a collaborative project :-)
