### ISSUE TITLE
How to design training data for a model which only needs to synthesis single English words?

### ISSUE THREAD

**Issue by Ziye-Yang** [CSTR-Edinburgh/merlin#404]
Hi all, I'm building my own TTS system which I hope can synthesis both Mandarin and English. Usually the text contains only a few English words such as 'Sorry', 'Micheal Jackson', 'NBA','WIFI' etc, and the rest of it are all Chinese. What I need is to train an English model which is able to clearly pronounce single English words base on the audios recorded by the same speaker to guarantee the consistency. The problem is that this speaker can offer me very limited amount of English audios.
So, What text shall I give her to record? A list of English words? The goal is to provide text with amount of words just enough to cover all English phoneme pronunciation rules. Any suggestion? 
Thanks in advance!

**Comment by ecooper7** [comment]
If you want phonetic balance, the CMU ARCTIC database sentences were put
together for this purpose:
http://www.festvox.org/cmu_arctic/
http://www.festvox.org/cmu_arctic/cmuarctic.data

it's 1132 sentences or about an hour of speech, so maybe others have
recommendations for smaller sets as well.

Best,
Erica

**Comment by ZackHodari** [comment]
If the announcer naturally sounds very similar to slt_arctic then there may be nothing to change.

Otherwise, the most likely reason is accidentally training on the slt_arctic data. Make sure you are certain which data is being used in training model.
