### ISSUE TITLE
Some trouble when using phone-align method

### ISSUE THREAD

**Issue by Chaos-XingChao** [CSTR-Edinburgh/merlin#41]
Hi, 
   When I using phone-align label run train process, I had changed script/setup.sh from state-align to phone-align.
   Do I need change something else? Cause the results are so unacceptable.

**Comment by ronanki** [comment]
Are you using slt demo or your own data?

The [results] (https://github.com/CSTR-Edinburgh/merlin/blob/master/egs/slt_arctic/s1/RESULTS.md) for phone-align are slightly worse than state-align. Having said that, the quality shouldn't defer much. 

Once you alter any variable in global_settings.cfg, you need to recreate all the conf files. Please share the conf files if possible.

**Comment by Chaos-XingChao** [comment]
I just use cmu slt demo and cmu slt full data to run the script.
I've changed the file "merlin/egs/slt_arctic/s1/scripts/setup.sh".
set echo "Labels=phone_align" >> $global_config_file
Then I run the script "merlin/egs/slt_arctic/s1/run_demo.sh" directly. Dose there anything missing?
And I double check my log, the phone-align labels used~
Thanks for replay~

**Comment by Chaos-XingChao** [comment]
Sorry, check down.
When I just change the script, the test labels didn't change.
So I switched my test labels, it's work fine~

**Comment by ronanki** [comment]
okay, I assume you are using run_full_voice.sh rather than run_demo.sh
