### ISSUE TITLE
Input audio files for custom voice

### ISSUE THREAD

**Issue by Enderpman** [CSTR-Edinburgh/merlin#410]
How long should the audio files be?

**Comment by rhoposit** [comment]
if you have perfect outstanding alignments, then the file could be fairly long. However, it is unlikely to have such good alignments, especially on long files. Therefore it's recommended to use utterances. Where each wav file is an utterance, padded with some silence. The length of an utterance depends a bit on the type of data. It could be sentences, but if conversational, then it might work better to use a pause threshold. Take a look at some of the examples in merlin/egs folder to get a sense for the durations.

**Comment by Enderpman** [comment]
It would be beneficial to add this to the documentation.
