### ISSUE TITLE
creation of labels not complete

### ISSUE THREAD

**Issue by rkhyd** [CSTR-Edinburgh/merlin#412]
hello
This is the error i get when i run the step 02.
`forced-alignment using HTK tools...
---preparing enverionment
---checking data
---extracting features
Sun Nov 18 17:20:52 2018
---feature_normalisation
Sun Nov 18 17:20:56 2018
---making proto
Sun Nov 18 17:20:56 2018
---training HMM models
Traceback (most recent call last):
  File "/home/ubuntu/merlin/misc/scripts/alignment/state_align/forced_alignment.py", line 381, in <module>
    aligner.train_hmm(7, 32)
  File "/home/ubuntu/merlin/misc/scripts/alignment/state_align/forced_alignment.py", line 285, in train_hmm
    stdout=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/ubuntu/merlin/tools/bin/htk/HERest', '-C', '/home/ubuntu/merlin/egs/build_your_own_voice/s1/labels/config/cfg', '-S', '/home/ubuntu/merlin/egs/build_your_own_voice/s1/labels/config/train.scp', '-I', '/home/ubuntu/merlin/egs/build_your_own_voice/s1/labels/config/mono_phone.mlf', '-M', '/home/ubuntu/merlin/egs/build_your_own_voice/s1/labels/model/hmm_mix_1_iter_1', '-H', '/home/ubuntu/merlin/egs/build_your_own_voice/s1/labels/model/hmm0/macros', '-H', '/home/ubuntu/merlin/egs/build_your_own_voice/s1/labels/model/hmm0/hmmdefs', '-t', '250.0', '150.0', '2000.0', '/home/ubuntu/merlin/egs/build_your_own_voice/s1/labels/mono_phone.list']' returned non-zero exit status -11
ls: cannot access 'labels/label_state_align': No such file or directory
Force-alignment unsucessful!! Please check /home/ubuntu/merlin/misc/scripts/alignment/state_align/forced_alignment.py
Copying labels to duration and acoustic data directories...
cp: cannot stat 'labels/label_state_align': No such file or directory
cp: cannot stat 'labels/label_state_align': No such file or directory
ls: cannot access 'labels/label_state_align': No such file or directory
ls: cannot access 'labels/label_state_align': No such file or directory
done...!
`
Can any one help me to overcome this issue

**Comment by RasmusD** [comment]
Hi,

the forced alignmetn procedure has failed (line 285 in /home/ubuntu/merlin/misc/scripts/alignment/state_align/forced_alignment.py)

I suggest you run the forced alignment procedure separately to debug the issue.

- Rasmus
