### ISSUE TITLE
GPU problem 

### ISSUE THREAD

**Issue by 106368031HuangBaiHong** [CSTR-Edinburgh/merlin#414]
I am runing vcc2016  when it Running on GPU.
It shows that ERROR (theano.gpuarray): pygpu was configured but could not be imported or is too old (version 0.7 or higher required)

I search how to insatll pygpu. I try all the solution but still can't successful installation.
 When I import it show

 >>> import pygpu
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pygpu/__init__.py", line 7, in <module>
    from . import gpuarray, elemwise, reduction
  File "pygpu/elemwise.py", line 3, in <module>
    from .dtypes import dtype_to_ctype, get_common_dtype
  File "pygpu/dtypes.py", line 6, in <module>
    from . import gpuarray
ImportError: cannot import name gpuarray
>>> import gpuarray
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named gpuarray

Does anyone have the same moral problem with me?

**Comment by rhoposit** [comment]
I've found that using anaconda and their environment feature is really helpful for setting up the right versions and dependencies. You can also test the import using a simple python script before running with Merlin.

**Comment by jiayalu123** [comment]
请问您得问题解决了么，我也遇到了同样得问题
