### ISSUE TITLE
TTS database

### ISSUE THREAD

**Issue by rezame** [CSTR-Edinburgh/merlin#419]
Hi
I'm new in TTS.
I want to implement a tts for Farsi (Persian)
language.
Is it possible to describe, properties of the TTS dataset?
I have dataset of speech recognition with 200 speakers and about 100 hours. Is it good dataset for TTS ?
I think that can train model with that dataset and adapt on a one speaker, how many hours for adaptation?
best regards

**Comment by pasindud** [comment]
Typically TTS Systems require clean audio for training as opposed to noises audio that ASR requires.
