### ISSUE TITLE
Mismatch mgc order between Label alignment and Deep Recurrent Training

### ISSUE THREAD

**Issue by Chaos-XingChao** [CSTR-Edinburgh/merlin#42]
Hi, guys, 
  I successfully run the slt_demo and slt_full experiments, and now I want to migrate it from English to Mandarin. 
  Based on our old HTS version, I get the forced aligned label using mgc order = 34, and I run merlin parameters as default. 
  But the results quit strange, some phone sounds nice, most phone doesn't work well.
  Do I must set mgc order same between get aligned label and train merlin model?

**Comment by ronanki** [comment]
mgc order 34 is quite strange, as I heard 40 and 60 before. Can you please let us know how did you extract the vocoder parameters?

**Comment by Chaos-XingChao** [comment]
In HTS,  just use SPTK to extract features, MGCEP for mgc, PITCH for lf0, it's all same in HTS's basic parameter extract.
I followed the demo's makefile steps without vocoder to extract features.
In merlin, I use world extract parameters.

**Comment by ronanki** [comment]
So, you have state_align labels from HTS and vocoder parameters extracted from WORLD. That's fine.

May I know the sampling frequency of the data you used. Also, can you share your conf/global_settings.cfg and acoustic_config file.
