### ISSUE TITLE
error installing speech tools (./compile_other_speech_tools.sh)

### ISSUE THREAD

**Issue by yyf** [CSTR-Edinburgh/merlin#427]
Hi,
I was trying to run ./compile_other_speech_tools.sh on Ubuntu 18.04.1, but got "error installing speech tools". Here are my steps:

1. added txt folder under .../test_synthesis/
2. added a text file to the txt folder
3. ran prepare_labels_from_txt.sh
4. ran merlin_synthesis.sh (error... festival path not specified)
5. tried to run compile_other_speech_tools.sh to install festival under merlin dir
6. forced gcc to 4.8 (#255 )
7. ran compile_other_speech_tools.sh again, but still got the following error log: "<builtin> recipe for target 'edvc_3.o' failed ... Error installing speech tools"

Wondering if there is any other tip to resolve this? Thanks.

**Comment by RasmusD** [comment]
The error tells you what is wrong. Speech tools didn't compile properly and it is the edvc_3.o which failed to built.

If you look in the compile_other_speech_tools.sh scripts line 143-145 you see the check which outputs that speech tools is not compiled properly. I'd recommend running the block from line 17 to 38 separately and debug why the compilation of speech_tools fails.

**Comment by yyf** [comment]
Thanks. I went through the log again and here are a few more errors:

../include/defs.h:83:14: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]

FeatureExtracion.cc:243:13: error: no match for 'operator==' (operand types are 'std::if stream {aka std::bassic_ifstream<char>}' and 'int')

FeatureExtraction.cc:831:13: error: no match for 'operator==' (operand types are 'std::if stream {aka std::bassic_ifstream<char>}' and 'int')

header.h:56:15: error: no match for 'operator==' (operand types are 'std::if stream {aka std::bassic_ifstream<char>}' and 'int')

edec_v3.cc:345:14: error: no match for 'operator==' (operand types are 'std::if stream {aka std::bassic_ifstream<char>}' and 'int')

Compiler related issue? I'm currently using gcc 4.8 based on suggestions from #255

**Comment by yyf** [comment]
This was resolved by uncommenting this line in the compile_other_speech_tools.sh: 
# sudo apt-get -y install libncurses5 libncurses5-dev libcurses-ocaml # for sudo users only 

Now I got the same IndexError originally reported in #255 when trying to generate a new sentence by running ./merlin_synthesis. 

Thanks.

**Comment by ghost** [comment]
Hi,
same index error occurred during merlin synthesis even after doing that! and make test is also failed in festival. could someone help me.
Thanks,
Bharath.
