### ISSUE TITLE
Implementing a new recipe

### ISSUE THREAD

**Issue by rmmal** [CSTR-Edinburgh/merlin#43]
What are the modifications needed to be able to implement LSTM as an example ?

**Comment by ronanki** [comment]
hidden_layer_type  : ['TANH', 'TANH', 'TANH', 'TANH', 'TANH', 'TANH']
#if RNN or sequential training is used, please set sequential_training to True.
sequential_training : False
--------------------------------------------------------------------------
1. You need to change hidden_layer_type as shown below:
hidden_layer_type  : ['LSTM', 'LSTM']
hidden_layer_type  : ['RNN', 'RNN']
hidden_layer_type  : ['RNN', 'RNN', 'LSTM', 'BLSTM']
hidden_layer_type  : ['TANH', 'TANH', 'LSTM', 'GRU']
hidden_layer_type  : ['TANH', 'TANH', 'SIGMOID', 'SIGMOID', 'SLSTM', 'BSLSTM'] 
(SLSTM is simplified LSTM for fast-training)

2. You need to set the variable sequential_training to True
sequential_training : True

**Comment by rmmal** [comment]
Okay Thanks ronanki , i will try it now.

**Comment by ikhfa** [comment]
Are there any explanation in how to decide the number of layers and nodes?

**Comment by ronanki** [comment]
No -- you can experiment with them.
