### ISSUE TITLE
How to train Merlin using LJ Speech dataset

### ISSUE THREAD

**Issue by yyf** [CSTR-Edinburgh/merlin#432]
In addition to the default slt_arctic_demo_data and slt_arctic_full_data, wondering what are the recommended processes and database spec/format to train Merlin using other public available datasets, such as the LJ Speech Dataset? Did a quick search online and the git issues, but haven't seen any writeup or tutorial on this topic. Would be good to have some pointers as part of the README for build_your_own_voice case. Thanks.

**Comment by yyf** [comment]
I downsampled the 13100 files from the dataset to 16kHz, and set number of files in global_settings.cfg based on the suggestion in #203, i.e. 
Train=11790
Valid=655
Test=655

I was able to finish ./04_prepare_conf_files.sh, but got below error when running ./05_train_duration_model.sh: 

AssertionError: check train, valid, test file number

Then, I check the number of files in the duration_model/data/file_id_list.scp, but there is only 2098 entries there. Is there additional config required to train on a larger dataset/the LJSpeech dataset?

**Comment by pasindud** [comment]
You should be able to still train with those files by changing the ratios assuming all the features are extracted.

For the first question on data sets.
You can find few datasets here [1], merlin recipes can be found here [2]

1 - https://github.com/google/voice-builder/blob/master/DataSets.md
2 - https://github.com/googlei18n/language-resources/tree/master/bn/merlin

**Comment by yyf** [comment]
Thanks for the links @pasindud 

Still not sure why there is only 2098 entries in my file_id_list.scp, but I was able to finish ./05_train_duration_model.sh and ./06_train_acoustic_model.sh after replacing the force_alignment_parallel file(#293 ) and updating global_settings.cfg:

Train=2058
Valid=20
Test=20

This is probably not the right way to resolve this?

Then, I got the same error reported in #352 when running ./07_run_merlin.sh experiments/LJ_db_16k/test_synthesis/txt conf/test_dur_synth_LJ_db_16k.conf conf/test_synth_LJ_db_16k.conf

`
...
gawk: fatal: cannot open file experimental/LJ_db_16k/test_synthesis/prompt-lab/tmp for reading (No such file or directory)
...
Traceback (most recent call last):
  File "/home/ubuntu/Code/merlin/src/run_merlin.py", line 1320, in <module>
    main_function(cfg)
  File "/home/ubuntu/Code/merlin/src/run_merlin.py", line 971, in main_function
    generator.acoustic_decomposition(gen_file_list, cfg.cmp_dim, cfg.out_dimension_dict, cfg.file_extension_dict, var_file_dict, do_MLPG=cfg.do_MLPG, cfg=cfg)
  File "/home/ubuntu/Code/merlin/src/frontend/parameter_generation.py", line 164, in acoustic_decomposition
    gen_features = mlpg_algo.generation(current_features, var, out_dimension_dict[feature_name]//3)
  File "/home/ubuntu/Code/merlin/src/frontend/mlpg_fast.py", line 122, in generation
    var_frames[0, 1] = 100000000000;
IndexError: index 0 is out of bounds for axis 0 with size 0`

To debug, I double checked gawk is installed and also manually install festvox-kallpc16k, but these didn't help. Not sure if this is related to gcc version (#255) or some hardcoded line in dumpfeat in festival (#409)?

**Comment by dreamk73** [comment]
You could create your own file_id_list.scp file with as many filenames as you need? I don't understand why this is a problem?

**Comment by yyf** [comment]
@dreamk73 
There are 13100 files in ./LJ_db_16k/labels/file_id_list.scp, but only 2098 in these two files (./experiments/LJ_db_16k/duration_model/data/file_id_list.scp, ./experiments/LJ_db_16k/acoustic_model/data/file_id_list.scp). Does this seem right?

**Comment by dreamk73** [comment]
Why don't you create a new filelist with all 13100 files in it? You can replace the file_id_list.scp file and put in as many files as you want to use.

**Comment by yyf** [comment]
After replacing both file_id_list.scp files under duration_model and acoustic_model folders, I'm still getting this error: IOError: [Errno 2] No such file or directory: '/.../.../.../merlin_conda_test/merlin/egs/build_your_own_voice/s1/experiments/LJ_16k/duration_model/data/label_state_align/LJ001-0001.lab'

This is after ./02_prepare_labels.sh was completed without error. Not sure why?

**Comment by yyf** [comment]
I then used the first 60 wav files from the LJ dataset for training and found out label for file 55 is always missing after running ./02_prepare_labels.sh. Is this is a known issue to folks who had luck training merlin using the LJ dataset?

**Comment by yyf** [comment]
Resolved by properly reformatting the transcription file.

**Comment by fxwderrick** [comment]
@yyf Hi, just curious, have you finished training on LJ-speech? If so, how is the quality?
