### ISSUE TITLE
Train dataset

### ISSUE THREAD

**Issue by lalimili6** [CSTR-Edinburgh/merlin#433]
Hi
thanks
I used Kaldi to segment audiobook and alignment phones, now I have wave and text and phone alignment.
1- my dataset contains 15 hours waves and 3500 waves with text transcripts and phone alignments. It means waves are about 15 seconds in length. is it good? or segments them? (dataset growing up to 30 hours)
1-1- and my dataset doesn't have any stress,... labels. does it achieve good results or must label these?
2- Is it possible to describe how can use this toolkit?

**Comment by dreamk73** [comment]
1 sounds ok
2 You will get much better results if you have stress included. You need to use Festival or another toolkit to analyze your text to get pronunciations with stress.

**Comment by lalimili6** [comment]
thanks
I can't change my phone alignment to format that Merlin need. how can change them?
thanks

**Comment by KunalDhawan** [comment]
Hi @lalimili6 
Could you please share if you were able to convert Kaldi alignments to merlin format? If yes, could you kindly share any relevant resources which helped you in doing so.

**Comment by lalimili6** [comment]
@KunalDhawan 
Oh, sorry, I cant use Kaldi alignments.
maybe you can use link below.
If you do it, please share with me!!!
http://jrmeyer.github.io/tts/2017/02/14/Installing-Merlin.html

**Comment by KunalDhawan** [comment]
@lalimili6 Thank you for the quick response.
I'll surely post it here when I am able to solve this problem.
