### ISSUE TITLE
nick_hurricane_full: downloaded data file requires password

### ISSUE THREAD

**Issue by entn-at** [CSTR-Edinburgh/merlin#44]
Hi,
when trying to run the setup script associated with egs/nick_hurricane/s1/ for the full voice ("./01_setup.sh nick_hurricane_full") I am being asked for a password which is set on the downloaded data file ("nick_hurricane_full_data.zip"). 

Is this intentional and the data is not publicly available? I did not find any information in the README.md files in the egs/nick_hurricane/ and s1/ folders.

Thanks

**Comment by ronanki** [comment]
The data is not publicly available as it includes features extracted from STRAIGHT and labels using Combilex phoneset (both of them have restricted usage). 

Therefore, the scripts are meant for internal purpose and also for those who have license to both. 

The scripts and README are hastily prepared -- will update README soon with this information.

**Comment by entn-at** [comment]
Thanks for the clarification ronanki!
