### ISSUE TITLE
Paper references?

### ISSUE THREAD

**Issue by mrgloom** [CSTR-Edinburgh/merlin#441]
Is it all available information about algorithms used in merlin?
https://isca-speech.org/archive/SSW_2016/pdfs/ssw9_DS-3_Ronanki.pdf

**Comment by ZackHodari** [comment]
This Interspeech tutorial provides a good amount of information.
http://www.speech.zone/courses/one-off/merlin-interspeech2017/

Otherwise there is no official documentation about what is implemented in Merlin.
