### ISSUE TITLE
Is pretrained model availible?

### ISSUE THREAD

**Issue by mrgloom** [CSTR-Edinburgh/merlin#443]
Is pretrained model availible to test text to speech functionality?

**Comment by ZackHodari** [comment]
Not as far as I am aware, there are recipes that can be followed to train a voice and then synthesis from it within Merlin, e.g. https://github.com/CSTR-Edinburgh/merlin/tree/master/egs/fls_blizzard2017/s1

Or there are other repo's that have trained models available for download, but these are unrelated to Merlin, e.g. https://colab.research.google.com/github/r9y9/Colaboratory/blob/master/Tacotron2_and_WaveNet_text_to_speech_demo.ipynb
