### ISSUE TITLE
AssertionError while running merlin/egs/build_your_own_voice/s1/run_demo_voice.sh 

### ISSUE THREAD

**Issue by kevinmchu** [CSTR-Edinburgh/merlin#461]
I'm trying to run the demo for the 'build your own voice' recipe, but I'm getting this AssertionError:

```
Traceback (most recent call last):
  File "/home/xxxxxx/merlin/src/run_merlin.py", line 1320, in <module>
    main_function(cfg)
  File "/home/xxxxxx/merlin/src/run_merlin.py", line 551, in main_function
    assert cfg.train_file_number+cfg.valid_file_number+cfg.test_file_number == total_file_number, 'check train, valid, test file number'
AssertionError: check train, valid, test file number
```

The global_settings.cfg file defines the size of the subsets as

Train=50
Valid=5
Test=5

What am I doing wrong?

**Comment by dreamk73** [comment]
How many files are in your file_id_list.scp? That has to match your train+valid+test. 

Esther

**Comment by kevinmchu** [comment]
I'm not actually creating the scp or subsets myself; instead, I'm running the demo code which should create the necessary files. For some reason, file_id_list.scp only contains 53 out of the 60 files it should contain. Here is a partial list:

arctic_a0003
arctic_a0004
arctic_a0005
arctic_a0006
arctic_a0007
arctic_a0008
arctic_a0009
arctic_a0010
arctic_a0011
arctic_a0012
arctic_a0013
arctic_a0014
arctic_a0015
arctic_a0019
arctic_a0020
arctic_a0021
arctic_a0022
arctic_a0024
arctic_a0026
arctic_a0027

The only way I can think of to fix the problem is to manually recreate file_id_list.scp. Is there a better way of fixing this file that uses code instead of manual recreation?

**Comment by seblemaguer** [comment]
I suggest more to try to understand why you have only 53 files instead of 60. If you really want to proceed without being sure, I would modify thye number of `train`, `valid` and `test` to sum to 53

**Comment by kevinmchu** [comment]
According to #250, the files missing from file_id_list.scp have missing alignments. The reason the alignments are missing has to do with the pruning beam width in forced_alignment.py. The default values are given as `PRUNING = [str(i) for i in (250., 150., 2000.)]`. Is there a suggested set of parameters to use for the PRUNING variable to reduce the potential for missing alignment?

**Comment by ndwuhuangwei** [comment]
hey, @kevinmchu  I've met the same problem when trainning duration model, you close this issue , does it mean you know how to deal with this problem now? could you  teach me how to set the values?
