### ISSUE TITLE
Features used for SLT Arctic

### ISSUE THREAD

**Issue by kevinmchu** [CSTR-Edinburgh/merlin#462]
How many features are used for the SLT Arctic recipe? In RESULTS.md, I see lines such as 

`Labels: state_align; Network: [416->5] LR 0.002 [4 TANH] [4*512]; <br/>`

for the duration model and

`Labels: state_align; Network: [425->187], LR 0.002 [4 TANH] [4*512]; <br/>`

for the acoustic model. 

However, in the paper _Merlin: An Open Source Neural Network Speech Synthesis System_, there is a line that says 491 input features were used for all neural networks. What is the correct number of features?

**Comment by dreamk73** [comment]
It depends on the question file you use and how many features are in there. There are always 9 more acoustic features than duration features for the same question file. If you run the model training, you can see in the inter_module directory in the directory names how many features are used.

**Comment by kevinmchu** [comment]
I am using questions-radio_dnn_416.hed, which I understand contains 416 features. I am also using the 9 subphone features, which explains 425 features in the acoustic model. Where are the remaining 66 features? Are they not used?

**Comment by dreamk73** [comment]
No, those are the features that are used.

**Comment by kevinmchu** [comment]
Just to clarify, only 416/425 features are used?

**Comment by dreamk73** [comment]
Yes

**Comment by kevinmchu** [comment]
Thank you for the clarification.

On an unrelated note, I am trying to train a model using only the QS features in the .hed file. I created a new .hed file that is similar to questions-radio_dnn_416.hed but does not contain the CQS features. I also modified the configuration files to point to the new questions file. However, when I tried this I received an error.

```
Traceback (most recent call last):
  File "/home/xxxxxx/merlin/src/run_merlin.py", line 1320, in <module>
    main_function(cfg)
  File "/home/xxxxxx/merlin/src/run_merlin.py", line 672, in main_function
    label_normaliser.prepare_dur_data(in_label_align_file_list, file_paths.dur_file_list, cfg.label_type, cfg.dur_feature_type)
  File "/home/xxxxxx/merlin/src/frontend/label_normalisation.py", line 148, in prepare_dur_data
    self.extract_dur_features(ori_file_list[i], output_file_list[i], label_type, feature_type, unit_size, feat_size)
  File "/home/xxxxxx/merlin/src/frontend/label_normalisation.py", line 155, in extract_dur_features
    A = self.extract_dur_from_state_alignment_labels(in_file_name, feature_type, unit_size, feat_size)
  File "/home/xxxxxx/merlin/src/frontend/label_normalisation.py", line 228, in extract_dur_from_state_alignment_labels
    if(label_continuous_vector[0, 1]==1 or current_phone in list_of_silences): ##pos-bw and c-silences
IndexError: index 1 is out of bounds for axis 1 with size 0
```

I looked through the code, and it seems like it requires continuous/CQS features to compute the durations. 

**My questions**: Can the model be trained without using CQS features? If so, what do I need to do to get the code to ignore the continuous features?
