### ISSUE TITLE
Modifying CQS Questions

### ISSUE THREAD

**Issue by kevinmchu** [CSTR-Edinburgh/merlin#467]
I am trying to train the SLT Arctic model using only the QS questions. I created a new questions file by removing the CQS questions from questions-radio_dnn_416.hed, and I modified the configuration files to point to the new questions file. However, when I tried running the demo, I received an error.

```
Traceback (most recent call last):
  File "/home/xxxxxx/merlin/src/run_merlin.py", line 1320, in <module>
    main_function(cfg)
  File "/home/xxxxxx/merlin/src/run_merlin.py", line 672, in main_function
    label_normaliser.prepare_dur_data(in_label_align_file_list, file_paths.dur_file_list, cfg.label_type, cfg.dur_feature_type)
  File "/home/xxxxxx/merlin/src/frontend/label_normalisation.py", line 148, in prepare_dur_data
    self.extract_dur_features(ori_file_list[i], output_file_list[i], label_type, feature_type, unit_size, feat_size)
  File "/home/xxxxxx/merlin/src/frontend/label_normalisation.py", line 155, in extract_dur_features
    A = self.extract_dur_from_state_alignment_labels(in_file_name, feature_type, unit_size, feat_size)
  File "/home/xxxxxx/merlin/src/frontend/label_normalisation.py", line 228, in extract_dur_from_state_alignment_labels
    if(label_continuous_vector[0, 1]==1 or current_phone in list_of_silences): ##pos-bw and c-silences
IndexError: index 1 is out of bounds for axis 1 with size 0
```

Looking through the code, it seems that the CQS questions are needed to compute the state durations. 

**My questions**: 
1) Can the model be trained without using CQS questions? 
2) If so, what modifications do I need to make to ignore the CQS questions?
3) If not, can I train the model using only a subset of CQS questions?

**Comment by RasmusD** [comment]
1. Yes. Though I'm not sure why you want to our why you think that'd improve results. 
2. That line which fails seems to check if you're at the beginning of the utterance through the pos-bw feature added for state or phone level positional information. Did you disable those features as well? If not, then this would be a bug. 
3. Yes.

**Comment by kevinmchu** [comment]
Yes, I am ignoring all CQS questions. To clarify, in 2 are you saying that there's a bug in the way the code is written? Or are you saying that it's not possible to run the code without CQS?

**Comment by kevinmchu** [comment]
In the code

```
### syllable ending information ###
syl_end = 0        
if(label_continuous_vector[0, 1]==1 or current_phone in list_of_silences): ##pos-bw and c-silences
     syl_end = 1

### word ending information ###
word_end = 0        
if(syl_end and label_continuous_vector[0, 9]==1 or current_phone in list_of_silences):
      word_end = 1
```

I see that the CQS questions are needed. If I revise the if statements to be

```
### syllable ending information ###
syl_end = 0        
if(current_phone in list_of_silences): ##pos-bw and c-silences
     syl_end = 1

### word ending information ###
word_end = 0        
if(current_phone in list_of_silences):
      word_end = 1
```

would I be able to run the code without CQS questions?

**Comment by RasmusD** [comment]
CQS and QS simply mean a continous valued question (CQS) and a binary question (QS).
The positional question it is looking for for the AC model is the position in the phone from the forced alignment. That is the subphone_feats. These are not specified in the question file. So if you've only modified the question file and removed all CQS from there then it is weird why they're missing as they're added in the code and not through the question file. That's why I suspect a bug.
This is also why it is the acoustic model that fails and not the duration model because these features are, at run-time, generated from the duration model predictions.

> would I be able to run the code without CQS questions?

Why don't you try? I suspect there'll be some other issue somewhere, but give it a go.

**Comment by kevinmchu** [comment]
If I understand correctly, the positional question should reference the subphone features instead of the question file to determine whether the end of the word/syllable has been reached. However, when I read through the code, it looks like the question file is used.

label_continuous_vector is defined as:
`
label_continuous_vector = self.pattern_matching_continous_position(full_label)
`

Looking through the function `pattern_matching_continous_position`, I see that lab_continuous_vector is defined by with respect to the dictionary continuous_dict.

```
    def pattern_matching_continous_position(self, label):

        dict_size = len(self.continuous_dict)

        lab_continuous_vector = numpy.zeros((1, dict_size))

        for i in range(dict_size):
            continuous_value = -1.0

            current_compiled = self.continuous_dict[str(i)]

            ms = current_compiled.search(label)
            if ms is not None:
#                assert len(ms.group()) == 1
                continuous_value = ms.group(1)

            lab_continuous_vector[0, i] = continuous_value

        return  lab_continuous_vector
```

After searching a bit more, I see that continuous_dict is defined in the `load_question_set_continous` function. It looks like the code uses the question file to generate continuous_dict.
```

    def load_question_set_continous(self, qs_file_name):

        logger = logging.getLogger("labels")

        fid = open(qs_file_name)
        binary_qs_index = 0
        continuous_qs_index = 0
        binary_dict = {}
        continuous_dict = {}
        LL=re.compile(re.escape('LL-'))
        LAST_QUESTION = re.compile(re.escape('(\d+)') + '$') # regex for last question

        for line in fid.readlines():
            line = line.replace('\n', '').replace('\t', ' ')

            if len(line) > 5:
                temp_list = line.split('{')
                temp_line = temp_list[1]
                temp_list = temp_line.split('}')
                temp_line = temp_list[0]
                temp_line = temp_line.strip()
                question_list = temp_line.split(',')

                temp_list = line.split(' ')
                question_key = temp_list[1]
#                print   line
                if temp_list[0] == 'CQS':
                    assert len(question_list) == 1
                    processed_question = self.wildcards2regex(question_list[0], convert_number_pattern=True)
                    if LAST_QUESTION.search(question_list[0]):
                        processed_question = processed_question + '$' # last question must only match at end of HTS label string
                    continuous_dict[str(continuous_qs_index)] = re.compile(processed_question) #save pre-compiled regular expression
                    continuous_qs_index = continuous_qs_index + 1
                elif temp_list[0] == 'QS':
                    re_list = []
                    for temp_question in question_list:
                        processed_question = self.wildcards2regex(temp_question)
                        if LL.search(question_key):
                            processed_question = '^'+processed_question
                        re_list.append(re.compile(processed_question))

                    binary_dict[str(binary_qs_index)] = re_list
                    binary_qs_index = binary_qs_index + 1
                else:
                    logger.critical('The question set is not defined correctly: %s' %(line))
                    raise Exception

#                question_index = question_index + 1
        return  binary_dict, continuous_dict
```
**Is this a bug in the code?**

**Comment by dreamk73** [comment]
I guess I don't understand why you would want to get rid of all CQS questions in the first place? Both for duration and for the acoustics I believe it is important to give information about where in the utterance a phoneme is and how long the utterance is etc?

**Comment by kevinmchu** [comment]
I suppose I don't need to get rid of all CQS questions, just some of them. I am using a speech synthesizer for an application that requires all the features to be causal, which would preclude features such as position of a phoneme in an utterance and length of the utterance. However, I would be able to use features based on information from past and current frames such as the number of words preceding the current word.
