### ISSUE TITLE
Adding new features such as waves in time domain ?

### ISSUE THREAD

**Issue by m7md7sien** [CSTR-Edinburgh/merlin#47]
can i use merlin to train neural networks with different kind of features, i want to use the waves it self as a features, can this be done ?
thank you in advanced.

**Comment by m-toman** [comment]
Hi, 
you could probably look into this: https://github.com/ibab/tensorflow-wavenet (or one of the other implementations of https://deepmind.com/blog/wavenet-generative-model-raw-audio/).

**Comment by m7md7sien** [comment]
thank you :)
