### ISSUE TITLE
Label-Files contain gibberish after merlin_synthesis

### ISSUE THREAD

**Issue by erbsenzaehla** [CSTR-Edinburgh/merlin#474]
After running merlin_synthesis.sh without errors using the full arctic voice, the wav-file only contains noise. The problem appears to be the label files which look like this:
`0 440000 x^x-sil+hh=ax@x_x/A:0_0_0/B:x-x-x@x-x&x-x#x-x$x-x!x-x;x-x|x/C:0+0+2/D:0_0/E:x+x@x+x&x+x#x+x/F:content_2/G:0_0/H:x=x@1=1|0/I:11=8/J:11+8-1[2]`
`440000 880000 x^x-sil+hh=ax@x_x/A:0_0_0/B:x-x-x@x-x&x-x#x-x$x-x!x-x;x-x|x/C:0+0+2/D:0_0/E:x+x@x+x&x+x#x+x/F:content_2/G:0_0/H:x=x@1=1|0/I:11=8/J:11+8-1[3]`
`880000 1320000 x^x-sil+hh=ax@x_x/A:0_0_0/B:x-x-x@x-x&x-x#x-x$x-x!x-x;x-x|x/C:0+0+2/D:0_0/E:x+x@x+x&x+x#x+x/F:content_2/G:0_0/H:x=x@1=1|0/I:11=8/J:11+8-1[4]`
`1320000 1760000 x^x-sil+hh=ax@x_x/A:0_0_0/B:x-x-x@x-x&x-x#x-x$x-x!x-x;x-x|x/C:0+0+2/D:0_0/E:x+x@x+x&x+x#x+x/F:content_2/G:0_0/H:x=x@1=1|0/I:11=8/J:11+8-1[5]`
`1760000 2200000 x^x-sil+hh=ax@x_x/A:0_0_0/B:x-x-x@x-x&x-x#x-x$x-x!x-x;x-x|x/C:0+0+2/D:0_0/E:x+x@x+x&x+x#x+x/F:content_2/G:0_0/H:x=x@1=1|0/I:11=8/J:11+8-1[6]`
`2200000 2300000 x^sil-hh+ax=l@1_2/A:0_0_0/B:0-0-2@1-2&1-11#1-8$1-6!0-1;0-1|ax/C:1+1+2/D:0_0/E:content+2@1+8&1+4#0+1/F:content_1/G:0_0/H:11=8@1=1|L-L%/I:0=0/J:11+8-1[2]`
...

The corresponding sentence is "Hello, I am the arctic voice of Merlin."
Thanks for your help!

**Comment by RasmusD** [comment]
Those label files look good to me. What do you think is wrong with them?

**Comment by erbsenzaehla** [comment]
I thought they had to look as "clean" as the training label files...

**Comment by RasmusD** [comment]
And how does your training label files look? Are you sure you're not confusing alignment label files and actual training labels? If they didn't contain the above "gibberish" then that's probably why it doesn't work.

**Comment by erbsenzaehla** [comment]
I used the stl_arctic example with .lab files looking like
`0.205 125 sil`
`0.34 125 ao`
etc.
If it isn't the label files that are wrong, what else could cause the wav-files only containing noise?
No errors showed up during installation, training or synthesis. What files or logs should I provide?

**Comment by RasmusD** [comment]
So those you write there are monophone label files which can work for alignment.
If you've used those for training then that explains why you get a voice that sounds like nothing.
You need the full-context label files (those with "gibberish" in them you initially posted) for training and synthesis.
