### ISSUE TITLE
import theano

### ISSUE THREAD

**Issue by ghost** [CSTR-Edinburgh/merlin#476]
I get theano import error when i try to run the sample given in s1 of merlin. When i try to to reinstall theano it says rquirement already satisfied.

  File "/home/fjwu/merlin-master/src/run_merlin.py", line 56, in <module>
    import theano
ImportError: No module named theano

**Comment by seblemaguer** [comment]
are you sure that merlin is using the same python than you are for testing?

**Comment by ghost** [comment]
Resolved. thats was the issue. i was using  a different version for installations. thankyou
