### ISSUE TITLE
file_id_list_full 

### ISSUE THREAD

**Issue by ghost** [CSTR-Edinburgh/merlin#483]
I was able to run the first voice demo on merlin. 
While running the **full voice demo**, there is a file missing **"file_id_list_full.scp"**
I cannot seem to find it anywhere.

**Comment by seblemaguer** [comment]
According to the setup file: https://github.com/CSTR-Edinburgh/merlin/blob/33fa6e65ddb903ed5633ccb66c74d3e7c128667f/egs/slt_arctic/s1/01_setup.sh#L107

`file_id_list_full.scp` is related to the building of the full voice, not the demo

**Comment by saharsyed** [comment]
full voice was what I wanted to run. The issue was resolved though by some relocation of files.thankyou

**Comment by ghost** [comment]
full voice was what I wanted to run. The issue was resolved though by some relocation of files.thankyou

**Comment by Aliraheem** [comment]
I have the same issue. please how did you solve it?
