### ISSUE TITLE
fail to compile postfilter

### ISSUE THREAD

**Issue by ndwuhuangwei** [CSTR-Edinburgh/merlin#487]
compiling postfilter...
./00_make.sh: 5: ./00_make.sh: aclocal: not found
./00_make.sh: 6: ./00_make.sh: automake: not found
./00_make.sh: 7: ./00_make.sh: autoconf: not found
./00_make.sh: 8: ./00_make.sh: ./configure: not found
make: *** No rule to make target 'clean'.  Stop.
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.

why, what could I do to fix it

**Comment by Yogatiara** [comment]
please solution? @ndwuhuangwei
