### ISSUE TITLE
02_prepare_labels_from_txt - malloc() corrupted top size

### ISSUE THREAD

**Issue by gaspardol** [CSTR-Edinburgh/merlin#493]
Hi all I'm trying to make labels from the data in speaker adaptation and I am running into the following error:

Step 2:
Preparing labels...
preparing full-contextual labels using Festival frontend...
creating a scheme file from text directory
generating utts from scheme file
malloc(): corrupted top size
/mnt/c/Users/Bonjour/Documents/GitHub/merlin/egs/speaker_adaptation/s1/scripts/prepare_labels_from_txt.sh: line 53:    12 Aborted                 (core dumped) ${FESTDIR}/bin/festival -b ${out_dir}/$scheme_file
converting festival utts to labels...
01_setup.sh 02_prepare_labels.sh 03_prepare_acoustic_features.sh 04_prepare_conf_files.sh 05_train_duration_model.sh 06_train_acoustic_model.sh 07_run_merlin.sh 08_setup_adapt.sh 09_prepare_labels_adapt.sh 10_prepare_acoustic_features.sh 11_prepare_conf_files_adapt.sh 12_adapt_duration_model.sh 13_adapt_acoustic_model.sh conf database download_data.sh experiments README.md RESULTS.md run_demo_voice.sh scripts VCTK-Corpus VCTK-Corpus.tar.gz
gawk: fatal: cannot open file `database/labels/prompt-lab/tmp' for reading (No such file or directory)
gawk: fatal: cannot open file `database/labels/prompt-lab/tmp' for reading (No such file or directory)
normalizing label files for merlin...
p225_001.lab
Traceback (most recent call last):
  File "/mnt/c/Users/Bonjour/Documents/GitHub/merlin/misc/scripts/frontend/utils/normalize_lab_for_merlin.py", line 134, in <module>
    normalize_label_files(in_lab_file, out_lab_file, label_style, write_time_stamps)
  File "/mnt/c/Users/Bonjour/Documents/GitHub/merlin/misc/scripts/frontend/utils/normalize_lab_for_merlin.py", line 35, in normalize_label_files
    in_f = open(in_lab_file,'r')
IOError: [Errno 2] No such file or directory: 'database/labels/prompt-lab/full/p225_001.lab'
forced-alignment using HTK tools...
---preparing enverionment
---checking data
---extracting features
Tue Dec  3 21:39:45 2019
---feature_normalisation
Tue Dec  3 21:39:45 2019
---making proto
Tue Dec  3 21:39:45 2019
---training HMM models
  ERROR [+7220]  NewHMMScan: cannot find any physical HMMs to scan
 FATAL ERROR - Terminating program /mnt/c/Users/Bonjour/Documents/GitHub/merlin/tools/bin/htk/HERest
Traceback (most recent call last):
  File "/mnt/c/Users/Bonjour/Documents/GitHub/merlin/misc/scripts/alignment/state_align/forced_alignment.py", line 381, in <module>
    aligner.train_hmm(7, 32)
  File "/mnt/c/Users/Bonjour/Documents/GitHub/merlin/misc/scripts/alignment/state_align/forced_alignment.py", line 285, in train_hmm
    stdout=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/mnt/c/Users/Bonjour/Documents/GitHub/merlin/tools/bin/htk/HERest', '-C', '/mnt/c/Users/Bonjour/Documents/GitHub/merlin/egs/speaker_adaptation/s1/database/labels/config/cfg', '-S', '/mnt/c/Users/Bonjour/Documents/GitHub/merlin/egs/speaker_adaptation/s1/database/labels/config/train.scp', '-I', '/mnt/c/Users/Bonjour/Documents/GitHub/merlin/egs/speaker_adaptation/s1/database/labels/config/mono_phone.mlf', '-M', '/mnt/c/Users/Bonjour/Documents/GitHub/merlin/egs/speaker_adaptation/s1/database/labels/model/hmm_mix_1_iter_1', '-H', '/mnt/c/Users/Bonjour/Documents/GitHub/merlin/egs/speaker_adaptation/s1/database/labels/model/hmm0/macros', '-H', '/mnt/c/Users/Bonjour/Documents/GitHub/merlin/egs/speaker_adaptation/s1/database/labels/model/hmm0/hmmdefs', '-t', '250.0', '150.0', '2000.0', '/mnt/c/Users/Bonjour/Documents/GitHub/merlin/egs/speaker_adaptation/s1/database/labels/mono_phone.list']' returned non-zero exit status 52
ls: cannot access 'database/labels/label_state_align': No such file or directory
Force-alignment unsucessful!! Please check /mnt/c/Users/Bonjour/Documents/GitHub/merlin/misc/scripts/alignment/state_align/forced_alignment.py
Copying labels to duration and acoustic data directories...
cp: cannot stat 'database/labels/label_state_align': No such file or directory
cp: cannot stat 'database/labels/label_state_align': No such file or directory
ls: cannot access 'database/labels/label_state_align': No such file or directory
ls: cannot access 'database/labels/label_state_align': No such file or directory
done...!

Any idea how I could fix this?

**Comment by priyanthini** [comment]
@gaspardol Have you found a solution to this problem?

**Comment by gaspardol** [comment]
@priyanthini I couldn't make it work on my laptop, Ubuntu 18.04 LTS 

However I could make it work it work on google colab using the following code to set it up:
https://colab.research.google.com/drive/16HxKIk9KTYe5qR3Ex3wSU-viRmxsSUvj

**Comment by priyanthini** [comment]
@gaspardol Thank you.

**Comment by BeastyZ** [comment]
> https://colab.research.google.com/drive/16HxKIk9KTYe5qR3Ex3wSU-viRmxsSUvj

https://colab.research.google.com/drive/16HxKIk9KTYe5qR3Ex3wSU-viRmxsSUvj works for me. Thanks!

**Comment by Yogatiara** [comment]
hello @BeastyZ , i also have this problem, and tried to downgrade ubuntu to 18 then use gcc 4.8 and g++ 4.8. For malloc() corrupted top size problem is solved, but problem like "ERROR [+7220] NewHMMScan: cannot find any physical HMMs to scan" and gawk not finding "`database/labels/prompt-lab/tmp'".



My Errror :

converting festival utts to labels...
01_setup.sh 02_prepare_labels.sh 03_prepare_acoustic_features.sh 04_prepare_conf_files.sh 05_train_duration_model.sh 06_train_acoustic_model.sh 07_run_merlin.sh README.md conf database experiments run_demo_voice.sh scripts
gawk: fatal: cannot open file `database/labels/prompt-lab/tmp' for reading: No such file or directory
gawk: fatal: cannot open file `database/labels/prompt-lab/tmp' for reading: No such file or directory
normalizing label files for merlin...
arctic_a0001.lab
Traceback (most recent call last):
  File "/home/yoga-tiara/experiment/gantts/preprocessing/merlin/misc/scripts/frontend/utils/normalize_lab_for_merlin.py", line 134, in <module>
    normalize_label_files(in_lab_file, out_lab_file, label_style, write_time_stamps)
  File "/home/yoga-tiara/experiment/gantts/preprocessing/merlin/misc/scripts/frontend/utils/normalize_lab_for_merlin.py", line 35, in normalize_label_files
    in_f = open(in_lab_file,'r')
           ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'database/labels/prompt-lab/full/arctic_a0001.lab'
forced-alignment using HTK tools...
---preparing enverionment
---checking data
---extracting features
Tue Nov  5 18:08:46 2024
---feature_normalisation
Tue Nov  5 18:08:46 2024
---making proto
Tue Nov  5 18:08:46 2024
---training HMM models
  ERROR [+7220]  NewHMMScan: cannot find any physical HMMs to scan
 FATAL ERROR - Terminating program /home/yoga-tiara/experiment/gantts/preprocessing/merlin/tools/bin/htk/HERest
Traceback (most recent call last):
  File "/home/yoga-tiara/experiment/gantts/preprocessing/merlin/misc/scripts/alignment/state_align/forced_alignment.py", line 381, in <module>
    aligner.train_hmm(7, 32)
  File "/home/yoga-tiara/experiment/gantts/preprocessing/merlin/misc/scripts/alignment/state_align/forced_alignment.py", line 279, in train_hmm
    check_call([HERest, '-C', self.cfg, '-S', self.train_scp,
  File "/home/yoga-tiara/anaconda3/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/yoga-tiara/experiment/gantts/preprocessing/merlin/tools/bin/htk/HERest', '-C', '/home/yoga-tiara/experiment/gantts/preprocessing/merlin/egs/build_your_own_voice/s1/database/labels/config/cfg', '-S', '/home/yoga-tiara/experiment/gantts/preprocessing/merlin/egs/build_your_own_voice/s1/database/labels/config/train.scp', '-I', '/home/yoga-tiara/experiment/gantts/preprocessing/merlin/egs/build_your_own_voice/s1/database/labels/config/mono_phone.mlf', '-M', '/home/yoga-tiara/experiment/gantts/preprocessing/merlin/egs/build_your_own_voice/s1/database/labels/model/hmm_mix_1_iter_1', '-H', '/home/yoga-tiara/experiment/gantts/preprocessing/merlin/egs/build_your_own_voice/s1/database/labels/model/hmm0/macros', '-H', '/home/yoga-tiara/experiment/gantts/preprocessing/merlin/egs/build_your_own_voice/s1/database/labels/model/hmm0/hmmdefs', '-t', '250.0', '150.0', '2000.0', '/home/yoga-tiara/experiment/gantts/preprocessing/merlin/egs/build_your_own_voice/s1/database/labels/mono_phone.list']' returned non-zero exit status 52.
ls: cannot access 'database/labels/label_state_align': No such file or directory
Force-alignment unsucessful!! Please check /home/yoga-tiara/experiment/gantts/preprocessing/merlin/misc/scripts/alignment/state_align/forced_alignment.py
Copying labels to duration and acoustic data directories...
cp: cannot stat 'database/labels/label_state_align': No such file or directory
cp: cannot stat 'database/labels/label_state_align': No such file or directory
ls: cannot access 'database/labels/label_state_align': No such file or directory
ls: cannot access 'database/labels/label_state_align': No such file or directory
done...!
done...!
