### ISSUE TITLE
Error while executing prepare_labels.sh script

### ISSUE THREAD

**Issue by priyanthini** [CSTR-Edinburgh/merlin#495]
I tried labeling as follows in merlin:

./02_prepare_labels.sh ./database/wav/ ./database/utts.data ./database/labels/

It is giving a long error as :

Step 2: 
Preparing labels...
preparing full-contextual labels using Festival frontend...
creating a scheme file from text file
generating utts from scheme file
free(): invalid next size (fast)
/{MerlinDir}/egs/build_your_own_voice/s1/scripts/prepare_labels_from_txt.sh: line 53: 10424 Aborted                 (core dumped) ${FESTDIR}/bin/festival -b ${out_dir}/$scheme_file
converting festival utts to labels...
01_setup.sh 02_prepare_labels.sh 03_prepare_acoustic_features.sh 04_prepare_conf_files.sh 05_train_duration_model.sh 06_train_acoustic_model.sh 07_run_merlin.sh conf database experiments README.md run_demo_voice.sh scripts
gawk: fatal: cannot open file `./database/labels//prompt-lab/tmp' for reading (No such file or directory)
gawk: fatal: cannot open file `./database/labels//prompt-lab/tmp' for reading (No such file or directory)
normalizing label files for merlin...
ta_1001.lab
Traceback (most recent call last):
  File "/{MerlinDir}/misc/scripts/frontend/utils/normalize_lab_for_merlin.py", line 134, in <module>
    normalize_label_files(in_lab_file, out_lab_file, label_style, write_time_stamps)
  File "{MerlinDir}/misc/scripts/frontend/utils/normalize_lab_for_merlin.py", line 35, in normalize_label_files
    in_f = open(in_lab_file,'r')
IOError: [Errno 2] No such file or directory: './database/labels//prompt-lab/full/ta_1001.lab'
forced-alignment using HTK tools...
---preparing enverionment
---checking data
---extracting features
Mon Jan 13 14:51:47 2020
---feature_normalisation
Mon Jan 13 14:51:47 2020
---making proto
Mon Jan 13 14:51:47 2020
---training HMM models
  ERROR [+7220]  NewHMMScan: cannot find any physical HMMs to scan
 FATAL ERROR - Terminating program /{MerlinDir}/tools/bin/htk/HERest
Traceback (most recent call last):
  File "/{MerlinDir}/misc/scripts/alignment/state_align/forced_alignment.py", line 381, in <module>
    aligner.train_hmm(7, 32)
  File "/{MerlinDir}/misc/scripts/alignment/state_align/forced_alignment.py", line 285, in train_hmm
    stdout=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/{MerlinDir}/tools/bin/htk/HERest', '-C', '/{MerlinDir}/egs/build_your_own_voice/s1/./database/labels/config/cfg', '-S', '/{MerlinDir}/egs/build_your_own_voice/s1/./database/labels/config/train.scp', '-I', '/{MerlinDir}/egs/build_your_own_voice/s1/./database/labels/config/mono_phone.mlf', '-M', '/{MerlinDir}/egs/build_your_own_voice/s1/./database/labels/model/hmm_mix_1_iter_1', '-H', '/{MerlinDir}/egs/build_your_own_voice/s1/./database/labels/model/hmm0/macros', '-H', '/{MerlinDir}/egs/build_your_own_voice/s1/./database/labels/model/hmm0/hmmdefs', '-t', '250.0', '150.0', '2000.0', '/{MerlinDir}/egs/build_your_own_voice/s1/./database/labels/mono_phone.list']' returned non-zero exit status 52
ls: cannot access './database/labels//label_state_align': No such file or directory
Force-alignment unsucessful!! Please check /{MerlinDir}/misc/scripts/alignment/state_align/forced_alignment.py
Copying labels to duration and acoustic data directories...
cp: cannot stat './database/labels//label_state_align': No such file or directory
cp: cannot stat './database/labels//label_state_align': No such file or directory
ls: cannot access './database/labels//label_state_align': No such file or directory
ls: cannot access './database/labels//label_state_align': No such file or directory
done...!

Please someone help me to solve this error.
Thanks in advance.

**Comment by seblemaguer** [comment]
Hello, I think you are facing the "festival version" problem. I did a pull request to use a more up to date festival (see #481 ). Maybe have a look there

**Comment by priyanthini** [comment]
@seblemaguer Eventhough I edited the compile_other_speech_tools.sh as given in the link you have provided, I get the same error again and again. 
What can I do now?

**Comment by prajwaljpj** [comment]
Were you able to solve this problem? I am facing the same issue with Festival, speech_tools and festvox in their latest commit.

**Comment by priyanthini** [comment]
> Were you able to solve this problem? I am facing the same issue with Festival, speech_tools and festvox in their latest commit.

I actually manually copied my labels (created in festival) in database/labels/label_phone_align folder.

**Comment by Yogatiara** [comment]
I also get the same error. What is the solution? @priyanthini 

Step 2:
Preparing labels...
preparing full-contextual labels using Festival frontend...
creating a scheme file from text file
generating utts from scheme file
malloc(): corrupted top size
/home/yoga-tiara/experiment/gantts/preprocessing/merlin/egs/build_your_own_voice/s1/scripts/prepare_labels_from_txt.sh: line 53: 185393 Aborted                 ${FESTDIR}/bin/festival -b ${out_dir}/$scheme_file
converting festival utts to labels...
01_setup.sh 02_prepare_labels.sh 03_prepare_acoustic_features.sh 04_prepare_conf_files.sh 05_train_duration_model.sh 06_train_acoustic_model.sh 07_run_merlin.sh README.md conf database experiments run_demo_voice.sh scripts
gawk: fatal: cannot open file `database/labels/prompt-lab/tmp' for reading: No such file or directory
gawk: fatal: cannot open file `database/labels/prompt-lab/tmp' for reading: No such file or directory
normalizing label files for merlin...
arctic_a0001.lab
Traceback (most recent call last):
  File "/home/yoga-tiara/experiment/gantts/preprocessing/merlin/misc/scripts/frontend/utils/normalize_lab_for_merlin.py", line 134, in <module>
    normalize_label_files(in_lab_file, out_lab_file, label_style, write_time_stamps)
  File "/home/yoga-tiara/experiment/gantts/preprocessing/merlin/misc/scripts/frontend/utils/normalize_lab_for_merlin.py", line 35, in normalize_label_files
    in_f = open(in_lab_file,'r')
FileNotFoundError: [Errno 2] No such file or directory: 'database/labels/prompt-lab/full/arctic_a0001.lab'
forced-alignment using HTK tools...
---preparing enverionment
---checking data
---extracting features
Sun Oct 27 23:47:35 2024
---feature_normalisation
Sun Oct 27 23:47:35 2024
---making proto
Sun Oct 27 23:47:35 2024
---training HMM models
  ERROR [+7220]  NewHMMScan: cannot find any physical HMMs to scan
 FATAL ERROR - Terminating program /home/yoga-tiara/experiment/gantts/preprocessing/merlin/tools/bin/htk/HERest
Traceback (most recent call last):
  File "/home/yoga-tiara/experiment/gantts/preprocessing/merlin/misc/scripts/alignment/state_align/forced_alignment.py", line 381, in <module>
    aligner.train_hmm(7, 32)
  File "/home/yoga-tiara/experiment/gantts/preprocessing/merlin/misc/scripts/alignment/state_align/forced_alignment.py", line 285, in train_hmm
    stdout=PIPE)
  File "/home/yoga-tiara/anaconda3/envs/merlin/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/yoga-tiara/experiment/gantts/preprocessing/merlin/tools/bin/htk/HERest', '-C', '/home/yoga-tiara/experiment/gantts/preprocessing/merlin/egs/build_your_own_voice/s1/database/labels/config/cfg', '-S', '/home/yoga-tiara/experiment/gantts/preprocessing/merlin/egs/build_your_own_voice/s1/database/labels/config/train.scp', '-I', '/home/yoga-tiara/experiment/gantts/preprocessing/merlin/egs/build_your_own_voice/s1/database/labels/config/mono_phone.mlf', '-M', '/home/yoga-tiara/experiment/gantts/preprocessing/merlin/egs/build_your_own_voice/s1/database/labels/model/hmm_mix_1_iter_1', '-H', '/home/yoga-tiara/experiment/gantts/preprocessing/merlin/egs/build_your_own_voice/s1/database/labels/model/hmm0/macros', '-H', '/home/yoga-tiara/experiment/gantts/preprocessing/merlin/egs/build_your_own_voice/s1/database/labels/model/hmm0/hmmdefs', '-t', '250.0', '150.0', '2000.0', '/home/yoga-tiara/experiment/gantts/preprocessing/merlin/egs/build_your_own_voice/s1/database/labels/mono_phone.list']' returned non-zero exit status 52.
ls: cannot access 'database/labels/label_state_align': No such file or directory
Force-alignment unsucessful!! Please check /home/yoga-tiara/experiment/gantts/preprocessing/merlin/misc/scripts/alignment/state_align/forced_alignment.py
Copying labels to duration and acoustic data directories...
cp: cannot stat 'database/labels/label_state_align': No such file or directory
cp: cannot stat 'database/labels/label_state_align': No such file or directory
ls: cannot access 'database/labels/label_state_align': No such file or directory
ls: cannot access 'database/labels/label_state_align': No such file or directory
done...!
