### ISSUE TITLE
Error while executing 02_prepare_labels.sh for Sinhala Language.

### ISSUE THREAD

**Issue by DinithiUPM** [CSTR-Edinburgh/merlin#518]
I got the following error while executing 02_prepare_labels.sh for Sinhala Language.

Please help me to solve it.

Step 2: 
Preparing labels...
preparing full-contextual labels using Festival frontend...
creating a scheme file from text directory
generating utts from scheme file
malloc(): corrupted top size
/home/dinithi/merlin/egs/build_your_own_voice/s1/scripts/prepare_labels_from_txt.sh: line 53:  5957 Aborted                 (core dumped) ${FESTDIR}/bin/festival -b ${out_dir}/$scheme_file
converting festival utts to labels...
01_setup.sh 02_prepare_labels.sh 03_prepare_acoustic_features.sh 04_prepare_conf_files.sh 05_train_duration_model.sh 06_train_acoustic_model.sh 07_run_merlin.sh Build_voice_sinhala.ipynb conf database experiments get-pip.py README.md run_demo_voice.sh scripts
gawk: fatal: cannot open file `database/labels/prompt-lab/tmp' for reading (No such file or directory)
gawk: fatal: cannot open file `database/labels/prompt-lab/tmp' for reading (No such file or directory)
normalizing label files for merlin...
s1001.lab
Traceback (most recent call last):
  File "/home/dinithi/merlin/misc/scripts/frontend/utils/normalize_lab_for_merlin.py", line 134, in <module>
    normalize_label_files(in_lab_file, out_lab_file, label_style, write_time_stamps)
  File "/home/dinithi/merlin/misc/scripts/frontend/utils/normalize_lab_for_merlin.py", line 35, in normalize_label_files
    in_f = open(in_lab_file,'r')
FileNotFoundError: [Errno 2] No such file or directory: 'database/labels/prompt-lab/full/s1001.lab'
forced-alignment using HTK tools...
---preparing enverionment
---checking data
---extracting features
Traceback (most recent call last):
  File "/home/dinithi/merlin/misc/scripts/alignment/state_align/forced_alignment.py", line 379, in <module>
    aligner.prepare_training(file_id_list_name, wav_dir, lab_dir, work_dir, multiple_speaker)
  File "/home/dinithi/merlin/misc/scripts/alignment/state_align/forced_alignment.py", line 253, in prepare_training
    self._HCopy()
  File "/home/dinithi/merlin/misc/scripts/alignment/state_align/forced_alignment.py", line 190, in _HCopy
    check_call([HCopy, '-C', self.cfg, '-S', self.copy_scp])
  File "/home/dinithi/anaconda3/lib/python3.6/subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/home/dinithi/anaconda3/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/dinithi/anaconda3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/home/dinithi/anaconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/dinithi/merlin/tools/bin/htk/HCopy': '/home/dinithi/merlin/tools/bin/htk/HCopy'
ls: cannot access 'database/labels/label_state_align': No such file or directory
Force-alignment unsucessful!! Please check /home/dinithi/merlin/misc/scripts/alignment/state_align/forced_alignment.py
Copying labels to duration and acoustic data directories...
cp: cannot stat 'database/labels/label_state_align': No such file or directory
cp: cannot stat 'database/labels/label_state_align': No such file or directory
ls: cannot access 'database/labels/label_state_align': No such file or directory
ls: cannot access 'database/labels/label_state_align': No such file or directory
done...!

**Comment by RasmusD** [comment]
Default festival does not produce sinhala compatible labels. It's english specific. You'd want to create your own sinhala label generator.

**Comment by DinithiUPM** [comment]
Do you mean the question file?

**Comment by RasmusD** [comment]
The question file ask questions about the generated labels.
The labels should contain sinhala relevant information to ask questions about ;-)

**Comment by DinithiUPM** [comment]
Okay. Thank you so much.
