### ISSUE TITLE
the issues of forced_alignment.py  

### ISSUE THREAD

**Issue by wangqipeng** [CSTR-Edinburgh/merlin#52]
Hi, guys: 
     when i run the script:  forced_alignment.py , i found the format of the lab files int the directory: "label_state_align" was error, which include two more time stamp columns int the lab files from the "label_no_align" directory.
     the problem from the below code. In the line: 16, the variable "full_tab" is a raw line from the no align lab file, it was print to the last lab file directly in the line: 20. 
     Before print to the last lab files, may be should get rid of the two raw time stamp columns in the no align label files.

   1. def _postprocess(self, mlf, lab_align_dir):
   2     if not os.path.exists(lab_align_dir):
   3        os.makedirs(lab_align_dir)
   4     state_num = STATE_NUM
   5    fid = open(mlf, 'r')
   6     line = fid.readline()
   7     while True:
   8         line = fid.readline()
   9         line = line.strip()
  10         if len(line) < 1:
  11              break
  12        line = line.replace('"', '')
  13          file_base = os.path.basename(line)
  14          flab = open(os.path.join(self.lab_dir, file_base), 'r')
  15          fw   = open(os.path.join(lab_align_dir, file_base), 'w')
  16          for full_lab in flab.readlines():
  17              full_lab = full_lab.strip()
  18              for i in xrange(state_num):
  19                  line = fid.readline()
  20                  line = line.strip()
  21                  tmp_list = line.split()
  22                  print >> fw,'{0} {1} {2}[{3}]'.format(tmp_list[0], tmp_list[1], full_lab, i+2)
  23
  24          fw.close()
  25          flab.close()
  26          line = fid.readline()
  27          line = line.strip()
  28         if line != '.':
  29              print 'The two files are not matched!\n'
  30              sys.exit(1)
  31      fid.close()

`

**Comment by ronanki** [comment]
The input format for alignment itself excludes those two columns. May be you missed this step:
https://github.com/CSTR-Edinburgh/merlin/blob/master/misc/scripts/alignment/state_align/prepare_labels_from_txt.sh#L60-L66

**Comment by wangqipeng** [comment]
I had run this script and check the L60-L66, but the format of the last lab files in the "label_state_align" dir just like below:  
**200000 250000 0 200000** x^x-pau+n=iy@1_0/A:0_0_0/B:0-0-0@1-0&1-1#1-1$1-1!0-0;0-0|0/C:0+0+0/D:0_0/E:0+0@1+0&1+0#0+0/F:0_0/G:0_0/H:0=0@1=2|0/I:0=0/J:10+10-2[2][6]

and the lab file from the slt_arctic_demo_data  is : 
**0 50000** x^x-sil+sil=ax@x_x/A:0_0_0/B:x-x-x@x-x&x-x#x-x$x-x!x-x;x-x|x/C:0+0+0/D:0_0/E:x+x@x+x&x+x#x+x/F:0_0/G:0_0/H:x=x@1=2|0/I:0=0/J:28+13-2[2]

**Comment by ronanki** [comment]
Can you print first few lines in "label_no_align" dir?

**Comment by wangqipeng** [comment]
these lines from "label_no_align" dir :

**0 200000** x^x-pau+f=awng@1_0/A:0_0_0/B:0-0-0@1-0&1-1#1-1$1-1!0-0;0-0|0/C:0+0+0/D:0_0/E:0+0@1+0&1+0#0+0/F:0_0/G:0_0/H:0=0@1=1|0/I:0=0/J:6+6-1[2]
**200000 400000** x^x-pau+f=awng@1_0/A:0_0_0/B:0-0-0@1-0&1-1#1-1$1-1!0-0;0-0|0/C:0+0+0/D:0_0/E:0+0@1+0&1+0#0+0/F:0_0/G:0_0/H:0=0@1=1|0/I:0=0/J:6+6-1[3]
**400000 600000** x^x-pau+f=awng@1_0/A:0_0_0/B:0-0-0@1-0&1-1#1-1$1-1!0-0;0-0|0/C:0+0+0/D:0_0/E:0+0@1+0&1+0#0+0/F:0_0/G:0_0/H:0=0@1=1|0/I:0=0/J:6+6-1[4]
**600000 800000** x^x-pau+f=awng@1_0/A:0_0_0/B:0-0-0@1-0&1-1#1-1$1-1!0-0;0-0|0/C:0+0+0/D:0_0/E:0+0@1+0&1+0#0+0/F:0_0/G:0_0/H:0=0@1=1|0/I:0=0/J:6+6-1[5]
**800000 1100000** x^x-pau+f=awng@1_0/A:0_0_0/B:0-0-0@1-0&1-1#1-1$1-1!0-0;0-0|0/C:0+0+0/D:0_0/E:0+0@1+0&1+0#0+0/F:0_0/G:0_0/H:0=0@1=1|0/I:0=0/J:6+6-1[6]

**Comment by ronanki** [comment]
yeah, it's incorrect format. The time-stamps shouldn't be there. And only one full-contextual line per phone is used as input. Something like this:

x^x-sil+ao=th@x_x/A:0_0_0/B:x-x-x@x-x&x-x#x-x$x-x!x-x;x-x|x/C:1+1+1/D:0_0/E:x+x@x+x&x+x#x+x/F:content_2/G:0_0/H:x=x@1=2|0/I:7=5/J:14+8-2
x^sil-ao+th=er@1_1/A:0_0_0/B:1-1-1@1-2&1-7#1-4$1-3!0-2;0-4|ao/C:0+0+2/D:0_0/E:content+2@1+5&1+2#0+3/F:in_1/G:0_0/H:7=5@1=2|L-L%/I:7=3/J:14+8-2
sil^ao-th+er=ah@1_2/A:1_1_1/B:0-0-2@2-1&2-6#1-4$1-3!1-1;1-3|er/C:1+0+2/D:0_0/E:content+2@1+5&1+2#0+3/F:in_1/G:0_0/H:7=5@1=2|L-L%/I:7=3/J:14+8-2
ao^th-er+ah=v@2_1/A:1_1_1/B:0-0-2@2-1&2-6#1-4$1-3!1-1;1-3|er/C:1+0+2/D:0_0/E:content+2@1+5&1+2#0+3/F:in_1/G:0_0/H:7=5@1=2|L-L%/I:7=3/J:14+8-2
th^er-ah+v=dh@1_2/A:0_0_2/B:1-0-2@1-1&3-5#1-3$1-3!2-2;2-2|ah/C:0+0+2/D:content_2/E:in+1@2+4&2+2#1+2/F:det_1/G:0_0/H:7=5@1=2|L-L%/I:7=3/J:14+8-2

**Comment by wangqipeng** [comment]
i don't see any lab files is the format you described in my building dir, is it the bug of HTK labeling process or some steps incorrect in my building process? 
if it's a bug, i will fix it. : )
