### ISSUE TITLE
problem with download the dataset 

### ISSUE THREAD

**Issue by ghost** [CSTR-Edinburgh/merlin#520]
I am facing difficulty with downloading a dataset. please help 

 ali@1c30:~/merlin/egs/speaker_adaptation/s1$ ./download_data.sh
downloading data.....
--2021-01-30 18:35:37--  http://homepages.inf.ed.ac.uk/jyamagis/release/VCTK-Corpus.tar.gz
Resolving homepages.inf.ed.ac.uk (homepages.inf.ed.ac.uk)... 129.215.32.113
Connecting to homepages.inf.ed.ac.uk (homepages.inf.ed.ac.uk)|129.215.32.113|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-01-30 18:35:38 ERROR 404: Not Found.

extracting files......
tar (child): VCTK-Corpus.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

**Comment by simonkingedinburgh** [comment]
On 30 Jan 2021, at 18:39, Alimandeel wrote:

\--2021-01-30 18:35:37-- <http://homepages.inf.ed.ac.uk/jyamagis/release/VCTK-Corpus.tar.gz>

That link needs to be updated - VCTK is now here

https://datashare.ed.ac.uk/handle/10283/2950
https://datashare.ed.ac.uk/download/DS_10283_3443.zip

Simon

--
Prof. Simon King
Director of the Centre for Speech Technology Research
Professor of Speech Processing
University of Edinburgh,UK
www.cstr.ed.ac.uk

The University of Edinburgh is a charitable body, registered in Scotland, with registration number SC005336.

**Comment by ghost** [comment]
thanks, it works
