### ISSUE TITLE
Error Format Of Dur_Label In HTS

### ISSUE THREAD

**Issue by xyx361100238** [CSTR-Edinburgh/merlin#529]
Dear ALL:
I was use MTTS to deal Mandarin TTS frontend  (text2label with no dur)：
```
0 0 xx^xx-sil+j=i4@xx@/A:xx-xx^xx@/B:xx+xx@xx^xx^xx+x……
0 0 xx^sil-j+i4=x@i@/A:xx-4^4@/B:0+19@1^2^1+20#1-20-/……
0 0 sil^j-i4+x=v4@i@/A:xx-4^4@/B:0+19@1^2^1+20#1-20-/……
```

then use merlin to alignment：
```
0 0 xx^xx-sil+j=i4@xx@/A:xx-xx^xx@/B:xx+xx@xx^xx^xx+xx#xx-xx-/C:……
0 900000 xx^sil-j+i4=x@i@/A:xx-4^4@/B:0+19@1^2^1+20#1-20-/C:xx_v……
900000 1600000 sil^j-i4+x=v4@i@/A:xx-4^4@/B:0+19@1^2^1+20#1-20-/……
```

When I use this label files to train in HTS,tips:
```
=============== sil ================
- system is PLAIN
  ERROR [+2121]  HInit: Too Few Observation Sequences [0]
 FATAL ERROR - Terminating program /home/xieyouxi/010_TTS_Pro/HTS_Pro/htk/bin/HInit
Error in /home/xieyouxi/010_TTS_Pro/HTS_Pro/htk/bin/HInit     -A    ……
```
it means no have enough lab for phone 'sil',that's because dur_label is 0 ~ 0 in line one。
how to slove this problem,thinks 

(it works well in merlin system)

**Comment by xyx361100238** [comment]
@ZackHodari

**Comment by ZackHodari** [comment]
Your issue seems to be related to HTS, forced alignment, or your data, not merlin.

**Comment by xyx361100238** [comment]
I was use merlin to force alignment ： ./scripts/submit.sh ${MerlinDir}/src/run_merlin.py conf/test_dur_synth_mandarin_voice.conf
Actually，there is silence section in train wav file，so the format like：
```
0 400000 xx^xx-sil+j=i4@xx@/A:xx-xx^xx@/B:xx+xx@xx^xx^xx+xx#xx-xx-/C:……
400000 900000 xx^sil-j+i4=x@i@/A:xx-4^4@/B:0+19@1^2^1+20#1-20-/C:xx_v……
900000 1600000 sil^j-i4+x=v4@i@/A:xx-4^4@/B:0+19@1^2^1+20#1-20-/……
```
