### ISSUE TITLE
nooby - slt_artic/s1/run_demo error 

### ISSUE THREAD

**Issue by rowntreerob** [CSTR-Edinburgh/merlin#56]
script runs for a min or so before throwing error:  
CRITICAL[0m     subprocess: exit status 127
CRITICAL[0m     subprocess:  for command: echo 1 1 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4  | /home/rob/src/tmp/merlin/tools/bin/SPTK-3.9/x2x +af > /home/rob/src/tmp/merlin/egs/slt_arctic/s1/experiments/slt_arctic_demo/acoustic_model/gen/DNN_TANH_TANH_TANH_TANH_LINEAR__mgc_lf0_vuv_bap_1_50_425_187_4_512_512/weight

CRITICAL[0m     subprocess:       stderr: /bin/sh: 1: /home/rob/src/tmp/merlin/tools/bin/SPTK-3.9/x2x: not found

stdout :  

  File "/home/rob/src/tmp/merlin/src/run_merlin.py", line 1175, in <module>
    main_function(cfg)
  File "/home/rob/src/tmp/merlin/src/run_merlin.py", line 961, in main_function
    generate_wav(gen_dir, gen_file_id_list, cfg)     # generated speech
  File "/home/rob/src/tmp/merlin/src/utils/generate.py", line 200, in generate_wav
    .format(line=line, x2x=SPTK['X2X'], weight=os.path.join(gen_dir, 'weight')))
  File "/home/rob/src/tmp/merlin/src/utils/generate.py", line 93, in run_process

The 'SPTK..' folder is empty. do i need to do another git pull or something?

**Comment by ronanki** [comment]
Did you install tools as per the given instructions?
https://github.com/CSTR-Edinburgh/merlin/tree/master/tools

**Comment by rowntreerob** [comment]
thank you. that is solution to issue.
