### ISSUE TITLE
merlin on windows 

### ISSUE THREAD

**Issue by m7md7sien** [CSTR-Edinburgh/merlin#57]
Can merlin be used on windows for synthesis only at least?
other than changing the bash scripts and installing theano and other dependencies on windows, what else should I do if any in order to use an already trained model on windows?

thank you in advance.

**Comment by ZackHodari** [comment]
If you have a working install of python with the necessary requirements, as well as any required command line tools for the tasks you wish to perform (vocoders, HTK, etc.). Then you should just be able to run the python scripts (e.g. `run_merlin.py`). As you mentioned, you will have to change the bash scripts (or use [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10))
