### ISSUE TITLE
How can I control the duration ?

### ISSUE THREAD

**Issue by rmmal** [CSTR-Edinburgh/merlin#58]
Is there anything that can allow me to change the duration of the silence pattern ? 
I mean that I want the "sil" or "pau" to be 0.5 seconds or anything , how can I achieve this ?

**Comment by ronanki** [comment]
You can do so while [preparing labels] (https://github.com/CSTR-Edinburgh/merlin/blob/master/egs/slt_arctic/s1/scripts/prepare_labels_from_txt.sh) from text. 

[normalize_lab_for_merlin.py] (https://github.com/CSTR-Edinburgh/merlin/blob/master/misc/scripts/frontend/utils/normalize_lab_for_merlin.py) script does lab normalization as per either phone_align/state_align -- you can change the silence duration there. 

pause duration is nothing but a phrase break, which is predicted w.r.t context and I don't recommend modifying it to a fixed duration.

**Comment by rmmal** [comment]
So do you mean that it takes the silence pattern given to him and give it the duration from the normalize_lab_for_merlin. ?
Now I get the state labels from another source so if I want the silence pattern to be for a certain duration I should give it a fixed duration in this labels and then whenever it sees it , it will take this duration ,right ?

**Comment by ronanki** [comment]
Yes, you are right. Silence duration is usually not predicted -- so whatever duration the initial labels has for silence, the same is reflected in synthesis.All other phones including pause are predicted from a duration model.

**Comment by rmmal** [comment]
Yes yes , thanks for explaining (Y)
