### ISSUE TITLE
How can I use new features in merlin ?

### ISSUE THREAD

**Issue by rmmal** [CSTR-Edinburgh/merlin#59]
I want to use different features in merlin like Bottlneck features or filterbanks or any other features , What should I change in the scripts to implement my own neural network using these features ?

**Comment by yzliu90** [comment]
you can modify the configuration file

**Comment by ronanki** [comment]
Do you mean to change/replace vocoder features or do you mean to add some more additional features to the existing linguistic features?

**Comment by ronanki** [comment]
For first case, to change/replace vocoder features, you need to change the variable output_features and gen_wav_features in configuration file as per your vocoder. 

For second case, you need to use additional_features variable in configuration file.

**Comment by rmmal** [comment]
Thanks ronanki for your answer (Y)
