### ISSUE TITLE
about acoustic parameters

### ISSUE THREAD

**Issue by yzliu90** [CSTR-Edinburgh/merlin#61]
Hello, which tools be used to extract the acoustic parameters in the demo of merlin,world or straight?
thank you so much!

**Comment by seblemaguer** [comment]
Hello,

if by demo you mean the slt voice, according to this file https://github.com/CSTR-Edinburgh/merlin/blob/master/egs/slt_arctic/s1/conf/dnn/acoustic_slt_arctic_full.conf, it is world

**Comment by zhizhengwu** [comment]
by default is world + SPTK: https://github.com/CSTR-Edinburgh/merlin/tree/master/misc/scripts/vocoder
