### ISSUE TITLE
How to implement voice conversion with merlin

### ISSUE THREAD

**Issue by wangqipeng** [CSTR-Edinburgh/merlin#62]
Hi, guys!
     the paper tell us Merlin had be used for voice conversion, is there any tutorial available on this field?

**Comment by ronanki** [comment]
As of now, there is no tutorial. But, it's not difficult to implement. 

At the moment, only training is supported. Preparation of source and target acoustic files (MGC+BAP+LF0) and alignment are not included in the Merlin. 

Assuming you have training files -- for voice conversion training, you need to use a blank question file and set the appended_input_dim variable to the same dimension as of target cmp. Use nn_no_silence_lab_norm_{src_dim} folder to save the source files -- and the remaining training and synthesis is common to TTS.

**Comment by rmmal** [comment]
@ronanki  assuming that both speakers say the same sentence ( parallel data ) , right ?

**Comment by ronanki** [comment]
Yes -- parallel data.

**Comment by vsooda** [comment]
@ronanki  how to deal with the alignment problem between source sentence and target sentence for using parallel data to train a voice conversion model.

**Comment by ronanki** [comment]
Once after speech_tools and festvox are properly installed, follow the below steps to get the alignments.

Steps:
1. $SPTK/bin/x2x +fa inp.mgc > inp_ascii.mgc
2. cat inp_ascii.mgc | xargs -n60 > inp_ascii_mc.mgc
3. ~/Tools/speech_tools/bin/ch_track -s 0.005 -otype est_binary inp_ascii.mgc -o inp_binary.mgc
4. ~/Tools/festvox/src/general/phonealign -itrack ref_binary.mgc -otrack inp_binary.mgc -ilabel i.lab -olabel o.lab -verbose -withcosts
5. cat <phonealign output> | sed ‘1d’ | cut -d “ “ -f 2 | \
while read a; do sed “`exp $a + 1 `q;d” inp_ascii_matrix.mgc >> ip_aligned.mgc; done
6. $SPTK/bin/x2x +af inp_ascii_aligned.mgc > inp_aligned.mgc

**Comment by vsooda** [comment]
@ronanki  thank you very much.

**Comment by lbqin** [comment]
@ronanki can you check your voice convert steps above. I had followed the recipes, but I feel confused about step5. What is the input and output of step5. can you explain it for me. 

Thank you.

**Comment by ronanki** [comment]
You have to write the output of 4th step into a file and then use that file in 5th step. Fourth step gives each index mapping w.r.t length of reference. You have to use those indices and inp.mgc to get the alignment.

**Comment by lbqin** [comment]
@ronanki thanks.

**Comment by ronanki** [comment]
[Scripts to perform voice conversion](https://github.com/CSTR-Edinburgh/merlin/tree/master/egs/voice_conversion/s1) are now added in Merlin.

**Comment by yuxialuo** [comment]
Hi, @ronanki,

Run step by step https://github.com/CSTR-Edinburgh/merlin/blob/master/egs/voice_conversion/s1/run_demo_vc.sh,

./05_train_acoustic_model.sh conf/acoustic_bdl.conf
Got error:

Traceback (most recent call last):
  File "/root/merlin/src/run_merlin.py", line 1194, in <module>
    main_function(cfg)
  File "/root/merlin/src/run_merlin.py", line 691, in main_function
    acoustic_worker.prepare_nn_data(in_file_list_dict, nn_cmp_file_list, cfg.in_dimension_dict, cfg.out_dimension_dict)
  File "/root/merlin/src/frontend/acoustic_base.py", line 122, in prepare_nn_data
    self.prepare_data(in_file_list_dict, out_file_list, in_dimension_dict, out_dimension_dict)
  File "/root/merlin/src/frontend/acoustic_composition.py", line 157, in prepare_data
    delta_features = self.compute_dynamic_matrix(features, self.delta_win, frame_number, in_feature_dim)
  File "/root/merlin/src/frontend/acoustic_base.py", line 197, in compute_dynamic_matrix
    dynamic_matrix[:, dim:dim+1] = self.compute_dynamic_vector(data_matrix[:, dim], dynamic_win, frame_number)
  File "/root/merlin/src/frontend/acoustic_base.py", line 182, in compute_dynamic_vector
    temp_vector[w, 0] = vector[0, 0]
IndexError: index 0 is out of bounds for axis 0 with size 0
