### ISSUE TITLE
bap should less than 0 in world

### ISSUE THREAD

**Issue by Chaos-XingChao** [CSTR-Edinburgh/merlin#63]
Hi, I found bap should less than 0 in world else it will be strange in synthesised wave.
I had hardly change the bap value from upper than 0 to 0.
So, does this possible we modify it during training process? Like nonlinear activate function for bap only?

**Comment by ronanki** [comment]
which version of WORLD are you using? WORLD or WORLD_v2 ?

**Comment by Chaos-XingChao** [comment]
It's WORLD~
