### ISSUE TITLE
How to read the MCD Calculations

### ISSUE THREAD

**Issue by ikhfa** [CSTR-Edinburgh/merlin#66]
```
INFO           main    : calculating MCD
INFO           main    : Develop: DNN -- MCD: 5.077 dB; BAP: 0.232 dB; F0:- RMSE: 23.313 Hz; CORR: 0.726; VUV: 8.990%
INFO           main    : Test   : DNN -- MCD: 5.030 dB; BAP: 0.224 dB; F0:- RMSE: 21.781 Hz; CORR: 0.720; VUV: 9.205%
```

Hi, how to read the distortion here? What's the difference between 'Develop' and 'Test'? Could anyone provide any papers related to that? Thanks

**Comment by seblemaguer** [comment]
according to the source code :
  - test is corresponding to the test corpus (I suspect that the one which is synthesized also after) and develop to the validation corpus .
  - to see how is computed MCD you should have a look to this file  [merlin/src/utils/compute_distortion.py](merlin/src/utils/compute_distortion.py) especially the method starting line 59.
  - just take also into account these lines:
```python
valid_spectral_distortion *= (10 /numpy.log(10)) * numpy.sqrt(2.0)    ##MCD
test_spectral_distortion *= (10 /numpy.log(10)) * numpy.sqrt(2.0) ##MCD
```
As far as I see, it is a classical MCD as defined for example in SPTK.

**Comment by Lukelluke** [comment]
I love you! 
And i finally figure clearly out where is the MCD toolkit, all in Merlin & SPTK.
I used to use an independent package named "mcd", and cost so much time to deal with temporary files.


But to be honest, the score result of MCD do have too much accuracy problem. Not as accuracy as speech enhancement metrics(e.g. PESQ etc.), but more and more VoiceConversion related works would like to present this MCD metric.
