### ISSUE TITLE
how can use the gv for training and synthesizing

### ISSUE THREAD

**Issue by yzliu90** [CSTR-Edinburgh/merlin#67]
Hey,Guys:
      how can use the gv model for training ang synthesizing speech

**Comment by ronanki** [comment]
GV scripts are not yet complete. 

GV stats are calculated using a matlab script and stored in data folder (data/GV)-- which has to be re-written in python (will be uploaded some time soon).

GV testing -- can be applied by setting variable 'apply_GV' to True.
