### ISSUE TITLE
Frame Number Mismatch

### ISSUE THREAD

**Issue by habdulkafi** [CSTR-Edinburgh/merlin#68]
I'm trying to run the `build_your_own_voice` example.  I'm running into this error while running `03_run_merlin.sh` after `Step 3: training acoustic model...`:

```
2016-12-29 23:47:50,111 INFO      acoustic_comp: processing file    1 of  175 : /home/husam/tf-wn-new/merlin/egs/build_your_own_voice/s2/experiments/obama/acoustic_model/data/nn_mgc_lf0_vuv_bap_187/barackobamaafghanistantroopreductionARXE_cut_21.cmp
2016-12-29 23:47:50,625 CRITICAL  acoustic_comp: the frame number of data stream lf0 is not consistent with others: current 1542 others 772
Traceback (most recent call last):
  File "/home/husam/tf-wn-new/merlin/src/run_merlin.py", line 1175, in <module>
    main_function(cfg)
  File "/home/husam/tf-wn-new/merlin/src/run_merlin.py", line 693, in main_function
    acoustic_worker.prepare_nn_data(in_file_list_dict, nn_cmp_file_list, cfg.in_dimension_dict, cfg.out_dimension_dict)
  File "/home/husam/tf-wn-new/merlin/src/frontend/acoustic_base.py", line 122, in prepare_nn_data
    self.prepare_data(in_file_list_dict, out_file_list, in_dimension_dict, out_dimension_dict)
  File "/home/husam/tf-wn-new/merlin/src/frontend/acoustic_composition.py", line 137, in prepare_data
    assert  out_frame_number == frame_number
AssertionError
Lock freed
```

I'm not sure how most of this stuff works, but I think the problem is the vocoder generation.  I'm using the World vocoder script (I don't have access to the STRAIGHT vocoder).  I tried a few weeks ago running the whole `build_your_own_voice` example with the SLT Arctic dataset, but hit the exact same error. 
Any insight as to why this is happening?  There is not error before this point.

**Comment by ikhfa** [comment]
Yup, i believe there's difference between the number of features extracted from vocoder and the one on your configuration file.

**Comment by m-toman** [comment]
See also https://github.com/CSTR-Edinburgh/merlin/issues/54

**Comment by nischalpatil** [comment]
I get this exact same error. i used WORLD vocoder and I have no idea how to clear. i checked the other similar issues but did not get any resolve please help.

**Comment by seblemaguer** [comment]
Hello,

have you checked that the sample rate in the configuration file and the one of your wave files are the same? also be sure that the wav format is compatible with merlin (mono, ...)

**Comment by fuzeller** [comment]
Hi, I have also seen this happen when there isn't enough silence at the start or end of the audio. You could test this by padding your samples with silence, preferably by adding a sample of silence (about 0.01 to 0.02 seconds) extracted from your audio. Padding with zero is also possible, but I don't recommend it.

The resulting audio will then be labeled with pause/silence that has enough frames (>0).

Good luck!

**Comment by ZackHodari** [comment]
The OP's issue may be due to a numpy dtype mistake when loading/saving the binary file. 

```... the frame number of data stream lf0 is not consistent with others: current 1542 others 772```

These are _roughly_ twice each other, so it is possible `np.float32` and `np.float64` were used incorrectly.

However, this will be in addition to another issue since `772 * 2 = 1544 != 1542`
