### ISSUE TITLE
State alignment - no tokens survived to final node

### ISSUE THREAD

**Issue by madhavivr** [CSTR-Edinburgh/merlin#70]
HI! 

I am trying to build a voice with my own data and when doing state alignment I have been running into this issue of "tokens not surviving to the final node". The code I am using is  merlin/misc/scripts/alignment/state_align/run_aligner.sh and this problem occurs specifically with forced_alignment.py and running HVite. 

I realized the problem is due to the number of states and mixtures used for monophone training - 7 states and 32 mixtures seemed a bit much. So I reduced it and I had to bring it down to 5 states and 1 mixture before I could force align all but 3 of my data. I was wondering what the standard states and mixtures others are using?

The second issue I'm having is with the labeling it looks like this with multiple successive repetitions of the same phone. 

sil
sil
sil
sil
sil
k
k
k
k
k
ae
ae
ae
ae
ae
n
n
n
n
n
.....

But if I change it to the way HTK usually requires it
 sil
k
ae
n
...
I actually have no trouble with tokens making it to the end. 

But ofcourse I run into trouble in the "postprocess" where the code combines the labeling from festival with the HTK state alignment.  

I solved the above problem by changing the num_states in misc/frontend/utils/normalize_lab_for_merlin.py from 5 to 1. 
This code writes the same phone 5 times if there are 5 states, it seems this is done in an effort to split the duration equally between the 5 states - can someone please explain why this is needed. This seems unnecessary especially for HTK training and testing. HTK doesn't need this kind of equal splitting HCompV and HERest can take care of it.

**Comment by ronanki** [comment]
The below post-processing script uses phone_align option and 0 in the end, so that the output labels are phone-level labels without any time-stamps. Thereafter, run_aligner script uses this format to do state-level alignment. 

echo "normalizing label files for merlin..."
python ${frontend}/utils/normalize_lab_for_merlin.py \
                            ${WorkDir}/prompt-lab/full \
                            ${WorkDir}/label_no_align \
                            phone_align \
                            ${WorkDir}/file_id_list.scp 0
