### ISSUE TITLE
phone alignment

### ISSUE THREAD

**Issue by madhavivr** [CSTR-Edinburgh/merlin#72]
Hi! When it runs phone alignment the do_build labels command results in the a couple of utterance being discarded due to NAN problem.

Here is part of the output.  Any pointers on why and how to fix this problem?

Prompt: 1609 discarded due to NAN problem 
Note: Floored: word:state:gau:dim 28:143:0:0
FLOORED : 2.46253e-06 TO 0.001
Note: Floored: word:state:gau:dim 28:143:0:1
FLOORED : 4.50461e-05 TO 0.001
Note: Floored: word:state:gau:dim 28:143:0:2
FLOORED : 0.000201208 TO 0.001
Note: Floored: word:state:gau:dim 28:143:0:3
FLOORED : 0.000304336 TO 0.001
Note: Floored: word:state:gau:dim 28:143:0:4
FLOORED : 0.000460559 TO 0.001
Note: Floored: word:state:gau:dim 28:143:0:5
FLOORED : 0.000699819 TO 0.001
Note: Floored: word:state:gau:dim 28:143:0:6
FLOORED : 0.000955538 TO 0.001
Note: Floored: word:state:gau:dim 28:143:0:10
FLOORED : 0.000977612 TO 0.001
Average Likelihood: (21) -27.1898 -0.0117849
Accepted sentences are: 1603 / 1610

**Comment by ronanki** [comment]
1. If the audio files are not properly trimmed.....(either beginning/end silence missing) -- then such audio files may not get aligned. 
2. If the text and audio doesn't match -- then also there would be alignment problem.

**Comment by shartoo** [comment]
@ronanki do you have kept the scripts or note on preparing the `slt_arctic_demo_data `?I'm trying to synthesis Chinese from scratch but having no idea how to prepare these file.

**Comment by ronanki** [comment]
For new languages, you need to have a well-defined phoneset and lexicon to prepare utt files. And then you can follow the rest of the code to build models and synthesize.

**Comment by shartoo** [comment]
@ronanki  there is a Chinese speech dataset [THCHS30](http://www.cslt.org/news.php?title=News-20160204) with phoneset and lexicon,but `Festival` cannot process Chinese, how could i get utt files?

**Comment by shartoo** [comment]
@ronanki  Sorry to ask you some fundamental issue,i'm trying to construct Chinese TTS according to your script in `festival_utt_to_lab` in Merlin .Thank you! I'll keep trying.

**Comment by auzxb** [comment]
Hi，have you found some methods to process Chinese？ @shartoo

**Comment by shartoo** [comment]
@auzxb No,i have stop researching TTS now. There are some notes on my personal blog ,[my blog](shartoo.github.io) . Maybe i'll back someday.
