### ISSUE TITLE
TOBI label?

### ISSUE THREAD

**Issue by dreamk73** [CSTR-Edinburgh/merlin#79]
I notice when generating .lab files with full context labels, that it lists a TOBI label for words preceding a phrase boundary. But I don't see any reference to it in the question file, nor in the label_normalisation files? Is that feature even used?

**Comment by oliverwatts** [comment]
The labels output from Festival used for training in the Merlin demos add ToBI purely as predicted from text, so there is a very poor relation between ToBI in the labels and real prosodic events in the speech. We found that excluding questions relating to ToBI either didn't affect or slightly improved performance. If you have a database which is properly labelled with ToBI or something similar, you might want to add the relevant questions back in.

**Comment by zhizhengwu** [comment]
On the Nick data, we found removing ToBI can slightly improve objective measures, but did not do subjective evaluation.  You may  try this one your own data with ToBI.
