### ISSUE TITLE
How to Train Merlin on other languages ??

### ISSUE THREAD

**Issue by ajinkyakulkarni14** [CSTR-Edinburgh/merlin#85]
Hi ! 

I want to train TTS system for Spanish Language, What are the initial Steps I should follow ?
( Like Data Preprocessing step or Extracting linguistic feature or training commands for training with various options, speech generation commands )

Thank You !!

**Comment by bajibabu** [comment]
Hi, 
I recommend you to check this issue https://github.com/CSTR-Edinburgh/merlin/issues/18 and materials in this course http://www.speech.zone/courses/speech-synthesis/
