### ISSUE TITLE
Heads up: phone / state begin and end samples

### ISSUE THREAD

**Issue by dreamk73** [CSTR-Edinburgh/merlin#89]
I just wanted to explain a problem we had been dealing with when training a new voice with Merlin using our own label files. We couldn't figure out why the speech sounded so unintelligible. We had Festival-generated label files for the same audio data which sounded absolutely fine, but as soon as we input our own label files, it sounded like the speaker had a stroke and started to mumble. 

After investigating everything, bringing the question file down to the bare minimum of the current phone, we figured it out. We used the actual time stamps of the phoneme boundaries that are used in our system and then created the state time stamps from there. But instead, you should round them up/down to the nearest 5ms frame. Once we figured that out and retrained, the generated speech sounded the same as those from the Festival-based files. I hope we can help someone out with this.

**Comment by ronanki** [comment]
Thanks for posting this. 

However, we have a script to deal with this:
https://github.com/CSTR-Edinburgh/merlin/blob/master/misc/scripts/frontend/utils/normalize_lab_for_merlin.py

If you use label_style as state_align, then it would automatically does this -- dividing phone duration into uniform state durations and rounding them to nearest 5ms.

**Comment by dreamk73** [comment]
I had overlooked this script. We created our own context label files using hand-corrected segment boundaries and our own linguistic preprocessor and got the states from a modified forced_alignment script. We don't want uniform state durations but we do want to round them to the nearest 5ms. At any rate, it was a helpful realization that that was required to get intelligible speech.

**Comment by dreamk73** [comment]
A related question is what happens to phone durations that are less than 25 ms? Is that even allowed in Merlin? If you have 5 states and the rounding is 5 ms, don't you need a phone to be at least 25 ms long? I am wondering if this is a problem when you use HTK to automatically segment or if this is taken care of automatically because it sets a minimum duration?

And in addition, it would be good to specify some symbol to be able to ignore a phoneme in training(because it contains a glitch or is too short) but still use it in the context labels.

**Comment by ronanki** [comment]
If you use HTK state-aligner, it automatically sets each state duration to a minimum of 5ms even if the alignment of that particular phone is less than 25ms. This may lead to incorrect/inaccurate alignments at few places -- but that's how Merlin works for now. 

If you use Festvox phone aligner -- the phone duration can be less than 25ms and it's okay to have it as Merlin doesn't depend upon only state-alignments.  So, phone-alignments can also be used.

**Comment by dreamk73** [comment]
There seems to be an error with HCOPY where if you try to use the HTK state aligner with phoneme boundaries that are already defined and they are less than 25 ms, then in some cases HCOPY creates a wrong representation and the output states have wrong time stamps and sometimes even a duplication of the short phoneme in question. 
We can circumvent this by making sure segments are 25 ms before feeding them into the aligner.
