### ISSUE TITLE
LSTM based RNN

### ISSUE THREAD

**Issue by Ali20177** [CSTR-Edinburgh/merlin#95]
Dear all,

For implementing LSTM-based RNN, I have changed two lines in both "acoustic_demo.conf" & "duration_demo.conf" to:

hidden_layer_type  : ['TANH', 'TANH', 'TANH', 'TANH', 'TANH', 'BLSTM'] 
sequential_training : True

But unfortunately I am still getting a feed-forward DNN. Is there any other files need to change/modify for training parameters under LSTM-RNN?

Thanks in advance

**Comment by bajibabu** [comment]
Don't compile the conf file again after you modified, otherwise they overwrite with default values. Read the run_demo.sh file, first step is about making the conf file.

**Comment by Ali20177** [comment]
Thanks ...

**Comment by bajibabu** [comment]
Please close the issue if you solved the problem..
